DHFPROD-5830: fix for revert entity type
marklogic/marklogic-data-hub pull request #4527
Opened 2020-09-03 22:53 UTC by brucean52

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-09-04 16:30 UTC, timur-isangulov approved these changes
Works fine, tested using scenario in the ticket.

2020-09-04 18:36 UTC, Sanjeevani19 approved these changes
One e2e test fails but not related to this PR so approving.

2020-09-08 16:12 UTC, akshaysonvane requested changes
I'm seeing some weird behavior on revert https://drive.google.com/file/d/1hA35mwK0KC-Jo2tIWE6j1NXNeZ04P15U/view

2020-09-08 18:32 UTC, brucean52 commented
> I'm seeing some weird behavior on revert https://drive.google.com/file/d/1hA35mwK0KC-Jo2tIWE6j1NXNeZ04P15U/view

Fixed this. Please review again

2020-09-08 19:16 UTC, akshaysonvane requested changes
Revert seems fine now. Seeing this issue while saving an entity: https://drive.google.com/file/d/1jsHFjVvQJtzT4xWwpzHrtfgFq6dv8JIo/view

2020-09-08 23:50 UTC, brucean52 commented
> Revert seems fine now. Seeing this issue while saving an entity: https://drive.google.com/file/d/1jsHFjVvQJtzT4xWwpzHrtfgFq6dv8JIo/view

Added the fix for saving an entity.

2020-09-09 15:52 UTC, Sanjeevani19 requested changes
The sort checkmark is still enabled even after saving those changes to database, Once page is refreshed the checkmark disappears.

2020-09-09 21:31 UTC, brucean52 commented
> The sort checkmark is still enabled even after saving those changes to database, Once page is refreshed the checkmark disappears.

Added the fix for Save All and updated e2e tests to cover the regression issues found.

2020-09-09 21:46 UTC, Sanjeevani19 submitted a review, later dismissed

2020-09-09 21:59 UTC, timur-isangulov submitted a review, later dismissed

2020-09-11 18:00 UTC, akshaysonvane requested changes
Revert and save looks good. Seeing this issue while updating the description: https://drive.google.com/file/d/1XHvNNqx7d5dmd5duLpyZgbHgBjTcVbgx/view

2020-09-11 21:00 UTC, brucean52 commented
> Revert and save looks good. Seeing this issue while updating the description: https://drive.google.com/file/d/1XHvNNqx7d5dmd5duLpyZgbHgBjTcVbgx/view

Added fix for entity description editing and added e2e test to cover this case.

2020-09-11 21:02 UTC, Sanjeevani19 approved these changes

2020-09-11 22:12 UTC, akshaysonvane commented on marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.tsx
> +        console.log('entity desc', entityDescription)
Can we get rid of this?

2020-09-11 22:38 UTC, Sanjeevani19 approved these changes

2020-09-11 22:42 UTC, akshaysonvane approved these changes
This looks really good.

2020-09-12 00:03 UTC, merged