DHFPROD-5898:Create hub-central roles to be shown in service portal
marklogic/marklogic-data-hub pull request #4543
Opened 2020-09-10 05:46 UTC by srinathgit

### Description
Create hub-central roles to be shown in service portal
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [N/A ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-09-10 12:26 UTC, rjrudin requested changes

2020-09-10 12:26 UTC, rjrudin commented on examples/reference-entity-model/src/main/ml-config/security/users/wailin.json
> +    "hub-central-curator"
Let's keep the downloader role, we need someone who's not a hc-developer that can do this for testing purposes.

2020-09-10 12:26 UTC, rjrudin commented on marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-curator.json
> +{
We still need tests for all 3 of these new roles. I think we can get away with just reading the role from the Manage API and verifying that the role inherits all of the expected roles. Each assertion should explain why the role is being inherited.

These should be core tests - can put them in the hub.security package.

2020-09-10 14:53 UTC, bsrikan commented on marklogic-data-hub/src/main/resources/hub-internal-config/security/roles/hub-central-curator.json
> +    "hub-central-step-runner",
We can drop this. hc-flow-writer inherits step-runner

2020-09-10 18:31 UTC, bsrikan approved these changes

2020-09-10 18:43 UTC, ryanjdew approved these changes

2020-09-10 19:10 UTC, rjrudin approved these changes

2020-09-11 05:36 UTC, srinathgit commented
@SameeraPriyathamTadikonda ,
I think this can be merged. There are 2 cypress test failures, they are not related to the PR.

2020-09-11 07:24 UTC, merged