DHFPROD-6027: Add intro text to the top of each tile
marklogic/marklogic-data-hub pull request #4638
Opened 2020-09-29 17:27 UTC by wooldridge

Also added tests of intro text display across tile views.

Intro text is stored in the config file for tiles.

Screencast is here: https://drive.google.com/file/d/1tXsvwKT0OBxl5l0fKkFFEs2lePbVj62y/view

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-09-29 18:36 UTC, timur-isangulov approved these changes

2020-09-29 18:44 UTC, briantang approved these changes

2020-09-29 22:04 UTC, briantang requested changes
Seeing the cypress test failures may actually be related to the changes to the intro text in this PR. Can you check if the corresponding changes also need to be made in existing e2e tests?

2020-09-29 23:16 UTC, wooldridge commented
> Seeing the cypress test failures may actually be related to the changes to the intro text in this PR. Can you check if the corresponding changes also need to be made in existing e2e tests?

@briantang, thanks for noticing that. I fixed and force-pushed.

2020-09-29 23:30 UTC, briantang approved these changes

2020-09-30 00:31 UTC, Sanjeevani19 approved these changes

2020-09-30 00:57 UTC, merged