DHFPROD-5537:Default to step 1 if flow name and step are not provided
marklogic/marklogic-data-hub pull request #4645
Opened 2020-09-30 06:41 UTC by srinathgit

### Description
Default to step 1 if flow name and step are not provided
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-09-30 13:11 UTC, rjrudin requested changes

2020-09-30 13:11 UTC, rjrudin commented on marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/RunDefaultIngestionTest.java
> +        Assertions.assertEquals("value", docNode.get("envelope").get("instance").get("testing").asText());
Can you add an assertion on the Job document that gets created (which unfortunately is left in an unfinished state) on flowName = default-ingestion? I'm guessing that's not tested anywhere, so would be good to test here. There's no indication that the first step was run, although that's implied by the flow finishing successfully.

2020-09-30 17:28 UTC, rjrudin submitted a review, later dismissed

2020-09-30 19:51 UTC, rjrudin submitted a review, later dismissed

2020-09-30 20:53 UTC, ryanjdew approved these changes

2020-10-01 11:22 UTC, rjrudin submitted a review, later dismissed

2020-10-01 16:02 UTC, akshaysonvane submitted a review, later dismissed

2020-10-01 16:57 UTC, srinathgit commented
I had to rebase due to merge conflicts

2020-10-01 16:59 UTC, rjrudin approved these changes

2020-10-01 17:53 UTC, akshaysonvane approved these changes

2020-10-01 19:16 UTC, merged