DHFPROD-5891: Running a step collapses the expanded flow
marklogic/marklogic-data-hub pull request #4652
Opened 2020-09-30 23:27 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-10-01 04:21 UTC, wooldridge requested changes
@briantang , I think I'm seeing a remaining issue, can you see if you can reproduce?

The buggy scenario described in the ticket looks fixed:

https://drive.google.com/file/d/1tkkETOn2DbbkkUTnCqzz4Ea0EF_sjXbE/view

However, when I manually try the scenario described in Run.test.tsx: "Verify a flow panel that is closed reopens when a step is added to it"

When I try adding a step to test1, I see a different flow panel open, the panel where I most recently ran a step:

https://drive.google.com/file/d/1R2lIesLdbVc3bPccWt4_SnKuPGYx2ujI/view

Do we need to set panel state during the Add Step process?

2020-10-01 18:32 UTC, briantang commented
Thanks for the catch @wooldridge. It's fixed now.

2020-10-02 02:33 UTC, wooldridge approved these changes

2020-10-02 13:12 UTC, Sanjeevani19 approved these changes

2020-10-02 13:38 UTC, timur-isangulov approved these changes

2020-10-02 16:28 UTC, merged