DHFPROD-6085:Allow removal of properties from step when loading from gradle
marklogic/marklogic-data-hub pull request #4669
Opened 2020-10-06 05:58 UTC by srinathgit

### Description
Allow removal of properties from step when loading from gradle
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-10-06 12:53 UTC, rjrudin requested changes
Looks good, just a couple tweaks

2020-10-06 12:53 UTC, rjrudin commented on marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepService.java
> +    com.fasterxml.jackson.databind.JsonNode saveStep(String stepDefinitionType, com.fasterxml.jackson.databind.JsonNode stepProperties);
Shouldn't DS have removed this method? I think we only want one saveStep method, and I think it's good that the client has to explicitly choose whether to do an overwrite or not.

2020-10-06 12:53 UTC, rjrudin commented on marklogic-data-hub/src/main/java/com/marklogic/hub/dataservices/StepService.java
> +    com.fasterxml.jackson.databind.JsonNode saveStep(String stepDefinitionType, com.fasterxml.jackson.databind.JsonNode stepProperties);
I just tried this locally - I added overwrite:boolean to the API, then ran "gradle generatestepinterface", and the method was updated to include the boolean. That's what we want, we don't want a saveStep method that doesn't require the boolean.

2020-10-06 12:53 UTC, rjrudin commented on marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/customStep/CreateAndUpdateCustomStep.java
> +public class CreateAndUpdateCustomStep extends AbstractHubCoreTest {
Needs to have "Test" suffix so we know it's a test

2020-10-06 12:53 UTC, rjrudin commented on marklogic-data-hub/src/test/java/com/marklogic/hub/dataservices/customStep/CreateAndUpdateCustomStep.java
> +        ObjectMapper mapper = new ObjectMapper();
Can use objectMapper in the parent class

2020-10-07 11:43 UTC, rjrudin approved these changes
This looks good

2020-10-07 14:41 UTC, akshaysonvane approved these changes

2020-10-07 16:22 UTC, merged