DHFPROD-6062:Review Explore test data
marklogic/marklogic-data-hub pull request #4705
Opened 2020-10-12 20:14 UTC by Sanjeevani19

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-10-12 22:08 UTC, wooldridge requested changes
Great work! Looks like we use "modeling" (1 L) across the app so we should use that for the subfolder under mock-data.

Also, what do you think about using "curate" (same as page name) and "explore" for the other subfolders? Consistency and shortness is good.

I know we use Explorer in some places and Explore in others so maybe there's a reason for explorer...

2020-10-12 22:27 UTC, Sanjeevani19 commented
> Great work! Looks like we use "modeling" (1 L) across the app so we should use that for the subfolder under mock-data.
> 
> Also, what do you think about using "curate" (same as page name) and "explore" for the other subfolders? Consistency and shortness is good.
> 
> I know we use Explorer in some places and Explore in others so maybe there's a reason for explorer...

@wooldridge made those changes, ready for review.

2020-10-12 23:53 UTC, briantang approved these changes

2020-10-13 00:19 UTC, wooldridge approved these changes

2020-10-13 04:18 UTC, merged