DHFPROD-6119: Ant Design components are fixed to body element
marklogic/marklogic-data-hub pull request #4734
Opened 2020-10-19 18:43 UTC by xnikhil08

### Description
This is just fixing implementation detail for ant design components, to fix the issue where some components like tooltip, popovers etc., were being fixed to the body element. No tests are required here.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [N/A] Added Tests
  

- ##### Reviewer:

- [N/A] Reviewed Tests

2020-10-19 18:58 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/date-facet/date-facet.tsx
> +                getCalendarContainer={() => document.getElementById('sideBarContainer') || document.body}
The getCalendarContainer() property is specific to the date / time picker component. For all other components its not needed and getPopupContainer should be used.

2020-10-19 20:48 UTC, timur-isangulov approved these changes

2020-10-19 22:10 UTC, wooldridge requested changes
@xnikhil08, nice work! I'm seeing a few issues, not sure if all are related to your changes...

**Explore View**

- Created On menu appears disconnected
- Some tooltips are italic, unlike other tooltips (Close icon tooltip is italic in all views)

https://drive.google.com/file/d/1D7rTSbZ3CDVgXJP0FcQ2rSrCL96i9fC2/view

**Curate View**

- In Mapping details, function menu is throwing an error. (Can you reproduce?)

https://drive.google.com/file/d/1KEVQy_AP93Vf7azO0V_rJcKmbjEU4yHd/view

2020-10-19 22:16 UTC, brucean52 requested changes
In Model tile, Tooltip alignment is off the adding structured types.

<img width="1432" alt="Modeling-structured" src="https://user-images.githubusercontent.com/32427979/96517602-12e13500-121e-11eb-93d2-8e764e2d6310.png">

2020-10-21 00:06 UTC, xnikhil08 commented
> In Model tile, Tooltip alignment is off for adding structured type properties.
> 
> <img alt="Modeling-structured" width="1432" src="https://user-images.githubusercontent.com/32427979/96517602-12e13500-121e-11eb-93d2-8e764e2d6310.png">

@brucean52 - Fixed it but the tooltip will be like the screenshot below.   

![image](https://user-images.githubusercontent.com/19846034/96657210-79d21d00-12f6-11eb-9ef4-326a8a873122.png)

Discussed with Allison and she agreed that it looks ok.

2020-10-21 00:07 UTC, xnikhil08 commented
> @xnikhil08, nice work! I'm seeing a few issues, not sure if all are related to your changes...
> 
> **Explore View**
> 
> * Created On menu appears disconnected
> * Some tooltips are italic, unlike other tooltips (Close icon tooltip is italic in all views)
> 
> https://drive.google.com/file/d/1D7rTSbZ3CDVgXJP0FcQ2rSrCL96i9fC2/view
> 
> **Curate View**
> 
> * In Mapping details, function menu is throwing an error. (Can you reproduce?)
> 
> https://drive.google.com/file/d/1KEVQy_AP93Vf7azO0V_rJcKmbjEU4yHd/view

@wooldridge - All the issues are fixed. But i can't reproduce the function dropdown issue that you mentioned. Looks like its not related to this PR.

2020-10-21 16:20 UTC, wooldridge commented
@xnikhil08, I'm seeing the Mapping details Name search popup not being fixed to the tile container:

https://drive.google.com/file/d/1LEPlaTJN6UEBI4lltsLUNPiuWAr7kPjS/view

Also, I'm still seeing a lot of the tooltips in italics:

<img width="507" alt="Screen Shot 2020-10-21 at 9 15 13 AM" src="https://user-images.githubusercontent.com/477757/96748516-7b472800-137e-11eb-82c4-1a2539e42f4d.png">

2020-10-21 16:20 UTC, wooldridge requested changes
See my comment.

2020-10-21 20:19 UTC, xnikhil08 commented
> See my comment.

@wooldridge - Fixed those issues.

2020-10-21 20:26 UTC, timur-isangulov requested changes
Hi @xnikhil08, the export and column selector icon tooltips are off. 
<img width="351" alt="Screen Shot 2020-10-21 at 1 24 26 PM" src="https://user-images.githubusercontent.com/44847151/96778813-05a08380-13a1-11eb-854d-9fb35d29b204.png">
<img width="319" alt="Screen Shot 2020-10-21 at 1 24 31 PM" src="https://user-images.githubusercontent.com/44847151/96778815-05a08380-13a1-11eb-83c9-2bacd1c8f870.png">

2020-10-21 20:40 UTC, timur-isangulov commented
The tooltips for "Instance" and "JSON" views are bold. 
<img width="436" alt="Screen Shot 2020-10-21 at 1 38 49 PM" src="https://user-images.githubusercontent.com/44847151/96784941-f6bad080-13a2-11eb-946a-a095c865b09a.png">

2020-10-22 00:06 UTC, closed without merging

2020-10-22 00:06 UTC, xnikhil08 commented
Opening a separate PR for develop to avoid confusion.