DHFPROD-6131: Update file picker for running a Load step
marklogic/marklogic-data-hub pull request #4742
Opened 2020-10-20 19:44 UTC by saarimrahman

### Description
react-dropzone offers the same functionality and interaction as the previous file picker, so existing tests capture the scope of this ticket. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- N/A Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-10-21 20:08 UTC, wooldridge requested changes
I'm seeing a layout issue with the Load run button:

<img width="705" alt="Screen Shot 2020-10-21 at 12 56 56 PM" src="https://user-images.githubusercontent.com/477757/96776693-37641b00-139e-11eb-84b3-250caec4172f.png">

The following display CSS should fix it in `flows.tsx`:

```
{props.hasOperatorRole ?
                                    step.stepDefinitionType.toLowerCase() === "ingestion" ?
                                        <div {...getRootProps()} style={{display: 'inline-block'}}>
                                            <input {...getInputProps()} id="fileUpload"/>
```

2020-10-26 01:26 UTC, saarimrahman commented
> I'm seeing a layout issue with the Load run button:

@wooldridge thanks for pointing this out. It has been fixed now.

2020-10-26 18:06 UTC, wooldridge approved these changes

2020-10-26 18:08 UTC, timur-isangulov approved these changes

2020-10-26 18:12 UTC, briantang approved these changes

2020-10-26 18:28 UTC, merged