DHFPROD-6194:Recognize errors in Target Permissions on field blur
marklogic/marklogic-data-hub pull request #4840
Opened 2020-11-10 06:35 UTC by srinathgit

### Description
Recognize errors in Target Permissions on field blur
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-11-10 17:57 UTC, wooldridge requested changes

2020-11-10 17:57 UTC, wooldridge commented on marklogic-data-hub-central/ui/src/components/advanced-settings/advanced-settings-dialog.test.tsx
> +    expect(getByTestId('validationError')).toHaveTextContent('The format of the string is incorrect. The required format is role,capability,role,capability,....');
Let's fix the ellipsis here, it should be three dots (...) not four. (Four dots suggests the string should end in a period, which is incorrect.) And fix it in the place that is being tested: config/messages.config.ts, line 3

2020-11-10 23:31 UTC, briantang requested changes
@srinathgit functionality looks good but I'm seeing related RTL tests failing in other files: 

-mapping-card.test.tsx: Mapping Card component › Open Advanced Step settings
-load-list.test.tx: Load data component › Verify Load settings from list view renders correctly

Could you refactor those respective test files as well?

2020-11-10 23:46 UTC, srinathgit commented
> @srinathgit functionality looks good but I'm seeing related RTL tests failing in other files:
> 
> -mapping-card.test.tsx: Mapping Card component › Open Advanced Step settings
> -load-list.test.tx: Load data component › Verify Load settings from list view renders correctly
> 
> Could you refactor those respective test files as well?

Fixed the failing tests in the latest commit.

2020-11-10 23:59 UTC, briantang approved these changes
Looks good now.

2020-11-11 01:08 UTC, wooldridge approved these changes
Looks good: https://drive.google.com/file/d/1mfXvySK8cC8toYAGD5oTQ-wm-QsxEx-i/view

2020-11-11 01:18 UTC, merged