DHFPROD-4331: Merge Step Advanced Settings
marklogic/marklogic-data-hub pull request #4864
Opened 2020-11-16 05:35 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-11-19 22:33 UTC, wooldridge requested changes
I'm seeing the following error in the RTL tests (fresh install):
```
Summary of all failing tests
 FAIL  src/components/advanced-settings/advanced-settings.test.tsx (49.536s)
  ● Advanced step settings › Verify settings for Merging

    Unable to find an element with the text: Merge. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div
          class="newDataForm"
        >
          <form
            class="ant-form ant-form-horizontal"
          >
            <div
              class="ant-row ant-form-item formItem"
            >
              <div
                class="ant-col ant-form-item-label ant-form-item-label-left ant-col-xs-24 ant-col-sm-7"
              >
                <label
                  class=""
                  title=""
                >
                  <span>
                    Source Database
                  </span>
                </label>
              </div>
              <div
                class="ant-col ant-form-item-control-wrapper ant-col-xs-24 ant-col-sm-15"
              >
                <div
                  class="ant-form-item-control"
                >
                  <span
                    class="ant-form-item-children"
                  >
                    <div
                      class="inputWithTooltip ant-select ant-select-enabled"
                      id="sourceDatabase"
                    >
                      <div
                        aria-autocomplete="list"
                        aria-controls="test-uuid"
                        aria-expanded="false"
                        aria-haspopup="true"
                        aria-label="sourceDatabase-select"
                        class="ant-select-selection
                ant-select-selection--single"
                        role="combobox"
                        tabindex="0"
                      >
                        <div
                          class="ant-select-selection__rendered"
                        >
                          <div
                            class="ant-select-selection__placeholder"
                            style="display: none; user-select: none;"
                            unselectable="on"
                          >
                            Please select source database
                          </div>
                          <div
                            class="ant-select-selection-selected-value"
                            style="display: block; opacity: 1;"
                            title="data-hub-STAGING"
                          >
                            data-hub-STAGING
                          </div>
                        </div>
                        <span
                          class="ant-select-arrow"
                          style="user-select: none;"
                          unselectable="on"
                        >
                          <i
                            aria-label="icon: down"
                            class="anticon anticon-down ant-select-arrow-icon"
                          >
                            <svg
                              aria-hidden="true"
                              class=""
                              data-icon="down"
                              fill="currentColor"
                              focusable="false"
                              height="1em"
                              viewBox="64 64 896 896"
                              width="1em"
                            >
                              <path
                                d="M884 256h-75c-5.1 0-9.9 2.5-12.9 6.6L512 654.2 227.9 262.6c-3-4.1-7.8-6.6-12.9-6.6h-75c-6.5 0-10.3 7.4-6.5 12.7l352.6 486.1c12.8 17.6 39 17.6 51.7 0l352.6-486.1c3.9-5.3.1-12.7-6.4-12.7z"
                              />
                            </svg>
                          </i>
                        </span>
                      </div>
                    </div>
                    <div
                      class="selectTooltip"
                    >
                      <i
                        aria-label="icon: question-circle"
                        class="anticon anticon-question-circle questionCircle ml-tooltip-container"
                      >
                        <svg
                          aria-hidden="true"
                          class=""
                          data-icon="question-circle"
                          fill="currentColor"
                          focusable="false"
                          height="1em"
                          viewBox="64 64 896 896"
                          width="1em"
                        >
                          <path
                            d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm0 708c-22.1 0-40-17.9-40-40s17.9-40 40-40 40 17.9 40 40-17.9 40-40 40zm62.9-219.5a48.3 48.3 0 0 0-30.9 44.8V620c0 4.4-3.6 8-8 8h-48c-4.4 0-8-3.6-8-8v-21.5c0-23.1 6.7-45.9 19.9-64.9 12.9-18.6 30.9-32.8 52.1-40.9 34-13.1 56-41.6 56-72.7 0-44.1-43.1-80-96-80s-96 35.9-96 80v7.6c0 4.4-3.6 8-8 8h-48c-4.4 0-8-3.6-8-8V420c0-39.3 17.2-76 48.4-103.3C430.4 290.4 470 276 512 276s81.6 14.5 111.6 40.7C654.8 344 672 380.7 672 420c0 57.8-38.1 109.8-97.1 132.5z"
                          />
                        </svg>
                      </i>
                    </div>
                  </span>
                </div>
              </div>
            </div>
            <div
              class="ant-row ant-form-item formItem"
            >
              <div
                class="ant-col ant-form-item-label ant-form-item-label-left ant-col-xs-24 ant-col-sm-7"
              >
                <label
                  class=""
                  title=""
                >
                  <span>
                    Target Database
                  </span>
                </label>
              </div>
              <div
                class="...

      184 |     expect(getByText('Additional Collections')).toBeInTheDocument();
      185 |     // merge collections are present
    > 186 |     expect(getByText('Merge')).toBeInTheDocument();
          |            ^
      187 |     expect(getByText('sm-Test-merged sm-Test-mastered')).toBeInTheDocument();
      188 |     expect(getByText('merged')).toBeInTheDocument();
      189 | 

      at Object.getElementError (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/config.js:34:12)
      at node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:71:38
      at getByText (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:54:17)
      at Object.<anonymous> (src/components/advanced-settings/advanced-settings.test.tsx:186:12)


Test Suites: 1 failed, 78 passed, 79 total
Tests:       1 failed, 5 skipped, 360 passed, 366 total
Snapshots:   0 total
Time:        120.359s, estimated 122s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

2020-11-19 23:33 UTC, ryanjdew commented
@wooldridge I've added a waitForElement on the "Merge" text and that seems to resolve that test issue.

2020-11-20 17:42 UTC, Sanjeevani19 approved these changes

2020-11-20 18:21 UTC, wooldridge approved these changes

2020-11-20 22:11 UTC, xnikhil08 approved these changes

2020-11-20 22:21 UTC, merged