DHFPROD-6169:Export rows from TDE view that contains every type of TDE column
marklogic/marklogic-data-hub pull request #4891
Opened 2020-11-19 20:44 UTC by srinathgit

### Description
Export rows from TDE view that contains every type of TDE column
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-11-19 20:46 UTC, srinathgit commented
@rjrudin ,
I am not able to read base64, hexBinary as BinaryType in Spark. hexBinary throws IOException, base64 gets distorted. Should they be read as String as well ?

2020-11-19 20:56 UTC, rjrudin commented
I think reading those as Strings is reasonable. Check with @ehennum  too.

2020-11-23 19:06 UTC, rjrudin requested changes

2020-11-23 19:06 UTC, rjrudin commented on marklogic-data-hub/src/main/resources/ml-modules/root/marklogic-data-hub-spark-connector/readLib.sjs
> +        type: tdeToSparkDataTypeMap.get(column["sys.sys_columns.type"]),
To make this future-proof (in case TDE introduces a new column type), let's say that if the type value is not in the map, we'll just use string.

2020-11-23 19:06 UTC, rjrudin commented on marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadAllDataTypesTest.java
> +        for (InternalRow row : rows) {
For clarity, just do "InternalRow row : rows.get(0)" since we know there's only one.

2020-11-23 19:06 UTC, rjrudin commented on marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadAllDataTypesTest.java
> +            assertEquals(537336758000000L, row.get(13, DataTypes.TimestampType), "dateTime");
Both this and the date row should have assertion messages explaining why these are the expected values, as it's not clear to the casual reader

2020-11-23 19:06 UTC, rjrudin commented on marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadAllDataTypesTest.java
> +                logger.error("Failed to decode binary string: cause; " + e.getMessage());
For tests, just do throw new RuntimeException(e). "fail" is really for when you expect an exception to occur, but one doesn't - in which case, it's better to use assertThrows.

2020-11-23 19:06 UTC, rjrudin commented on marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadAllDataTypesTest.java
> +                logger.error("Failed to decode binary string: cause; " + e.getMessage());
Better yet - don't catch anything, just add "throws Exception" to the test method

2020-11-23 21:24 UTC, srinathgit commented on marklogic-data-hub-spark-connector/src/test/java/com/marklogic/hub/spark/sql/sources/v2/reader/ReadWithSelectedColumnsTest.java
> +        readRows("customerId,customerSince");
It's not meant to be there. I was doing some testing and forgot to remove it. Thanks for catching it.

2020-11-24 13:46 UTC, rjrudin approved these changes

2020-11-24 20:00 UTC, anu3990 approved these changes

2020-11-24 21:08 UTC, merged