DHFPROD-5650: added keyboard controls to tiles toolbar
marklogic/marklogic-data-hub pull request #4898
Opened 2020-11-20 21:40 UTC by jyangML

### Description
in tiles toolbar:
* added keyboard nagivation via up/down arrow keys
* added a customizable outline to "focused" tile icon
* fixed an issue where tiles link buttons' clickable areas were larger than expected
* fixed a visual issue where tiles icons were slightly off-center
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-11-23 07:24 UTC, briantang requested changes
Looks like this PR may be causing several cypress tests to fail in the pipeline. @jyangML can you look into it?

2020-11-24 17:14 UTC, Sanjeevani19 reviewed
@jyangML Some e2e tests are still failing on this PR, Could you please look into them

2020-11-24 23:45 UTC, Sanjeevani19 approved these changes

2020-11-24 23:59 UTC, briantang approved these changes

2020-11-25 00:07 UTC, merged