DHFPROD-6247: Add sourceName to records during ingestion and make it facetable
marklogic/marklogic-data-hub pull request #4905
Opened 2020-11-24 20:21 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-11-24 20:33 UTC, rjrudin requested changes
Looks good, just one tiny test addition - thanks for taking care of this!

2020-11-24 20:33 UTC, rjrudin commented on marklogic-data-hub/src/test/java/com/marklogic/hub/step/impl/IngestWithSourceNameAndSourceTypeTest.java
> +        JsonNode sourcesNode = sourceDoc.get("envelope").get("headers").get("sources").get(1);
Can you add another assertion on "sources[0]", verifying that it's the step name?

2020-11-24 20:52 UTC, rjrudin submitted a review, later dismissed

2020-11-24 23:45 UTC, xnikhil08 approved these changes

2020-11-25 16:24 UTC, timur-isangulov approved these changes

2020-11-25 18:33 UTC, rahulvudutala commented
Made changes to hc-qa-project and fixed e2e tests

2020-11-25 21:11 UTC, rjrudin submitted a review, later dismissed

2020-11-26 00:21 UTC, xnikhil08 submitted a review, later dismissed

2020-11-26 00:39 UTC, ryanjdew submitted a review, later dismissed

2020-11-26 02:55 UTC, rahulvudutala commented
Changed test data for failing calculateMergingActivity.sjs test

2020-11-26 03:09 UTC, ryanjdew approved these changes

2020-11-26 23:36 UTC, Sanjeevani19 approved these changes

2020-11-26 23:38 UTC, merged