DHFPROD-5707: added focus style to Create Flow button
marklogic/marklogic-data-hub pull request #4926
Opened 2020-12-02 15:09 UTC by jyangML

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-12-02 15:15 UTC, jyangML commented
For reviewers: I opted to set the background and outline color in :focus the same as the hover color (which is #5B69AF), but this also made any outlines very faint.  However, when you do tab over, it's immediately noticeable that the button is in focus, so I've decided that the AC is satisfied for now.  Just be sure to take a look before approving this PR.

2020-12-02 23:10 UTC, jyangML commented
Just talked to Kevin, and he's checked off on this :focus style.

2020-12-03 15:19 UTC, jyangML commented
Note: the changes in this PR has been updated to include all MLButton components.

2020-12-03 17:10 UTC, wooldridge requested changes
Nice work, I'm seeing the standalone buttons taking focus with outline styling across the app. 

I think there should be some kind of testing for button focus in the app, similar to what you have for tools in toolbar.test.tsx. How about we add a representative test for buttons in the Run tile in flows.test.tsx, and verify that the Create Flow button takes focus. With that button focused, also test that pressing Return displays the expected New Flow dialog.

A couple fixes for toolbar.test.tsx, change the two instances of Typescript "int" to "number". Also distinguish the two tests at the end in the descriptions, call the second one: "verify arrow key selection of tile icons"

2020-12-03 18:22 UTC, jyangML commented
new changes:
fixed names in toolbar.test.tsx
added a test in flows.test.tsx
cleaned up code for Create Flow button in flows.tsx

2020-12-03 18:59 UTC, jyangML commented
fixed an issue where you can't tab out of the Create Flow button

2020-12-03 19:10 UTC, wooldridge approved these changes
Looks great, here is some manual testing of the keyboard nav:  https://drive.google.com/file/d/1o_2bq7Gl5XE0mLqicvojnOzhSlSbp4Gh/view

Unit tests pass.

2020-12-03 19:12 UTC, wooldridge commented
Reviewers, note that contrary to the N/Aed checkboxes above, there were tests added.

2020-12-03 19:21 UTC, Sanjeevani19 commented
> Reviewers, note that contrary to the N/Aed checkboxes above, there were tests added.

2020-12-03 19:23 UTC, Sanjeevani19 commented
> Reviewers, note that contrary to the N/Aed checkboxes above, there were tests added.

@wooldridge @jyangML Just for consistency purpose since unit tests are there I have enable added tests checkbox.

2020-12-03 19:23 UTC, Sanjeevani19 approved these changes

2020-12-03 19:28 UTC, briantang requested changes

2020-12-03 19:28 UTC, briantang commented on marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
> +        expect(getByText("New Flow")).toBeInTheDocument();
@jyangML Seeing the unit test failing on this line. Can you take a look?

2020-12-03 19:38 UTC, briantang commented on marklogic-data-hub-central/ui/src/components/flows/flows.test.tsx
> +        expect(getByText("New Flow")).toBeInTheDocument();
Disregard this, did not have the latest changes. Looks good now.

2020-12-03 19:38 UTC, briantang approved these changes
Looks good, tests pass.

2020-12-03 19:48 UTC, merged