DHFPROD-6200: Reset page options when switching between databases
marklogic/marklogic-data-hub pull request #4939
Opened 2020-12-04 05:55 UTC by xnikhil08

### Description
Resolving the bug DHFPROD-6200 where the search response page options were not getting reset upon changing the database.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-12-04 17:10 UTC, timur-isangulov requested changes
@xnikhil08, modified e2e test failed on pipeline. Can you please fix it.

2020-12-04 21:16 UTC, timur-isangulov approved these changes

2020-12-04 23:41 UTC, brucean52 approved these changes

2020-12-07 22:51 UTC, Sanjeevani19 requested changes
@xnikhil08 Looks like a rebase is needed. please look into it.

2020-12-08 21:54 UTC, Sanjeevani19 approved these changes

2020-12-08 21:54 UTC, timur-isangulov approved these changes

2020-12-08 21:57 UTC, brucean52 approved these changes

2020-12-09 01:30 UTC, merged