DHFPROD-6216: Optimize match summary range index
marklogic/marklogic-data-hub pull request #4964
Opened 2020-12-08 21:59 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- N/A Added Tests
  

- ##### Reviewer:

-  N/A Reviewed Tests

2020-12-08 22:02 UTC, fsnow approved these changes

2020-12-08 22:16 UTC, rjrudin requested changes
I need to research this further, as we have DHFPROD-6271 open to undo a temporary change I made so that final-database.xml is updated during hubUpdate. I think this ticket will require a little more surgery - i.e. "//actionDetails" needs to be removed if it exists, and then "/matchSummary/actionDetails" needs to be added if it doesn't exist. But I need to dig a bit deeper to remember what's going on with these files under ml-config.

2020-12-08 22:20 UTC, ryanjdew commented
@rjrudin After doing a bootstrap on my instance I only have the "/matchSummary/actionDetails" index, but I'm fine with parking this in draft state for a bit.

2020-12-08 22:23 UTC, rjrudin commented
@ryanjdew  That's due to the hack I put in to fix a bug on the develop branch (the hack is that final-database.xml is overwritten if it exists); I opened up 6271 to undo the hack and surgically update final-database.xml. 

I think we may need a meeting though to consider the pros and cons of having DHF basically say - I own the definition of the files under ml-config/database-fields. That would make this issue go away.

2020-12-09 20:02 UTC, rjrudin approved these changes

2020-12-10 17:37 UTC, merged