DHFPROD-6231:Mapping step fails when provenance is set to "fine"
marklogic/marklogic-data-hub pull request #4967
Opened 2020-12-09 07:27 UTC by srinathgit

### Description
Mapping step fails when provenance is set to "fine"
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-12-09 13:44 UTC, rjrudin requested changes

2020-12-09 13:44 UTC, rjrudin commented on marklogic-data-hub/src/test/resources/test-projects/provenance-test/flows/inline.flow.json
> +        "provenanceGranularityLevel": "fine",
I think it's worth adding an assertion to GetRecordTest (it's tangential to the test, but I think it's fine to stuff it in there) verifying that there's no error in stepOutput, and the test should verify that prov is set to "fine" in the step config as well. The assertion messages can state that we expect the step to not fail, even though fine is not supported for a mapping step.

2020-12-09 19:08 UTC, rjrudin approved these changes

2020-12-09 19:50 UTC, akshaysonvane approved these changes

2020-12-09 22:10 UTC, ryanjdew submitted a review, later dismissed

2020-12-10 22:17 UTC, rjrudin approved these changes

2020-12-10 23:56 UTC, akshaysonvane approved these changes

2020-12-11 01:04 UTC, merged