DHFPROD-6259: Timestamp should be shown by default in priority order slider
marklogic/marklogic-data-hub pull request #5015
Opened 2020-12-17 01:39 UTC by xnikhil08

### Description
Adding default timestamp handle on multi-slider in merging step detail.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-12-17 17:31 UTC, ryanjdew approved these changes

2020-12-17 20:01 UTC, Sanjeevani19 requested changes
@xnikhil08 Looks like priority order tooltip is missing as mentioned in the comments, Please look into it.

2020-12-17 22:08 UTC, xnikhil08 commented
> @xnikhil08 Looks like priority order tooltip is missing as mentioned in the comments for DHFPROD-6259, Please look into it.

@Sanjeevani19 - Added the tooltip for priority order slider.

2020-12-17 22:59 UTC, Sanjeevani19 commented
> > @xnikhil08 Looks like priority order tooltip is missing as mentioned in the comments for DHFPROD-6259, Please look into it.
> 
> @Sanjeevani19 - Added the tooltip for priority order slider.

@xnikhil08 looks like there are few merge conflicts, Could you please resolve them

2020-12-18 16:21 UTC, brucean52 approved these changes

2020-12-18 16:24 UTC, Sanjeevani19 approved these changes

2020-12-18 17:14 UTC, merged