DHFPROD-6374: Use target database for autocomplete endpoint in create…
marklogic/marklogic-data-hub pull request #5020
Opened 2020-12-17 20:10 UTC by brucean52

… edit step

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-12-18 16:57 UTC, Sanjeevani19 approved these changes

2020-12-18 18:29 UTC, briantang requested changes
Seeing the endpoint database change properly when the source database is edited inside a step (for example from staging to final). But following that, creating a new mapping step continues to use final database for the endpoint when I think it should be staging by default.

2020-12-21 16:45 UTC, brucean52 commented
> Seeing the endpoint database change properly when the source database is edited inside a step (for example from staging to final). But following that, creating a new mapping step continues to use final database for the endpoint when I think it should be staging by default.

Mapping step uses the create-edit-mapping component and is out of scope of this bug.

2020-12-21 17:19 UTC, briantang approved these changes

2020-12-21 20:12 UTC, merged