DHFPROD-6367: Document with encoded URI cannot be viewed
marklogic/marklogic-data-hub pull request #5039
Opened 2020-12-21 21:41 UTC by timur-isangulov

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2020-12-21 22:24 UTC, rahulvudutala commented
Can we have a cypress test for this scenario?

2020-12-21 22:27 UTC, rahulvudutala requested changes
Can we have a cypress test for this scenario by ingesting documents with docUri's such as "has%20space.json" and "has spcae.json" and succesfully fetching them from database

2020-12-22 00:08 UTC, rahulvudutala approved these changes

2020-12-22 16:05 UTC, Sanjeevani19 approved these changes

2020-12-22 18:19 UTC, merged