Add palamida scan devo 110
marklogic/marklogic-data-hub pull request #5082
Opened 2021-01-11 20:58 UTC by yafeldman

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-01-12 13:11 UTC, rjrudin requested changes
@yafeldman This needs a JIRA ticket in the beginning of the commit message.

@SameeraPriyathamTadikonda  Why are we using a separate JIRA project and not the DHF project? I'd prefer if all changes to this repository go through the DHF project.

2021-01-12 18:07 UTC, yafeldman commented
fixed PR description with JIRA ticket in the beginning

2021-01-12 19:17 UTC, SameeraPriyathamTadikonda commented
> @yafeldman This needs a JIRA ticket in the beginning of the commit message.
> 
> @SameeraPriyathamTadikonda Why are we using a separate JIRA project and not the DHF project? I'd prefer if all changes to this repository go through the DHF project.

@rjrudin we are tracking all the ci/cd related issues in DEVOPS board. We are not sure under which epic does the ci/cd work goes and the tasks we create affects the sprint as we create tasks in middle of the sprint. So, we are using Devops board in kanban fashion.

2021-01-12 20:23 UTC, SameeraPriyathamTadikonda approved these changes

2021-01-14 18:32 UTC, rjrudin approved these changes

2021-01-14 21:23 UTC, merged