DHFPROD-6453: Explorer won't search on All Data if no entities are lo…
marklogic/marklogic-data-hub pull request #5084
Opened 2021-01-11 21:14 UTC by timur-isangulov

…aded/created

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

2021-01-11 23:57 UTC, ryanjdew requested changes
I'm still seeing the results as empty depending on where I start the search from. Video here: https://drive.google.com/file/d/1tpD0Y4Nr7pK0FpdvcA69GOYrzVgElQVX/view?usp=sharing

2021-01-12 01:23 UTC, timur-isangulov commented
> I'm still seeing the results as empty depending on where I start the search from. Video here: https://drive.google.com/file/d/1tpD0Y4Nr7pK0FpdvcA69GOYrzVgElQVX/view?usp=sharing



> I'm still seeing the results as empty depending on where I start the search from. Video here: https://drive.google.com/file/d/1tpD0Y4Nr7pK0FpdvcA69GOYrzVgElQVX/view?usp=sharing

Hi @ryanjdew, can you please test again. Thanks.

2021-01-12 17:40 UTC, ryanjdew approved these changes

2021-01-12 21:16 UTC, brucean52 approved these changes

2021-01-12 21:19 UTC, merged