DHFPROD-6511: fixed input textbox lag in new step dialogs
marklogic/marklogic-data-hub pull request #5147
Opened 2021-01-21 20:47 UTC by jyangML

### Description
Original problem: new/edit step dialogs would send a payload on every keystroke.  steps.tsx can't process this very quickly, so there's a lag between user keystroke and when it appears on screen.  This fix replaces the update criteria to when the user shifts focus instead (for ex. user presses Save, or user moves onto the next input).

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-01-21 23:00 UTC, wooldridge approved these changes
Nice simple fix! I'm not seeing the delay anymore in all new/edit steps.

2021-01-21 23:06 UTC, wooldridge requested changes
Actually, I'm seeing some settings-related tests fail now (in steps.test and Load.test). I suspect it's not enough to just change field content to test discard changes functionality, you'll need to unfocus the field after changing.

2021-01-22 08:40 UTC, wooldridge commented
@jyangML, looks like RTL doesn't always play nice with document.activeElement: https://github.com/testing-library/react-testing-library/issues/276

I was able to fix the failing tests by wrapping certain form interactions in focus/blur. This triggers the payload-saving useEffect. PR to your branch here: https://github.com/jyangML/marklogic-data-hub/pull/2

2021-01-22 18:44 UTC, jyangML commented
Squashed Mike's RTL fixes

2021-01-22 21:06 UTC, brucean52 submitted a review, later dismissed

2021-01-22 23:40 UTC, wooldridge approved these changes

2021-01-25 22:05 UTC, jyangML commented
Rebased from develop

2021-01-26 17:57 UTC, wooldridge submitted a review, later dismissed

2021-01-26 18:18 UTC, briantang submitted a review, later dismissed

2021-01-26 18:42 UTC, brucean52 submitted a review, later dismissed

2021-01-28 22:30 UTC, briantang requested changes
Looks better, but for a new map step, seeing the 'Advanced' tab disabled (but still clickable) even though the form is valid. I think maybe a validation flag is getting lost with the latest change. Works fine for all other steps though.

2021-01-28 23:23 UTC, briantang approved these changes
Looks good now.

2021-01-29 00:17 UTC, brucean52 approved these changes

2021-01-29 01:01 UTC, merged