DHFPROD-6541: fixed incompatible children type in multi-slider
marklogic/marklogic-data-hub pull request #5203
Opened 2021-02-01 20:02 UTC by jyangML

### Description
Reviews should verify that there are no red console warnings when adjusting sliders in **Step Details** for any **Matching** step.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-02-01 22:58 UTC, briantang submitted a review, later dismissed
Looks good, warnings are gone.

2021-02-01 22:59 UTC, wooldridge requested changes
Let's fix a couple more console warnings in this PR. The ones that come up for the merge view for the tables missing unique row keys. I made a PR that fixes this and I see tests pass: https://github.com/jyangML/marklogic-data-hub/pull/3

@jyangML, can you check that and, if it looks OK, merge, squash, and force-push?

2021-02-01 23:04 UTC, jyangML commented
Squashed Mike's changes and rebased

2021-02-01 23:22 UTC, wooldridge commented
MLTable didn't like the way I set the rowKey. One more fix to make the rowKey compatible with both Table and MLTable: https://github.com/jyangML/marklogic-data-hub/pull/4

(Not sure why two different types of table components are being used--Table and MLTable--but we can leave that for another day.)

2021-02-01 23:29 UTC, Sanjeevani19 approved these changes
Looks good, Don't see console failures anymore

2021-02-01 23:30 UTC, wooldridge approved these changes
Nice, console now looks clean for Match and Merge tabs.

2021-02-02 00:20 UTC, timur-isangulov approved these changes

2021-02-02 00:24 UTC, merged