DHFPROD-6632: Advanced tab is enabled in a new step with invalid name field
marklogic/marklogic-data-hub pull request #5215
Opened 2021-02-05 20:11 UTC by devinnicholson

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

2021-02-06 00:28 UTC, briantang approved these changes

2021-02-06 00:50 UTC, brucean52 submitted a review, later dismissed

2021-02-06 00:58 UTC, wooldridge requested changes
@devinnicholson, do we need to add this check for Load steps?

2021-02-06 01:45 UTC, wooldridge approved these changes
Checked creation of all step types, validation and tab function works as expected, nice!

2021-02-08 07:11 UTC, briantang approved these changes

2021-02-08 16:39 UTC, timur-isangulov approved these changes

2021-02-08 17:41 UTC, merged