DHFPROD-6622: Fix for trace-ui security vulnerabilities
marklogic/marklogic-data-hub pull request #5216
Opened 2021-02-05 20:42 UTC by xnikhil08

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-02-05 21:03 UTC, wooldridge approved these changes

2021-02-05 21:05 UTC, srinathgit requested changes
Please run 4.x flows and make sure trace ui comes up fine without issues at localhost:8013 and do a sanity test to ensure it is good.

2021-02-05 23:50 UTC, xnikhil08 commented
> Please run 4.x flows and make sure trace ui comes up fine without issues at localhost:8013 and do a sanity test to ensure it is good.

@srinathgit - The trace ui works fine and the associated test also was executed successfully.

![image](https://user-images.githubusercontent.com/19846034/107100635-d7b54280-67c9-11eb-9fe4-e44ea968abc5.png)

2021-02-06 00:31 UTC, srinathgit approved these changes

2021-02-06 00:43 UTC, rjrudin approved these changes
Great job @xnikhil08 ! Thanks for taking care of this.

2021-02-06 00:46 UTC, merged