DHFPROD-6111:Tooltip for source doc should only appear for truncated values
marklogic/marklogic-data-hub pull request #5223
Opened 2021-02-09 04:51 UTC by srinathgit

### Description
Tooltip for source doc should only appear for truncated values
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-02-09 18:13 UTC, briantang approved these changes
Looks good, tooltip only appears for truncated values now in the source table. Tests pass.

2021-02-10 00:54 UTC, wooldridge requested changes
Looks good, I see the tooltips appearing only for truncated values: https://drive.google.com/file/d/1oR0CjtCm1ZsyYUJN7p4TVmF3kKT_ygue/view

@srinathgit, the ticket says the following:

"Tooltips should also appear below and centered on the value."

Right now they are **above** and centered. Does this need adjustment? CC: @jbelonoj

2021-02-10 01:11 UTC, srinathgit commented
@wooldridge 
The tooltip text will now appear below for the "Value" column in "Source" table

2021-02-10 01:39 UTC, wooldridge approved these changes

2021-02-10 17:41 UTC, briantang approved these changes

2021-02-10 18:55 UTC, merged