DHFPROD-6660: Fix Advanced Target Collections change checking
marklogic/marklogic-data-hub pull request #5226
Opened 2021-02-09 19:32 UTC by wooldridge

### Description

Changes to Advanced Target Collections values in Merge settings should not trigger the Discard Changes alert (since such values are saved independently). Here's the problem: https://drive.google.com/file/d/1BUQj9FRMM_mIji2wGxAqTiahLhYH_GHt/view

Test added in steps-test.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-02-09 21:09 UTC, briantang submitted a review, later dismissed

2021-02-09 22:51 UTC, timur-isangulov submitted a review, later dismissed

2021-02-10 20:07 UTC, wooldridge commented
Rebased the PR branch on develop, CICD is rerunning.

2021-02-10 21:22 UTC, briantang requested changes
Still an e2e failure that I believe is related to the PR. Fails when expecting discard changes to appear but the PR removes that check. 
@wooldridge Please refer to merging.spec.tsx:84-85, I think that check needs to be updated.

2021-02-11 02:20 UTC, wooldridge commented
> Still an e2e failure that I believe is related to the PR. Fails when expecting discard changes to appear but the PR removes that check.
> @wooldridge Please refer to merging.spec.tsx:84-85, I think that check needs to be updated.

@briantang, I fixed the merging e2e test and force-pushed.

2021-02-11 20:56 UTC, briantang approved these changes
Looks good, e2e passes in the pipeline now.  One backend test failure seems unrelated.

2021-02-11 21:28 UTC, xnikhil08 approved these changes
looks good

2021-02-11 23:04 UTC, merged