DHFPROD-6668:Add "eval-search-string" privilege to Datahub
marklogic/marklogic-data-hub pull request #5233
Opened 2021-02-11 20:30 UTC by srinathgit

### Description
Add "eval-search-string" privilege to Datahub
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-02-11 20:34 UTC, rjrudin requested changes

2021-02-11 20:34 UTC, rjrudin commented on marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
> +        assertEquals(1, resultsHandle.getTotalResults());
Can you add an assertion message stating that this works because the user has the eval-search-string privilege?

2021-02-11 20:34 UTC, rjrudin commented on marklogic-data-hub/src/test/java/com/marklogic/hub/security/DataHubOperatorTest.java
> +        assertThrows(ForbiddenUserException.class, ()->queryManager.search(queryManager.newRawQueryByExampleDefinition(rawHandle), new SearchHandle()));
Same thing here - use an assertion message to explain why this doesn't work. A benefit of the message is that when someone searches on "eval-search-string" in the codebase, they'll find both the role that inherits it and the test that explains why it's inherited

2021-02-11 21:02 UTC, rjrudin approved these changes

2021-02-12 17:52 UTC, ryanjdew approved these changes

2021-02-12 21:19 UTC, merged