DHFPROD-6667:Fix intermittent failure unzipping file
marklogic/marklogic-data-hub pull request #5255
Opened 2021-02-18 04:02 UTC by srinathgit

### Description
Fix intermittent failure unzipping file
#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-02-18 12:05 UTC, rjrudin approved these changes

2021-02-18 17:14 UTC, Sanjeevani19 approved these changes

2021-02-18 17:23 UTC, ryanjdew approved these changes

2021-02-18 23:02 UTC, Sanjeevani19 reviewed
@srinathgit zip test still fails on latest build, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5255/3/tests, please look into it

2021-02-18 23:03 UTC, SameeraPriyathamTadikonda requested changes
Test failing again.
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5255/3/tests/

2021-02-19 12:19 UTC, rjrudin approved these changes

2021-02-19 16:19 UTC, SameeraPriyathamTadikonda approved these changes

2021-02-19 16:19 UTC, merged