DHFPROD-7009: Fixing bug with saving step definition
marklogic/marklogic-data-hub pull request #5342
Opened 2021-03-10 19:49 UTC by rjrudin

### Description

The logic for checking on "default-" isn't needed because OOTB DHF step definitions are loaded via /v1/documents, not the artifacts endpoint. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-03-10 19:53 UTC, srinathgit requested changes

2021-03-10 19:53 UTC, srinathgit commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs
> +            dir = dir + stepDefinition.type.toLowerCase() + "/" + stepDefinition.name + "/";
@rjrudin 
The ootb step definition's uri is /step-definitions/mapping/marklogic/default-mapping.step.json
The user defined step definition would be something like /step-definition/custom/myCustom/myCustom.step.json
Therefore, we may want to have this if-else.

2021-03-10 20:17 UTC, srinathgit commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/artifacts/stepDefinition.sjs
> +            dir = dir + stepDefinition.type.toLowerCase() + "/" + stepDefinition.name + "/";
Had a conversation with @rjrudin , ootb step defs are loaded through v1/documents

2021-03-10 20:18 UTC, srinathgit approved these changes

2021-03-10 20:25 UTC, ryanjdew submitted a review, later dismissed

2021-03-12 06:31 UTC, srinathgit commented
@yafeldman , @SameeraPriyathamTadikonda 
The tests are not running. Pre Build checks failed.

2021-03-12 15:36 UTC, rjrudin commented
Rebased

2021-03-12 17:53 UTC, srinathgit approved these changes

2021-03-12 18:32 UTC, ryanjdew approved these changes

2021-03-12 19:34 UTC, merged

2021-03-12 19:35 UTC, srinathgit commented
@rjrudin 
Should a PR be created for all 5.4.1 bug fixes for develop as well ?