DHFPROD-7028: fixed custom step additional settings not displaying in UI
marklogic/marklogic-data-hub pull request #5367
Opened 2021-03-15 19:35 UTC by jyangML

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

2021-03-15 22:31 UTC, srinathgit requested changes
Can you add an e2e test ? The last time there was unit test and we didn't catch it since there was no e2e test

2021-03-16 15:50 UTC, srinathgit submitted a review, later dismissed

2021-03-16 17:02 UTC, wooldridge submitted a review, later dismissed

2021-03-16 19:34 UTC, jyangML commented
Oops, forgot to update RTL test

2021-03-16 22:57 UTC, srinathgit approved these changes

2021-03-18 23:42 UTC, wooldridge approved these changes

2021-03-18 23:45 UTC, merged