DHFPROD-5754: Retain state when navigating away and back to Model tile
marklogic/marklogic-data-hub pull request #5437
Opened 2021-03-29 23:25 UTC by devinnicholson

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-03-30 16:32 UTC, timur-isangulov requested changes
Hi @devinnicholson, there is one unit tests failure on pipeline and it fails locally for me when using this branch. Can you please look.

2021-04-05 16:24 UTC, timur-isangulov submitted a review, later dismissed

2021-04-05 16:31 UTC, Sanjeevani19 approved these changes

2021-04-05 16:33 UTC, Sanjeevani19 reviewed
@devinnicholson I see a couple of cypress tests are failing, Could you please check if those are related ? https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5437/18/pipeline

2021-04-05 20:40 UTC, devinnicholson commented
> @devinnicholson I see a couple of cypress tests are failing, Could you please check if those are related ? https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5437/18/pipeline

Fixing now- I pushed a fix for rtl tests that broke cypress tests.

2021-04-05 23:59 UTC, timur-isangulov approved these changes

2021-04-06 01:16 UTC, Sanjeevani19 approved these changes

2021-04-06 01:18 UTC, wooldridge approved these changes

2021-04-06 01:30 UTC, merged