DHFPROD-5227: Ruleset form for selecting multiple properties
marklogic/marklogic-data-hub pull request #5453
Opened 2021-03-31 21:44 UTC by xnikhil08

### Description
Just the dummy version of UI. The multiple ruleset form doesn't save yet. End to end tests will be added in future stories where form will be saved with relevant data.
- UX changes are approved by @jbelonoj

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-04-01 18:30 UTC, wooldridge requested changes
Looks slick! Minor issue, the tooltips on the right side are misaligned, I know you have experience with this annoying issue.
<img width="458" alt="Screen Shot 2021-04-01 at 11 26 51 AM" src="https://user-images.githubusercontent.com/477757/113338156-9464e500-92dd-11eb-8590-83cff7192f66.png">

2021-04-05 21:18 UTC, Sanjeevani19 approved these changes
Looks good

2021-04-05 21:42 UTC, timur-isangulov submitted a review, later dismissed

2021-04-05 22:06 UTC, Sanjeevani19 approved these changes

2021-04-05 22:07 UTC, timur-isangulov approved these changes

2021-04-05 22:48 UTC, wooldridge approved these changes

2021-04-05 22:49 UTC, ngodugu-marklogic approved these changes

2021-04-06 00:55 UTC, merged