DHFPROD-7053: Code refactor for ML libraries using Optic For Querying Jobs Data
marklogic/marklogic-data-hub pull request #5466
Opened 2021-04-05 17:57 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-04-05 19:02 UTC, ryanjdew approved these changes

2021-04-05 19:19 UTC, rjrudin requested changes
@ryanjdew @srinathgit  See my comments about a new DS endpoint to finish hub deployment - I think that's consistent with our shift of logic from Java to ML, and it also makes life easier in the future. 

The main difference here is we really don't need to be loading anything dynamically from the classpath - we know exactly what templates we want to install, and so we may as well toss knowledge of that into DHF modules as opposed to Java code.

2021-04-05 19:19 UTC, rjrudin commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/jobs/job-query-lib.sjs
> +      'Job.StepResponse.successfulEvents as successfulItemCount,' +
I think the template needs to be updated with these names also - the template is projecting column names on top of the data, where we can rename things that have misleading names.

2021-04-05 19:19 UTC, rjrudin commented on marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/LoadHubTemplatesCommand.java
> +            for (Resource r : resolver.getResources("classpath*:/hub-templates/**/*.json")) {
Taking a second look at this - this approach of finding files on the classpath makes sense for e.g. figuring out what databases/roles/etc to deploy. But once we've loaded the DHF modules into the modules database, it seems the simplest thing to do is have an e.g. "installJobTemplates" function in job-query-lib, which will write the template to both schema databases.

We then just need a single command to call a single DS endpoint to finish deployment of DHF after all the resources/modules have been deployed - e.g. "finishHubDeployment". The concept is that once we've got all the modules in place, we can invoke a DS endpoint that knows what else needs to be done. 

That also moves all of this logic from Java code into ML, which is typically what we want to do. 

Thus, I'm proposing the following:

- Change this command to "FinishHubDeploymentCommand"
- Make a new endpoint in the "data-services/system" directory called "finishHubDeployment"
- Have that endpoint call job-query-lib:installJobTemplates() (there's only one template, but there could clearly be a Job/Job template in the near future)

I know that's some rework now, but it'll make life easy for when we have future deployment needs that we can handle via DHF modules - we just invoke that code in the finishHubDeployment endpoint, and we don't have to touch any Java code.

2021-04-06 11:41 UTC, rjrudin requested changes
Looks good, just one tweak for the sort order

2021-04-06 11:41 UTC, rjrudin commented on marklogic-data-hub/src/main/java/com/marklogic/hub/deploy/commands/FinishHubDeploymentCommand.java
> +        setExecuteSortOrder(SortOrderConstants.DEPLOY_TRIGGERS + 1);
I think this should be max integer to ensure this runs after everything else is done, which is what the name implies.

2021-04-06 15:40 UTC, rjrudin approved these changes

2021-04-06 16:36 UTC, ryanjdew approved these changes

2021-04-06 17:14 UTC, merged