DHFPROD-6525: Can now control whether Batch docs are created
marklogic/marklogic-data-hub pull request #5474
Opened 2021-04-06 18:47 UTC by rjrudin

### Description

createBatch/updateBatch are gone; we only have insertBatch now. So no amp needed for updateBatch anymore.

Also fixed an issue in the test plumbing where "getJobDocCount" was actually get legacy job docs, not DHF 5 job docs. 

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-04-06 22:16 UTC, ryanjdew submitted a review, later dismissed

2021-04-06 22:18 UTC, srinathgit approved these changes

2021-04-07 13:00 UTC, rjrudin commented
Fixed merge conflict in flow.sjs,  had "content" instead of "contentArray"

2021-04-07 17:53 UTC, ryanjdew submitted a review, later dismissed

2021-04-07 19:31 UTC, srinathgit requested changes
There are a few core unit tests failures
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5474/7/tests

2021-04-07 20:56 UTC, rjrudin commented
Few more test fixes - two were looking for the deleted amp, the other two were failing because I dropped the work on DHFPROD-2445, which is now back.

2021-04-08 01:06 UTC, srinathgit approved these changes

2021-04-08 14:03 UTC, fsnow approved these changes

2021-04-08 18:15 UTC, merged