DHFPROD-6710: View helpful icons for related entity, multiple, and st…
marklogic/marklogic-data-hub pull request #5486
Opened 2021-04-08 19:44 UTC by timur-isangulov

…ructured types

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests

2021-04-09 05:07 UTC, wooldridge requested changes
I asked this in the ticket, what's the difference between the Foreign Key icon and the Relationship icon?

https://project.marklogic.com/jira/browse/DHFPROD-6710?focusedCommentId=198915&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198915

I know they represent difference things but if they are always together I'm not sure we need both. Or maybe I'm missing something.

2021-04-09 18:25 UTC, timur-isangulov commented
Thanks for comment. Removed the "Related Entity" icon per Julia's request.

2021-04-12 16:21 UTC, Sanjeevani19 approved these changes

2021-04-12 16:44 UTC, briantang approved these changes

2021-04-12 17:34 UTC, wooldridge approved these changes

2021-04-12 17:50 UTC, ngodugu-marklogic approved these changes

2021-04-12 20:34 UTC, xnikhil08 approved these changes

2021-04-14 03:56 UTC, merged