DHFPROD-7099: (5.4) Support matching with complex type XML schemas
marklogic/marklogic-data-hub pull request #5495
Opened 2021-04-09 22:20 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-04-09 23:16 UTC, rjrudin approved these changes

2021-04-12 12:58 UTC, rjrudin requested changes
See my comments on the PR for develop

2021-04-12 17:11 UTC, rjrudin approved these changes

2021-04-13 07:33 UTC, srinathgit approved these changes

2021-04-14 18:18 UTC, merged