DHFPROD-7084: Show additional attributes in Jobs table UI
marklogic/marklogic-data-hub pull request #5603
Opened 2021-05-04 21:03 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-05-04 21:05 UTC, ryanjdew approved these changes

2021-05-06 14:30 UTC, Sanjeevani19 requested changes
@rahulvudutala looks like there is a small bug to fix, Steps to repro -
1. Open column selector
2. Check one of the unselected columns
3. Click on cancel
4. Reopen the column selector, the checked columns should be unchecked since the cancel button is clicked
Please update the test scenario with this.

2021-05-06 16:26 UTC, Sanjeevani19 submitted a review, later dismissed

2021-05-06 18:46 UTC, ryanjdew submitted a review, later dismissed

2021-05-06 18:56 UTC, Sanjeevani19 approved these changes

2021-05-06 18:57 UTC, ryanjdew approved these changes

2021-05-06 19:49 UTC, merged