DHFPROD-7270: Add structured properties to the test matched result table
marklogic/marklogic-data-hub pull request #5640
Opened 2021-05-11 18:13 UTC by AkshayBajajML

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-05-11 18:51 UTC, AkshayBajajML commented
@jbelonoj approved UI changes!

2021-05-12 04:16 UTC, xnikhil08 requested changes

2021-05-12 04:16 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
> +    let response = await axios.get("/api/steps/matching");
Let's put all API calls under an appropriate location within **/src/api/***.
This seems like a good candidate for "getSteps", under **/src/api/steps.tsx** and then we can simply call it here like **getSteps("matching")**
Also, let's add another layer of validation by checking if you received a proper response before actually using it further. One of the ways is to check if the value of response.status is "200".

2021-05-12 04:16 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx
> +      return (rulesetType === "exact" || rulesetType === "Exact") && <span className={styles.testMatchedColumns} key={key} aria-label={matchedRulesetType + " " + (index)}>
If the rulesetType is going to be checked for different variations of the same word then might as well convert it to upper or lower case and check it only once.
something like **rulesetType.toLowerCase() === "exact"**
Same goes for all other places where rulesetType is being checked.

2021-05-12 04:16 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/entities/matching/expandable-table-view/expandable-table-view.tsx
> +  let response = await axios.get("/api/steps/matching");
Same comment as in another place. Let's move all the API calls to /src/api/*.

2021-05-12 18:00 UTC, AkshayBajajML commented
@xnikhil08 thanks for the feedback; updated the code and pushed the changes again.

2021-05-12 21:23 UTC, xnikhil08 requested changes

2021-05-12 21:35 UTC, AkshayBajajML commented on marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
> +      console.error("Error While fetching the mapping data", message);
Done!!

2021-05-13 00:19 UTC, xnikhil08 approved these changes

2021-05-13 18:32 UTC, Sanjeevani19 approved these changes

2021-05-13 18:34 UTC, merged