DHFPROD-7302: (5.4) Better messages for common write errors
marklogic/marklogic-data-hub pull request #5661
Opened 2021-05-13 23:39 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-05-14 13:32 UTC, rjrudin requested changes
Same thing as the other PR, just need to change "right" to "write"

2021-05-14 17:04 UTC, srinathgit submitted a review, later dismissed

2021-05-14 17:06 UTC, rjrudin approved these changes

2021-05-17 15:27 UTC, Sanjeevani19 reviewed
@ryanjdew One of the core unit test is failing, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5661/3/tests, could you please look into it ?

2021-05-17 17:57 UTC, rjrudin approved these changes

2021-05-17 17:58 UTC, srinathgit approved these changes

2021-05-17 20:02 UTC, merged