DHFPROD-7131: Handle entities with updated props when building join menu
marklogic/marklogic-data-hub pull request #5669
Opened 2021-05-15 02:17 UTC by wooldridge

### Description

Updated properties in entities that have not been saved yet will now show up in the Join Property menu in Modeling.

To test:

- Create a new property for an entity (e.g. Customer). Do not save the entity.
- Create a new entity relationship that points from one entity (Order) to the entity with the new property (Customer).
- Open the Join Property menu to confirm that the new property is included in the list of properties. (Previously, it was not.)

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-05-17 16:38 UTC, srinathgit approved these changes
Verified that the property shows up in 'Order'

2021-05-17 16:54 UTC, briantang approved these changes

2021-05-17 17:01 UTC, xnikhil08 approved these changes

2021-05-17 17:37 UTC, srinathgit requested changes
PR has to be updated based on the discussion we just had

2021-05-17 17:51 UTC, wooldridge commented
In discussion with the team, we decided that when a new property hasn't been saved to the backend yet in Modeling, that property shouldn't be allowed as a Join Property value. The property will be displayed in the menu but be disabled (just like multiple and structured properties are disabled). 

The tooltip associated with the Join Property field currently reads:

"Structured type properties and arrays cannot be used as join properties."

I suggest updating the tooltip to the following:

"Structured type properties, arrays, and unsaved properties cannot be used as join properties."

@sbayatpur does that work for you?

2021-05-18 01:20 UTC, wooldridge commented
> PR has to be updated based on the discussion we just had

@srinathgit I updated the branch to show but also disable unsaved properties in the Join Property menu. Also updated tooltip to explain unsaved properties cannot be used as join properties.

2021-05-18 01:36 UTC, srinathgit submitted a review, later dismissed
Looks good !

2021-05-18 04:35 UTC, briantang submitted a review, later dismissed
Nice!

2021-05-18 22:02 UTC, Sanjeevani19 approved these changes

2021-05-18 22:03 UTC, devinnicholson approved these changes

2021-05-18 22:09 UTC, merged