DHFPROD-7264: Delete mapping expressions for a related entity
marklogic/marklogic-data-hub pull request #5672
Opened 2021-05-16 19:23 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-05-17 20:47 UTC, wooldridge commented
Performed a bunch of manual tests using reference project, see below:

TL;DR: Testing checks out, things look fine, but the unrelated persistence issue (which is known: https://project.marklogic.com/jira/browse/DHFPROD-7304) is arising when returning to the mapping UI.

1. Confirmed mapCustomersWithRelatedEntitiesJSON showed up as expected in UI, all entity tables open.
2. Confirmed mapCustomersWithRelatedEntitiesJSON is as expected in QConsole.
3. After clearing user data, ran load and mapping step for mapCustomersWithRelatedEntitiesJSON, verified entity instances:
Customer (1)
Order (2)
BabyRegistry (1)
Product (6)
4. Deleted Product under BabyRegistry in mapCustomersWithRelatedEntitiesJSON via table X. 
5. Confirmed Product removed from BabyRegistry filter box.
6. Confirmed mapCustomersWithRelatedEntitiesJSON is as expected in QConsole (related Product gone under BabyRegistry).
7. After clearing user data, ran load and mapping step for mapCustomersWithRelatedEntitiesJSON, verified entity instances:
Customer (1)
Order (2)
BabyRegistry (1)
Product (4) (IDs 50, 60 are GONE)
8. Deleted Order under Customer in mapCustomersWithRelatedEntitiesJSON via filter pill in Customer.
9. Confirmed I see warning about needing to delete Product under Order first.
10. Deleted Product under Order in mapCustomersWithRelatedEntitiesJSON via filter pill in Order.
11. Confirmed Product table is gone under Order in UI.
12. Deleted Order under Customer in mapCustomersWithRelatedEntitiesJSON via filter pill in Customer.
13. Confirmed Order table is gone under Customer in UI.
14. Confirmed mapCustomersWithRelatedEntitiesJSON is as expected in QConsole (Customer and BabyRegistry only).
15. After clearing user data, ran load and mapping step for mapCustomersWithRelatedEntitiesJSON, verified entity instances:
Customer (1)
BabyRegistry (1)
16. When I return to the mapping step view for mapCustomersWithRelatedEntitiesJSON, the Order and Product tables ARE BACK, while the Product under BabyRegistry is still GONE.
17. When I hard refresh the browser window, mapCustomersWithRelatedEntitiesJSON goes back to the expected configuration, with  Order and Product tables GONE.
Note: This is a persistence bug being handled here: https://project.marklogic.com/jira/browse/DHFPROD-7304
18. Deleted BabyRegistry under Customer, now no more related entities remain (and relatedEntityMappings property in artifact is now []), and ran the same steps, results are good:
Customer (1)
19. Ran similar tests with mapCustomersWithRelatedEntitiesXML. Results are fine (but still seeing unrelated persistence bug).

2021-05-17 21:04 UTC, wooldridge requested changes
@srinathgit @briantang 

General modeling/mapping bug?

1. Start with a fresh reference project (I redeployed artifacts and wiped user data).
2. In Modeling, create a new relationship between Order and BabyRegistry. Create a new property in BabyRegistry "orderRel" that points to Order, with Join Property "orderId". (Don't worry about whether this makes sense wrt to the source data, we're not testing any mapping expressions here, just relationships.) Save the all changes in Modeling.
3. Go to mapCustomersWithRelatedEntitiesJSON. 
4. I don't see a relationship. Either the related Order entity in the BabyRegistry filter or the related BabyRegistry entity in the Order Filter.

<img width="889" alt="DHFPROD-7264-Order" src="https://user-images.githubusercontent.com/477757/118556190-6f56f500-b718-11eb-9f73-84c7c0fa49fb.png">
<img width="904" alt="DHFPROD-7264-BabyRegistry" src="https://user-images.githubusercontent.com/477757/118556204-71b94f00-b718-11eb-99e8-3bc3114944c6.png">

2021-05-17 22:16 UTC, wooldridge commented
@briantang I see that we do a mapping save (the alert appears) when a related entity is DELETED via the filter or the close icon. But we don't do a save when a related entity is ADDED via the filter:

https://drive.google.com/file/d/1LiTL9CPDpvlW7KI41POnQOFnaaFAxnvp/view

I'm assuming that's because this relationship only has an effect when a property expression in that related entity has been defined. And I see that's when things are saved. Was that the thinking?

2021-05-17 22:45 UTC, briantang commented
> @briantang I see that we do a mapping save (the alert appears) when a related entity is DELETED via the filter or the close icon. But we don't do a save when a related entity is ADDED via the filter:
> 
> https://drive.google.com/file/d/1LiTL9CPDpvlW7KI41POnQOFnaaFAxnvp/view
> 
> I'm assuming that's because this relationship only has an effect when a property expression in that related entity has been defined. And I see that's when things are saved. Was that the thinking?

@wooldridge This is correct. Saving is only necessary to update the artifact when an expression has been defined or something is deleted, so we don't see a save happening when a related entity is added.

2021-05-17 22:51 UTC, wooldridge requested changes
@briantang for the mapCustomersWithRelatedEntitiesJSON mapping in the reference project:

1. I've added a second Product relationship so that BabyRegistry now has two entities related to it.
2. I try to delete BabyRegistry at the Customer level and get a popup saying BabyRegistry has related entities, but it only lists the first Product. 
3. I delete the first Product.
4. Now I try to delete BabyRegistry at the Customer level and I can, successfully. 
5. This leaves a dangling Product that used to be related to BabyRegistry but it now unrelated to anything in view. 

Seems like a bug?

2021-05-17 23:40 UTC, briantang commented
Thanks @wooldridge, pushed a fix for the above issue.

2021-05-18 08:51 UTC, wooldridge commented
Looks good:

https://drive.google.com/file/d/1aS0o3AjH2J84_qORpwTXkkmQuzKexOxG/view

2021-05-18 08:51 UTC, wooldridge approved these changes

2021-05-18 21:01 UTC, wooldridge approved these changes

2021-05-18 22:03 UTC, Sanjeevani19 approved these changes

2021-05-18 22:45 UTC, merged