DHFPROD-7194: Add reference dropdown to mapping UI
marklogic/marklogic-data-hub pull request #5712
Opened 2021-05-25 17:27 UTC by wooldridge

### Description

- Add new dropdown menu for inserting reference values into the XPath Expression field in the mapping UI. Works similarly to the property and function menus that are already there.
- Refactor some of the mapping logic and CSS to make it more DRY.
- Fix the function menu bug so that the mapping UI auto-saves after function insertion. (Property and reference insertion also have auto-save.)
- Note that this PR doesn't description information in the dropdown menu, that feature has been pushed to a separate ticket. This Jira ticket has been updated to note all this.
- Added tests for the reference menu and updated tests for the function menu.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-05-25 23:59 UTC, srinathgit requested changes
I am seeing that when I hit "Test" button and there are errors in xpath expression, they are not showing up after rebasing with your branch
![image](https://user-images.githubusercontent.com/5034960/119582990-86ca5980-bd7a-11eb-8a60-3d4ec6c4cc7b.png)

2021-05-26 16:24 UTC, wooldridge commented
> I am seeing that when I hit "Test" button and there are errors in xpath expression, they are not showing up after rebasing with your branch

@srinathgit thanks, CSS issue, I force-pushed a fix.

2021-05-26 18:01 UTC, srinathgit approved these changes

2021-05-26 18:32 UTC, devinnicholson approved these changes

2021-05-26 20:32 UTC, xnikhil08 approved these changes

2021-05-26 20:59 UTC, merged