DHFPROD-7406: Update middle-tier dependencies
marklogic/marklogic-data-hub pull request #5743
Opened 2021-06-02 18:36 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- N/A Code passes ESLint tests
- N/A Added Tests
  

- ##### Reviewer:

- N/A Reviewed Tests

2021-06-02 19:33 UTC, rjrudin requested changes

2021-06-02 19:33 UTC, rjrudin commented on marklogic-data-hub-central/gradle.properties
> +springBootVersion=2.3.11.RELEASE
The comment above needs to be updated based on these new version numbers - probably better to reword it like this so it doesn't have version numbers:

"Spring Security and Spring Boot are then configured with version numbers to ensure they use the same underlying Spring library version."

2021-06-03 15:55 UTC, rjrudin submitted a review, later dismissed

2021-06-03 16:01 UTC, srinathgit approved these changes

2021-06-04 19:23 UTC, Sanjeevani19 reviewed
@yafeldman @ryanjdew looks like latest build is also failing after a force push https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5743/14/pipeline, @yafeldman could you please work with @ryanjdew to see if it's a pipeline issue

2021-06-04 21:35 UTC, ryanjdew commented
I had to update some things for the latest swagger-ui to work, which was one of the libraries with dependencies that needed updating.

2021-06-04 23:12 UTC, Sanjeevani19 approved these changes

2021-06-04 23:12 UTC, merged