DHFPROD-7418: Clearing applied facet clears only the facet attribute
marklogic/marklogic-data-hub pull request #5744
Opened 2021-06-02 23:24 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests

2021-06-03 16:50 UTC, ryanjdew approved these changes

2021-06-03 22:11 UTC, Sanjeevani19 approved these changes

2021-06-03 22:15 UTC, Sanjeevani19 requested changes
@rahulvudutala Start time grey facet is not being cleared when clicked on individual X button, Please look into it

2021-06-04 17:06 UTC, ryanjdew submitted a review, later dismissed

2021-06-08 16:37 UTC, Sanjeevani19 submitted a review, later dismissed

2021-06-08 17:07 UTC, ryanjdew approved these changes

2021-06-08 17:42 UTC, Sanjeevani19 submitted a review, later dismissed

2021-06-08 20:38 UTC, Sanjeevani19 submitted a review, later dismissed

2021-06-08 20:56 UTC, ryanjdew approved these changes

2021-06-08 21:40 UTC, Sanjeevani19 approved these changes

2021-06-08 21:40 UTC, ngodugu-marklogic submitted a review, later dismissed

2021-06-08 21:44 UTC, Sanjeevani19 submitted a review, later dismissed

2021-06-09 00:20 UTC, Sanjeevani19 submitted a review, later dismissed

2021-06-09 01:45 UTC, ngodugu-marklogic submitted a review, later dismissed

2021-06-09 15:08 UTC, Sanjeevani19 approved these changes

2021-06-09 16:23 UTC, ngodugu-marklogic approved these changes

2021-06-09 16:25 UTC, merged