DHFPROD-7452: Restrict property warnings to property being edited
marklogic/marklogic-data-hub pull request #5845
Opened 2021-06-25 21:06 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-06-25 21:38 UTC, xnikhil08 approved these changes

2021-06-25 21:43 UTC, Sanjeevani19 submitted a review, later dismissed

2021-06-25 22:17 UTC, ngodugu-marklogic requested changes
@ryanjdew I am getting this error when I try to save a merge step https://drive.google.com/file/d/1FmWrXShtupyvYMLTeAujiF1hegvSv2kv/view

2021-06-28 14:53 UTC, Sanjeevani19 reviewed
@ryanjdew Looks like there is an e2e failure related to merge warnings, Please look into it, https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-5845/3/tests

2021-06-28 17:07 UTC, Sanjeevani19 approved these changes

2021-06-28 17:27 UTC, xnikhil08 approved these changes

2021-06-29 23:14 UTC, ngodugu-marklogic approved these changes

2021-06-29 23:14 UTC, Sanjeevani19 approved these changes

2021-06-29 23:15 UTC, merged