DHFPROD-6656: Card selector loses rounded edges
marklogic/marklogic-data-hub pull request #5858
Opened 2021-07-01 20:00 UTC by briantang

### Description
- https://drive.google.com/file/d/1BXmybOWH_Iz5gLWDgO4ZICOF5YjwkQ27/view
- Design reviewed by Jamie

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-07-01 23:13 UTC, wooldridge requested changes
Weird bug, nice work! I'm thinking the the CSS could be slightly more optimized?
```
#zero-state-explorer #viewAsCard {
  .ant-radio-button-wrapper.ant-radio-button-wrapper-checked,
  .ant-radio-button-wrapper:first-child {
    border-radius: 0px 4px 4px 0px;
  }
}
```
Also, I noticed the search box on the zero state page is shifted down one pixel relative to the dropdown to its left, and I was able to fix it like this in the module CSS:
```
  .searchBar {
    top: -1px;
    width: 700px;
  }
```
Do you see that too?

2021-07-01 23:18 UTC, briantang commented
> Weird bug, nice work! I'm thinking the the CSS could be slightly more optimized?
> 
> ```
> #zero-state-explorer #viewAsCard {
>   .ant-radio-button-wrapper.ant-radio-button-wrapper-checked,
>   .ant-radio-button-wrapper:first-child {
>     border-radius: 0px 4px 4px 0px;
>   }
> }
> ```
> 
> Also, I noticed the search box on the zero state page is shifted down one pixel relative to the dropdown to its left, and I was able to fix it like this in the module CSS:
> 
> ```
>   .searchBar {
>     top: -1px;
>     width: 700px;
>   }
> ```
> 
> Do you see that too?

Thanks @wooldridge, saw the same issue and fixed.

2021-07-02 15:35 UTC, Sanjeevani19 approved these changes

2021-07-02 16:45 UTC, wooldridge approved these changes
Looks good!

2021-07-02 17:41 UTC, merged