DHFPROD-7133: Run flows success and error messages
marklogic/marklogic-data-hub pull request #5927
Opened 2021-07-28 04:00 UTC by briantang

### Description

- Added flow status modal upon running multiple steps in a flow in the Run tile
- When a flow has been run, its status modal can be opened via the info icon next to the flow name
- Out of scope: automatic updating of the status modal, so re-visit page to see changes at the moment
- Out of scope: Explore data button on the status modal.
- https://drive.google.com/file/d/1GHPRTM8E88LJP_Lnqw7RwVWhwCb1UXt3/view

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-07-28 17:48 UTC, AkshayBajajML requested changes
Spinner keeps on running once we run flow but looks fine once we close Modal and reopen it.

https://user-images.githubusercontent.com/66277536/127371388-abea2d05-aa03-4400-ba81-babcef347735.mov

2021-07-28 18:00 UTC, briantang commented
> Spinner keeps on running once we run flow but looks fine once we close Modal and reopen it.
> 
>  Screen.Recording.2021-07-28.at.10.46.06.AM.mov

@AkshayBajajML Right. Mentioned in the description that automatic updates to the modal are not a part of this story. That will probably need to be handled with https://project.marklogic.com/jira/browse/DHFPROD-7530. Currently, changes to the status will be seen upon closing and reopening the modal.

2021-07-28 19:00 UTC, briantang commented
Converting to Draft to investigate some issues brought up from @AkshayBajajML

2021-08-03 22:40 UTC, briantang commented
This is ready for review

2021-08-05 23:14 UTC, AkshayBajajML approved these changes
Looks Good!

2021-08-09 16:51 UTC, AkshayBajajML approved these changes

2021-08-09 23:07 UTC, AkshayBajajML approved these changes
All tests pass now

2021-08-09 23:13 UTC, xnikhil08 approved these changes

2021-08-09 23:16 UTC, merged