DHFPROD-6147: Test performance of disableJobOutput
marklogic/marklogic-data-hub pull request #5994
Opened 2021-08-17 18:16 UTC by devinnicholson

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests

2021-08-17 18:31 UTC, devinnicholson commented
Adding auth username/password variables

2021-08-17 23:53 UTC, rjrudin requested changes
I'll try this out in the morning

2021-08-17 23:53 UTC, rjrudin commented on performance-tests/gradle.properties
> +## sourceDocumentCount=1000
This should be in a section of parameters that apply to multiple tests, as it still applies to the mapping functions test

2021-08-18 14:02 UTC, rjrudin submitted a review, later dismissed

2021-08-18 14:02 UTC, rjrudin commented on performance-tests/src/main/jmeter/disable-job-output.jmx
> +          <stringProp name="HTTPSampler.path">/v1/resources/mlRunFlow</stringProp>
We don't want to use this, this endpoint is deprecated (see the comments in it). The code that you have in the "Run flow" component will run the flow, and you can customize that to pass in disableJobOutput in the options Map.

2021-08-18 14:02 UTC, rjrudin commented on performance-tests/src/main/jmeter/disable-job-output.jmx
> +            <stringProp name="Argument.value">${__P(authUsername, admin)}</stringProp>
Use test-data-hub-developer and password here; we know that user exists because it's created via "./gradlew bootstrap".

2021-08-18 14:02 UTC, rjrudin commented on performance-tests/src/main/jmeter/disable-job-output.jmx
> +<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.1.1 r1855137">
Use JMeter 5.4.1, that's the latest release.

2021-08-19 12:26 UTC, rjrudin requested changes
This looks good but needs one change - each job fails because the module path associated with the step definition doesn't exist. That prevents any batch documents from being created, and batch documents are what's going to slow things down the most (since only 1 job doc is created, but N batch docs can be created). 

In the "Create flow" processor, you'll need to insert the following text into the modules database with a URI matching that in the step definition (this is the simplest possible step module):

```
function main(contentItem, options) {
  return contentItem;
}

module.exports = {
  main
};
```

You can use hubClient.getModulesClient().newDocumentManager() to get a DocumentManager that will let you write this.

Then try running the flow with job output enabled, and verify that you're getting both a job doc (with a status of "success") and N batch docs.

2021-08-23 12:08 UTC, rjrudin approved these changes

2021-08-23 16:25 UTC, srinathgit approved these changes

2021-08-23 16:26 UTC, merged