DHFPROD-7680: Component Replacement: Avatar
marklogic/marklogic-data-hub pull request #6012
Opened 2021-08-20 13:12 UTC by federicoRufrancosMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Added Tests
- [X] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-08-20 22:19 UTC, wooldridge approved these changes

2021-08-20 22:27 UTC, briantang requested changes
I see a linting error in the pipeline. Looks like Avatar is no longer used so it can be removed from the antd import at the top of the file.

2021-08-23 14:21 UTC, Sanjeevani19 reviewed
@federicoRufrancosMarklogic This PR needs a rebase, please squash all the commits into one commit

2021-08-23 14:22 UTC, Sanjeevani19 approved these changes

2021-08-23 14:27 UTC, federicoRufrancosMarklogic commented
> I see a linting error in the pipeline. Looks like Avatar is no longer used so it can be removed from the antd import at the top of the file.

solved @briantang

2021-08-23 16:44 UTC, briantang approved these changes

2021-08-23 16:46 UTC, Sanjeevani19 approved these changes

2021-08-23 16:57 UTC, aniamy approved these changes

2021-08-23 18:15 UTC, wooldridge approved these changes

2021-08-23 18:23 UTC, romanlescano approved these changes

2021-08-23 18:34 UTC, merged