DHFPROD-7735: Component Replacement: Divider
marklogic/marklogic-data-hub pull request #6044
Opened 2021-08-27 15:54 UTC by MSBrignoni

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

2021-08-30 15:08 UTC, aniamy approved these changes

2021-08-30 15:33 UTC, iveyMarklogic approved these changes

2021-08-30 15:33 UTC, yubiselmarklogic approved these changes

2021-08-30 15:48 UTC, Sanjeevani19 reviewed
@MSBrignoni there are some lint UI failures on the PR, Please fix them

2021-08-31 13:18 UTC, wooldridge requested changes

2021-08-31 20:27 UTC, MSBrignoni commented on marklogic-data-hub-central/ui/src/components/common/divider/divider.module.scss
> +	color:#a1a1a1;
Resolved!.

2021-08-31 20:28 UTC, MSBrignoni commented on marklogic-data-hub-central/ui/src/components/job-response/job-response.tsx
> +import {Descriptions, Modal, Icon, Collapse, Spin, Button} from "antd";
Resolved.

2021-08-31 20:28 UTC, MSBrignoni commented on marklogic-data-hub-central/ui/src/components/common/divider/divider.tsx
> +const Divider: React.FC<Props> = (props) => {
Resolved.

2021-08-31 20:39 UTC, iveyMarklogic approved these changes

2021-08-31 20:42 UTC, yubiselmarklogic approved these changes

2021-08-31 21:16 UTC, aniamy approved these changes

2021-08-31 21:19 UTC, aniamy approved these changes

2021-08-31 23:32 UTC, wooldridge approved these changes

2021-09-01 12:19 UTC, yubiselmarklogic approved these changes

2021-09-01 13:10 UTC, mrodrigu-marklogic approved these changes

2021-09-01 17:13 UTC, merged