DHFPROD-7558: UI Text in Match Step Details Page
marklogic/marklogic-data-hub pull request #6093
Opened 2021-09-13 19:27 UTC by briantang

### Description

- Minor text updates to match step details page

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-09-13 23:52 UTC, AkshayBajajML submitted a review, later dismissed

2021-09-14 05:33 UTC, xnikhil08 submitted a review, later dismissed

2021-09-14 06:56 UTC, wooldridge approved these changes

2021-09-14 07:09 UTC, wooldridge requested changes
Minor content issue, we capitalize "Match step" in the Match tab intro but lowercase "merge step" and "match step" in the Merge tab intro. I added a query in the Jira ticket about this, we should be consistent.

2021-09-14 16:29 UTC, wooldridge commented
> Minor content issue, we capitalize "Match step" in the Match tab intro but lowercase "merge step" and "match step" in the Merge tab intro. I added a query in the Jira ticket about this, we should be consistent.

@briantang, based on the discussion in the Jira ticket, we're changing "Match step" in the intro text here to "Matching step". With that update in this PR, we should be good to go.

2021-09-15 20:45 UTC, AkshayBajajML approved these changes

2021-09-16 15:40 UTC, wooldridge approved these changes

2021-09-16 20:29 UTC, merged