DHFPROD-7791: Validate entitity model for showing content in Explorer tabular view
marklogic/marklogic-data-hub pull request #6128
Opened 2021-09-21 16:24 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-09-22 18:37 UTC, ryanjdew approved these changes

2021-09-30 19:14 UTC, ryanjdew submitted a review, later dismissed

2021-10-01 19:55 UTC, ryanjdew approved these changes

2021-10-01 22:31 UTC, xnikhil08 submitted a review, later dismissed

2021-10-04 04:53 UTC, briantang requested changes
Looks good but needs linting fix.

2021-10-04 15:34 UTC, rahulvudutala commented
Addressed the linting issues

2021-10-04 16:19 UTC, briantang approved these changes

2021-10-04 23:21 UTC, ryanjdew approved these changes

2021-10-05 17:04 UTC, merged