DHFPROD-7947 - Making Detail view its own tile
marklogic/marklogic-data-hub pull request #6144
Opened 2021-09-27 23:52 UTC by awanczowski

### Description

The detail view shared the same options as the explore tile view. This caused issues with CSS that was targeting the Explore view to hide contents on the detail page.  This change set addresses this by making a detail view its own TileView.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-09-29 17:59 UTC, AkshayBajajML commented
This PR is ready for review

2021-09-29 22:50 UTC, xnikhil08 requested changes
@awanczowski - I can see a new Detail tile option in the tile view toolbar. Let's get rid of it, since the Detail page is explorer related only. Please see the screencast below.
https://drive.google.com/file/d/1hnzMgN0imm6YfFQaDp2kUN_l5S0BrIrs/view

2021-09-29 23:33 UTC, awanczowski commented
@xnikhil08 I added an extra config to hide tiles icons the toolbar and added a descriptor to the pane title "Explore - Details"

2021-09-30 16:15 UTC, wooldridge requested changes

2021-09-30 16:15 UTC, wooldridge commented on marklogic-data-hub-central/ui/src/config/tiles.config.ts
> +        toolbarHidden: false
Let's avoid a double negative and do:
```
toolbar: true (or false for the Details case)
```

2021-09-30 16:15 UTC, wooldridge commented on marklogic-data-hub-central/ui/src/config/tiles.config.ts
> +        title: 'Explore - Details',
I think this PR should cover an implementation detail (we're handling the Details view as a separate tile definition) and not how content is presented in the UI. There's no problem with the current titles/organization and changing tile titles (if we wanted to do that) is a bigger question that should involve PM and UX. So let's keep this title as "Explore".

2021-09-30 16:15 UTC, wooldridge commented on marklogic-data-hub-central/ui/src/config/tiles.config.ts
> +        intro: 'Detail record view',
I don't see this actually displayed for Details so let's keep the intro value empty, "", to avoid confusion?

2021-09-30 16:38 UTC, wooldridge approved these changes
Looks good to me!

2021-09-30 19:39 UTC, xnikhil08 submitted a review, later dismissed

2021-10-01 17:01 UTC, SameeraPriyathamTadikonda commented
Missing ":" in the PR-title.

2021-10-04 16:37 UTC, AkshayBajajML commented
@awanczowski I see some of the e2e tests failing consistently.

2021-10-05 16:44 UTC, wooldridge approved these changes

2021-10-05 17:47 UTC, briantang approved these changes

2021-10-05 17:57 UTC, merged