DHFPROD-7905: Persisting graph config data using new endpoint
marklogic/marklogic-data-hub pull request #6147
Opened 2021-09-28 21:14 UTC by xnikhil08

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-09-28 22:11 UTC, wooldridge requested changes
When I edit the node color with the side panel open, I don't see an immediate change in the node color. It then changes when I close the side panel:

https://watch.screencastify.com/v/lJFF3pfE7g3rRkHY3SVP

Observations while creating and then deleting an entity:

When I create a new entity, there is a draft version of that entity created but I can move away from the modeling with without a warning. When I return to the modeling view there is a warning. (Also, should entity creation require a publish step?)

When I delete an entity, I get what appears to be a modeling update. (A spinner on the button.) But the result is a new draft entity in the database for that deleted entity. Then I have to Publish to finish deleting. Is that expected? Shouldn't a deletion just delete everything for that entity and not require and additional publish step?

Screencast: https://watch.screencastify.com/v/Tmh4tbGt0RBnhIXQHJmO

2021-09-29 04:21 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/api/modeling.ts
> +export const hubCentralConfig = async () => {
Done.

2021-09-29 04:21 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/modeling/entity-type-modal/entity-type-modal.tsx
> +  const UpdateHubCentralConfig = async (entityName, color) => {
Done.

2021-09-29 04:22 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx
> +          hubCentralConfig={hubCentralConfig}
Here **hubCentralConfig** is an object containing the configuration, not the function to get the object.

2021-09-29 04:23 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/modeling/entity-type-table/entity-type-table.test.tsx
> +          hubCentralConfig={hubCentralConfig}
Same as previous comment. **hubCentralConfig** is not a function here.

2021-09-29 04:26 UTC, xnikhil08 commented
> When I edit the node color with the side panel open, I don't see an immediate change in the node color. It then changes when I close the side panel:
> 
> https://watch.screencastify.com/v/lJFF3pfE7g3rRkHY3SVP
> 
> Observations while creating and then deleting an entity:
> 
> When I create a new entity, there is a draft version of that entity created but I can move away from the modeling with without a warning. When I return to the modeling view there is a warning. (Also, should entity creation require a publish step?)
> 
> When I delete an entity, I get what appears to be a modeling update. (A spinner on the button.) But the result is a new draft entity in the database for that deleted entity. Then I have to Publish to finish deleting. Is that expected? Shouldn't a deletion just delete everything for that entity and not require and additional publish step?
> 
> Screencast: https://watch.screencastify.com/v/Tmh4tbGt0RBnhIXQHJmO

@wooldridge - Fixed the issue where Alert was not visible on new entity creation. Also, regarding queries related to the creation and deletion of entities; It is designed this way to avoid having any modifications in the model, reach other tiles in HC. We can revisit this behavior if needed later or perhaps based on user feedback.

2021-09-30 00:09 UTC, briantang submitted a review, later dismissed
Functionality looks good to me with the relocation of graph config. Color and node positioning changes no longer trigger the alert but are persisted.

2021-09-30 00:19 UTC, briantang submitted a review, later dismissed

2021-09-30 00:45 UTC, wooldridge requested changes
I'm seeing config values for an entity accumulate in the config file even when the associated entity has been deleted. As a result, if I create an entity, delete it, and then create it again, the second new version gets properties of the first version (e.g., color): 
https://watch.screencastify.com/v/sAIjUolUHC5opDaapbBM

I would think removing entity objects from the config file upon entity deletion would fix this. But I'm not sure if this is supported by the endpoint! Can we ignore this edge case for now? Or can we remove the entity object from the config object in the UI code and resave?

2021-09-30 18:37 UTC, xnikhil08 commented
> https://watch.screencastify.com/v/sAIjUolUHC5opDaapbBM

@wooldridge - This seems like a reasonable request. I hav e created a separate ticket to handle deletion of hubCentral config for an entity type while deleting the entity type (https://project.marklogic.com/jira/browse/DHFPROD-7956).
@ryanjdew - Just FYI

2021-09-30 19:14 UTC, briantang submitted a review, later dismissed

2021-09-30 21:16 UTC, wooldridge requested changes
Seeing an error in the UI display upon trying to create a new entity:

https://watch.screencastify.com/v/CnTWli42BHiZJVWY0PsL

Complaining about draft-entity-model-validate-trigger.xqy. :-(

2021-09-30 21:37 UTC, xnikhil08 commented
> draft-entity-model-validate-trigger.xqy

@wooldridge - Looks like the file draft-entity-model-validate-trigger.xqy is missing in your database. Try redeploying the project after publishing the branch changes to local maven..

2021-09-30 21:58 UTC, wooldridge approved these changes

2021-09-30 21:59 UTC, briantang approved these changes

2021-10-01 00:37 UTC, briantang approved these changes

2021-10-01 01:24 UTC, AkshayBajajML approved these changes

2021-10-01 16:48 UTC, merged