DHFPROD-7857: Windows icons replacement
marklogic/marklogic-data-hub pull request #6148
Opened 2021-09-29 14:28 UTC by federicoRufrancosMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-09-29 20:59 UTC, iveyMarklogic approved these changes

2021-09-29 21:38 UTC, wooldridge requested changes

2021-09-29 21:38 UTC, wooldridge commented on marklogic-data-hub-central/ui/src/components/login-form/login-form.tsx
> +              prefix={<Person className={styles.usernameIcon} />}
In login-form.module.scss, let's adjust the CSS for these icons:
```
  .usernameIcon, .passwordIcon {
    color: rgba(0,0,0,.25);
    margin-left: -2px;
  }

  .usernameIcon {
    font-size: 17px;
  }

  .passwordIcon {
    font-size: 15px;
  }
```
Also, remove the CSS for .hostIcon (two places) as that is no longer used.

2021-10-01 21:37 UTC, wooldridge approved these changes
Icons look good!

2021-10-01 21:46 UTC, AkshayBajajML approved these changes

2021-10-04 16:21 UTC, briantang approved these changes

2021-10-04 16:37 UTC, AkshayBajajML approved these changes

2021-10-04 17:14 UTC, merged