DHFPROD-7778: Component Replacement: Dropdown
marklogic/marklogic-data-hub pull request #6153
Opened 2021-09-30 15:44 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-09-30 19:30 UTC, federicoRufrancosMarklogic requested changes

2021-09-30 19:30 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/load/load-list.tsx
> +import {Dropdown as DropdownB} from "react-bootstrap";
Is there any reason why rename it?

2021-09-30 19:30 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.module.scss
> +   text-align: end;
check indentation

2021-09-30 19:30 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
> +
remove this extra line, just to avoid extra error on rebasing

2021-10-01 12:25 UTC, federicoRufrancosMarklogic submitted a review, later dismissed

2021-10-04 12:40 UTC, mrodrigu-marklogic requested changes

2021-10-04 12:40 UTC, mrodrigu-marklogic commented on marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
> +          onToggle={(show) => {
Does this event need to have an empty listener or could we remove it?

2021-10-04 12:40 UTC, mrodrigu-marklogic commented on marklogic-data-hub-central/ui/src/components/entities/mapping/mapping-step-detail/mapping-step-detail.test.tsx
> +    mockGetUris.mockResolvedValue({status: 200, data: ["/dummy/uri/person-101.json"]});+-
Please remove this `+-` at the end of the line (probably a git conflict marker)

2021-10-04 12:40 UTC, mrodrigu-marklogic commented on marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.tsx
> +    if (key ==="singlePropertyRuleset") {
I'm not sure why the `lint` task didn't catch these, but please add a space between `=== "`

2021-10-04 16:31 UTC, briantang requested changes
@iveyMarklogic this looks pretty good. One small thing, the dropdown menu in load-list.tsx is not being closed when blurred out. All the other dropdowns are fine though.

https://watch.screencastify.com/v/eVGPkmkWsMD6Wyb3P7Wo

2021-10-04 16:59 UTC, iveyMarklogic commented
@briantang  Can you check again?. I fixed that behavior in the last update

2021-10-04 17:35 UTC, briantang approved these changes
Looks good now!

2021-10-04 17:37 UTC, briantang commented
@iveyMarklogic Looks like this will need a conflict resolution again. I can re-approve after that.

2021-10-04 22:54 UTC, briantang approved these changes

2021-10-05 13:37 UTC, mrodrigu-marklogic approved these changes
QA review looks good as well

2021-10-05 14:52 UTC, aniamy approved these changes

2021-10-05 14:55 UTC, merged