DHFPROD-7945: input-group-4
marklogic/marklogic-data-hub pull request #6249
Opened 2021-10-29 17:39 UTC by MSBrignoni

### Description
Input Group 4

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests

2021-11-03 20:52 UTC, iveyMarklogic submitted a review, later dismissed

2021-11-04 18:28 UTC, briantang approved these changes
There is misalignment with the placeholder text but since one of them is the Cascader coming later, we can fix it in the Cascader.

<img width="681" alt="Screen Shot 2021-11-04 at 11 20 41 AM" src="https://user-images.githubusercontent.com/18374593/140398504-a2002bc3-459b-4732-9378-cf0a776e7230.png">

2021-11-05 19:26 UTC, iveyMarklogic approved these changes

2021-11-05 19:28 UTC, briantang approved these changes

2021-11-05 20:25 UTC, briantang requested changes
@MSBrignoni There is a bug here causing the cypress failure. The new property modal is not cleared after it has been submitted once.

https://watch.screencastify.com/v/Tqc0rS6k1moJEysPXg1Q

2021-11-08 17:53 UTC, MSBrignoni commented
> 
> 
> @MSBrignoni There is a bug here causing the cypress failure. The new property modal is not cleared after it has been submitted once.
> 
> https://watch.screencastify.com/v/Tqc0rS6k1moJEysPXg1Q

Fixed Brian.

2021-11-08 19:02 UTC, iveyMarklogic approved these changes

2021-11-08 19:07 UTC, briantang approved these changes

2021-11-08 19:15 UTC, merged