DHFPROD-7993: Color of nodes doesn't change in relationship modal
marklogic/marklogic-data-hub pull request #6254
Opened 2021-11-03 16:39 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-11-05 17:39 UTC, AkshayBajajML submitted a review, later dismissed
Looks Good!

2021-11-08 19:54 UTC, wooldridge requested changes
Worked fine on my first test of creating a relationship (I saw the color appearing in the dialog), but when I tried a second time in graph view, I got the following error when trying to create a relationship: 

https://watch.screencastify.com/v/xS91dXBn6lO9SBK8s8Ua

```
TypeError: Cannot read properties of undefined (reading 'properties')
initRelationship
src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx:87
  84 | setTargetEntityColor(props.relationshipInfo.targetNodeColor);
  85 | setOneToManySelected(false);
  86 | 
> 87 | if (sourceEntityDetails.model.definitions[props.relationshipInfo.sourceNodeName].properties[props.relationshipInfo.relationshipName]?.hasOwnProperty("items")) {
     | ^  88 |   //set cardinality selection to "multiple"
  89 |   setOneToManySelected(true);
  90 | }
View compiled
```

2021-11-08 20:10 UTC, briantang commented
Thanks @wooldridge. Fixed.

2021-11-08 21:51 UTC, wooldridge approved these changes

2021-11-08 22:42 UTC, AkshayBajajML approved these changes

2021-11-09 01:06 UTC, merged