DHFPROD-8092: Add None option to foreign key dropdowns
marklogic/marklogic-data-hub pull request #6278
Opened 2021-11-12 20:28 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-11-15 17:43 UTC, AkshayBajajML requested changes
Overall Looks Good.
Just minor issue with tooltip flickering when none is selected in dropdown.
Screencast: https://drive.google.com/file/d/1SuHp7RpuojAB8IYKhLFR-gJATwifOJCq/view?usp=sharing

2021-11-16 03:07 UTC, briantang commented
> Overall Looks Good. Just minor issue with tooltip flickering when none is selected in dropdown. Screencast: https://drive.google.com/file/d/1SuHp7RpuojAB8IYKhLFR-gJATwifOJCq/view?usp=sharing

Thanks @AkshayBajajML , this seems to be an issue that is on develop due to the HC tooltip component. Should be fixed separately.

2021-11-16 17:28 UTC, AkshayBajajML approved these changes

2021-11-16 21:38 UTC, Sanjeevani19 approved these changes

2021-11-17 07:37 UTC, merged