DHFPROD-7834-Typography
marklogic/marklogic-data-hub pull request #6280
Opened 2021-11-15 18:54 UTC by lucianaabc-ml

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-11-16 14:17 UTC, iveyMarklogic requested changes

2021-11-16 14:17 UTC, iveyMarklogic commented on marklogic-data-hub-central/ui/src/components/detail-header/detail-header.module.scss
> +  color: #777777
@lucianaabc-ml This color must be imported from the theme variables

2021-11-17 14:50 UTC, mrodrigu-marklogic submitted a review, later dismissed

2021-11-18 15:03 UTC, yubiselmarklogic submitted a review, later dismissed

2021-11-18 17:17 UTC, briantang approved these changes
Looks good

2021-11-18 18:01 UTC, yubiselmarklogic approved these changes

2021-11-18 19:45 UTC, merged