DHFPROD-7870: Changes to Explorer main left side panel
marklogic/marklogic-data-hub pull request #6283
Opened 2021-11-16 18:25 UTC by federicoRufrancosMarklogic

### Description
implementing related entities
creating new options
add three state checkbox group
fix lint
adding ui tests

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [X] Added Tests
- [X] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-11-18 16:52 UTC, Sanjeevani19 requested changes
@federicoRufrancosMarklogic Sidebar looks good and matches the design, there are a few changes which need to be addressed
- I see that SORT entities code is repeated in 2 files, please create a common function for both of those files under marklogic-data-hub-central/ui/src/util  
- Also there is a query related e2e test failure 
https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6283/8/tests/

2021-11-19 17:44 UTC, Sanjeevani19 reviewed
@federicoRufrancosMarklogic util function looks good, But the e2e test related to queries is still failing https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6283/13/tests/, Could you please look into that  ?

2021-11-22 17:41 UTC, Sanjeevani19 approved these changes

2021-11-22 18:27 UTC, briantang approved these changes

2021-11-24 18:04 UTC, Sanjeevani19 approved these changes

2021-11-24 18:31 UTC, briantang approved these changes

2021-11-24 21:13 UTC, merged