DHFPROD-8093: Alignment-issues
marklogic/marklogic-data-hub pull request #6307
Opened 2021-11-24 18:57 UTC by lucianaabc-ml

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-11-25 19:48 UTC, federicoRufrancosMarklogic requested changes

2021-11-25 19:48 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.module.scss
> +
remove this extra white space

2021-11-25 19:48 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
> +        }
adjust indentation

2021-11-25 19:48 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/modeling/graph-view/side-panel/side-panel.module.scss
> +
remove extra spaces

2021-11-25 19:48 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/steps/steps.module.scss
> +
white spaces

2021-11-25 21:29 UTC, mrodrigu-marklogic approved these changes

2021-11-26 17:29 UTC, iveyMarklogic approved these changes

2021-11-26 17:31 UTC, federicoRufrancosMarklogic approved these changes

2021-11-26 17:38 UTC, merged