DHFPROD-7830: popover
marklogic/marklogic-data-hub pull request #6316
Opened 2021-11-25 20:53 UTC by MSBrignoni

### Description

Bootstrap Popover

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-11-29 18:46 UTC, briantang requested changes
@MSBrignoni Looks like there is a popover related e2e failure. Can we also fix the commit message to have a colon after the ticket number? Should be "DHFPROD-7830: Popover"

<img width="1678" alt="Screen Shot 2021-11-29 at 10 44 27 AM" src="https://user-images.githubusercontent.com/18374593/143925064-a465d292-382d-49f9-84cf-04b8d00d168b.png">

2021-11-29 20:48 UTC, MSBrignoni commented
> @MSBrignoni Looks like there is a popover related e2e failure. Can we also fix the commit message to have a colon after the ticket number? Should be "DHFPROD-7830: Popover"
> 
> <img alt="Screen Shot 2021-11-29 at 10 44 27 AM" width="1678" src="https://user-images.githubusercontent.com/18374593/143925064-a465d292-382d-49f9-84cf-04b8d00d168b.png">

Thank you Brian, done. Yes, i was fixing this in the "Authorization.spec".

2021-11-30 08:43 UTC, briantang requested changes
@MSBrignoni Looks good, but found a couple places where I think the popover needs to persist, but it destroys too early. In the video, we need to be able to click inside the popover, so the popover should not close until we blur out of the popover.
(1 in create-edit-step.tsx, 2 in entity-map-table.tsx (the stacked icons))

https://watch.screencastify.com/v/zW9F1mlEj8NbJyxLs7Eq

2021-11-30 14:27 UTC, MSBrignoni commented
> @MSBrignoni Looks good, but found a couple places where I think the popover needs to persist, but it destroys too early. In the video, we need to be able to click inside the popover, so the popover should not close until we blur out of the popover. (1 in create-edit-step.tsx, 2 in entity-map-table.tsx (the stacked icons))
> 
> https://watch.screencastify.com/v/zW9F1mlEj8NbJyxLs7Eq

Yes, i see @briantang, thank you. What i did is, give it a delay of 2 seconds in the popover wich need interaction (only when it needs to hide), because this element of bootstrap doesn't controll the events like ant with the hover.

2021-11-30 15:15 UTC, federicoRufrancosMarklogic approved these changes
I left 2 minor comments, anyway it's approved

2021-11-30 15:15 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
> +
here this whitespace has some logic? Or need remove it

2021-11-30 15:15 UTC, federicoRufrancosMarklogic commented on marklogic-data-hub-central/ui/src/components/entities/mapping/entity-map-table/entity-map-table.tsx
> +                <div className={styles.typeContainer} >
extra space to the end of the tag

2021-11-30 20:55 UTC, yubiselmarklogic approved these changes

2021-11-30 21:28 UTC, mrodrigu-marklogic approved these changes

2021-12-01 12:43 UTC, iveyMarklogic approved these changes

2021-12-01 18:32 UTC, briantang approved these changes

2021-12-01 18:33 UTC, merged