Dhfprod 7833 switch
marklogic/marklogic-data-hub pull request #6333
Opened 2021-12-03 20:22 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-12-06 20:34 UTC, yubiselmarklogic approved these changes

2021-12-07 19:29 UTC, AkshayBajajML requested changes
Good work! I have few minor observations:

- Can we change the cursor to pointer when user tries to hover over toggle switch.
- I see the background color for switch to be #394494. Can we update it to #5B69AF to keep it consistent.

2021-12-08 14:37 UTC, iveyMarklogic commented
@AkshayBajajML can you check again. I added fixes for both observations.

2021-12-08 18:08 UTC, AkshayBajajML approved these changes
Looks Good!

2021-12-08 18:42 UTC, yubiselmarklogic submitted a review, later dismissed

2021-12-08 20:51 UTC, Sanjeevani19 submitted a review, later dismissed

2021-12-09 20:08 UTC, briantang approved these changes

2021-12-09 20:10 UTC, AkshayBajajML approved these changes

2021-12-09 20:10 UTC, Sanjeevani19 approved these changes

2021-12-09 20:28 UTC, yubiselmarklogic approved these changes

2021-12-09 21:10 UTC, merged