DHFPROD-7831: Result
marklogic/marklogic-data-hub pull request #6336
Opened 2021-12-06 20:22 UTC by MSBrignoni

### Description
Result

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-12-08 15:29 UTC, yubiselmarklogic commented on marklogic-data-hub-central/ui/src/pages/noMatchRedirect.module.scss
> +    color: #5B69AF;
You should use the theme variables for this colors importing HCVariables.scss

2021-12-08 15:29 UTC, yubiselmarklogic commented on marklogic-data-hub-central/ui/src/pages/noMatchRedirect.tsx
> +          <div className={`d-flex align-items-center cursor-pointer`} style={{float: "right"}}>
Instead of use float: right; it's better approach using justify-content: end; in a flex container.

2021-12-08 15:30 UTC, yubiselmarklogic commented on marklogic-data-hub-central/ui/src/pages/noMatchRedirect.tsx
> +          <div className={`d-flex align-items-center cursor-pointer`} style={{float: "right"}}>
bootstrap class: justify-content-end

2021-12-08 15:53 UTC, yubiselmarklogic approved these changes

2021-12-08 19:16 UTC, AkshayBajajML requested changes
Can we move the _back link_ to left corner of the page as shown on mockup in jira ticket.

<img width="1677" alt="Screen Shot 2021-12-08 at 11 14 25 AM" src="https://user-images.githubusercontent.com/66277536/145269850-cc153939-5e4d-4e9a-bfd1-ec6d4e111577.png">

2021-12-08 19:19 UTC, AkshayBajajML commented
Can we also make back button only clickable.
Right now we can click anywhere on left top and user is routed to back screen.

2021-12-08 20:00 UTC, MSBrignoni commented
> Can we also make back link only clickable. Right now we can click anywhere on left top and user is routed to back screen.

Thank you @AkshayBajajML, done both changes.

2021-12-08 20:16 UTC, AkshayBajajML approved these changes
Looks Good!

2021-12-08 20:40 UTC, yubiselmarklogic approved these changes

2021-12-08 21:14 UTC, AkshayBajajML requested changes
I have few other minor observations:

- Entire page needs scrollbar(Right Now I am not able to scroll the page and error box at all).
- Right padding seems to more than left padding as can be seen below.

<img width="1680" alt="Screen Shot 2021-12-08 at 1 12 27 PM" src="https://user-images.githubusercontent.com/66277536/145285310-23efda2d-3857-4802-b66a-cf8b30fbc999.png">

2021-12-08 22:02 UTC, iveyMarklogic approved these changes

2021-12-09 13:39 UTC, MSBrignoni commented
> I have few other minor observations:
> 
>     * Entire page needs scrollbar(Right Now I am not able to scroll the page and error box at all).
> 
>     * Right padding seems to more than left padding as can be seen below.
> 
> 
> <img alt="Screen Shot 2021-12-08 at 1 12 27 PM" width="1680" src="https://user-images.githubusercontent.com/66277536/145285310-23efda2d-3857-4802-b66a-cf8b30fbc999.png">

Thank you @AkshayBajajML . 

- Regarding the scroll I added the necessary property css. 
- About the padding in the box, I was testing and it depends on the text. If the words cannot be divided, it goes to the next line as its image, when repeated it generates a different distribution, but, using other text, it displays well.
Anyway, I tried the "break-all" property, it distributes better, but breaks all the words (upper image), if we leave it as it is, it remains as the lower image. What do you think?
![text](https://user-images.githubusercontent.com/89084298/145406691-e976e752-0525-470d-94b6-8fcd430be4ed.png)

2021-12-09 17:37 UTC, jbelonoj commented
@MSBrignoni Thanks for checking! We definitely don't want the words to be broken, so my vote is for the bottom image approach. Thanks!

2021-12-09 18:05 UTC, AkshayBajajML commented
Overall looks good!
- Can we make the **marklogic support** link and hover color consistent with privacy link at footer.

2021-12-09 20:24 UTC, MSBrignoni commented
> Overall looks good!
> 
>     * Can we make the **marklogic support** link and hover color consistent with privacy link at footer.

Yes, done!, now it has the same style and effect @AkshayBajajML

2021-12-09 20:25 UTC, Sanjeevani19 approved these changes

2021-12-09 21:07 UTC, AkshayBajajML approved these changes
Looks great! Good work

2021-12-10 12:42 UTC, iveyMarklogic approved these changes

2021-12-10 15:09 UTC, merged