DHFPROD-7672: Avoid repeating search calls on errors
marklogic/marklogic-data-hub pull request #6337
Opened 2021-12-06 20:55 UTC by ryanjdew

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests

2021-12-07 18:25 UTC, briantang approved these changes

2021-12-08 20:49 UTC, Sanjeevani19 requested changes
@ryanjdew Initially I am updating the search controller file to get a run time error, the UI is not making endless search calls which works as per the AC but once I revert the code back to its place there are no search calls being made to get the data back, also I see an error related to cancelToken being undefined, Please look into them, I have sent a video over slack to reproduce this errors.

2021-12-15 15:35 UTC, Sanjeevani19 requested changes
@ryanjdew I still see the cancelToken undefined error, also there are a couple of e2e test failures, please look into them

2021-12-15 20:45 UTC, Sanjeevani19 reviewed
@ryanjdew  Looks like there are merge conflicts, also the e2e are failing in latest build https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6337/24/tests

2021-12-21 14:29 UTC, Sanjeevani19 approved these changes

2021-12-21 17:05 UTC, merged