Dhfprod 7741 treeselect
marklogic/marklogic-data-hub pull request #6346
Opened 2021-12-09 17:43 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-12-09 17:45 UTC, Sanjeevani19 reviewed
@iveyMarklogic Please make sure that the PR title is in correct format.

2021-12-09 17:54 UTC, iveyMarklogic commented
@Sanjeevani19 I think the PR has the correct title format

2021-12-13 03:32 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/support/components/matching/ruleset-single-modal.tsx
> +    cy.get(".rc-tree-select-selector").trigger("mouseover").click();
This is a really great selector improvement!

2021-12-13 12:24 UTC, yubiselmarklogic submitted a review, later dismissed

2021-12-13 16:47 UTC, mrodrigu-marklogic requested changes
There is a slight difference on the container that puts the horizontal scroll bar when you don't have children there, aside from that LGTM 

![image](https://user-images.githubusercontent.com/88854466/145853593-430b5947-7ec3-4401-be62-0b79aded1979.png)

2021-12-13 17:49 UTC, iveyMarklogic commented
@mrodrigu-marklogic can you check again

2021-12-13 19:32 UTC, yubiselmarklogic approved these changes

2021-12-13 20:16 UTC, mrodrigu-marklogic approved these changes

2021-12-14 12:37 UTC, merged