DHFPROD-8177: BE - Modify Graph Settings
marklogic/marklogic-data-hub pull request #6348
Opened 2021-12-10 14:11 UTC by prolonMarkLogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2021-12-10 17:49 UTC, ryanjdew requested changes

2021-12-10 17:49 UTC, ryanjdew commented on marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/ModelController.java
> -                .withPermission("hub-central-entity-model-reader", DocumentMetadataHandle.Capability.UPDATE);
We want to keep the update permission as is.

2021-12-10 19:34 UTC, aniamy approved these changes

2021-12-11 18:57 UTC, ryanjdew approved these changes

2021-12-13 12:54 UTC, merged