DHFPROD-8175:Side Panel Fixes
marklogic/marklogic-data-hub pull request #6358
Opened 2021-12-14 23:46 UTC by Sanjeevani19

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [X] JIRA_ID included in all the commit messages
- [X] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Code passes ESLint tests
- [N/A] Added Tests
- [N/A] Run UI tests

2021-12-15 19:01 UTC, federicoRufrancosMarklogic requested changes
Test changes on browser, they look good, I notice that there is no line between All Entities option. Is this change request discard? 
Code looks good also, made some minor comments
![image](https://user-images.githubusercontent.com/88794866/146248145-baa133ae-ac0b-427b-bce6-f92bdfe2bac5.png)

2021-12-15 19:03 UTC, Sanjeevani19 commented
> Test changes on browser, they look good, I notice that there is no line between All Entities option. Is this change request discard? Code looks good also, made some minor comments ![image](https://user-images.githubusercontent.com/88794866/146248145-baa133ae-ac0b-427b-bce6-f92bdfe2bac5.png)

@federicoRufrancosMarklogic This will be handled as a part of Yubisel select PR, Jamie is aware of that

2021-12-16 16:19 UTC, federicoRufrancosMarklogic approved these changes

2021-12-17 17:59 UTC, xnikhil08 approved these changes

2021-12-17 20:02 UTC, merged