DHFPROD-7934: Navigate to Graph Settings
marklogic/marklogic-data-hub pull request #6402
Opened 2022-01-04 17:02 UTC by xnikhil08

### Description
Just a dummy graph settings modal UI. Saving the modal will come in future stories.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2022-01-05 13:21 UTC, federicoRufrancosMarklogic requested changes
Code looks good, I found some comment out code, are they necessary?

On testing functionality I don't see filter over Entity Type. Here is an screenshot
![image](https://user-images.githubusercontent.com/88794866/148223375-a0fa987a-aedd-443f-a2b9-fe7b6d0fb9cf.png)

And here is how it looks on UX doc:
![image](https://user-images.githubusercontent.com/88794866/148223740-7016c767-a09c-4805-bd61-70fdbe022a5b.png)

Is color selection part of this story? Because I don't see anything detailed on the story. Probably is part of another task

2022-01-05 17:58 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/e2e/cypress/support/pages/browse.tsx
> +  // getManageQueriesButton() {
Filter, color and Icon have their own separate stories. Not in scope here.

2022-01-06 22:45 UTC, Sanjeevani19 reviewed
@xnikhil08 Functionality looks good !!

-  Still see some commented code, Is there a reason for not removing them from the code base ?

- Also there is one new e2e intermittent failure related to manage queries modal which is happening only on this PR, I see it on runs 6 and 8, Please look into fixing it

 **verify manage queries modal visibility and removing query scenario on the detail page**

2022-01-07 08:02 UTC, xnikhil08 commented
> @xnikhil08 Functionality looks good !!
> 
> * Still see some commented code, Is there a reason for not removing them from the code base ?
> * Also there is one new e2e intermittent failure related to manage queries modal which is happening only on this PR, I see it on runs 6 and 8, Please look into fixing it
> 
> **verify manage queries modal visibility and removing query scenario on the detail page**

@Sanjeevani19 - Fixed the failing test. Another review ?

2022-01-07 12:30 UTC, federicoRufrancosMarklogic commented
* Entity types should be listed in alphabetical order by default
* On the story said: "There's a filter for entity types and the ability to sort entity types", so should we remove "filter for entity types"? as you mention is part of different story
* Entity types header should be aligned with column content
![image](https://user-images.githubusercontent.com/88794866/148544312-c1d9d6be-9c61-4ada-ac04-0eb1de44f59d.png)
* Header column font should be stronger

2022-01-11 04:49 UTC, xnikhil08 commented
Closing it for now, since it has been de-prioritized in the 5.7.

2022-01-11 04:49 UTC, closed without merging