DHFPROD-8193: TABLE-Structured property should expand
marklogic/marklogic-data-hub pull request #6413
Opened 2022-01-10 18:43 UTC by MSBrignoni

### Description
Bug: TABLE-Structured property should expand when property is added and delete

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests

2022-01-10 19:16 UTC, MSBrignoni commented
This line was causing the problems related to the nested table in specific cases, altering the key of the row and affecting that later the library could not handle the default expand when adding and deleting.

![image](https://user-images.githubusercontent.com/89084298/148825393-7b696710-9841-4298-a225-3284f5a8f8f2.png)

2022-01-11 17:54 UTC, briantang requested changes
I think I see two tricky cases where the behavior is unexpected @MSBrignoni.

https://watch.screencastify.com/v/RctKJ4vM6FfWbKDS1Jjy

2022-01-12 13:52 UTC, MSBrignoni commented
> I think I see two tricky cases where the behavior is unexpected @MSBrignoni.
> 
> https://watch.screencastify.com/v/RctKJ4vM6FfWbKDS1Jjy

Good catch @briantang , i was looking the code and testing it, and it is coming from the [old ant table too](http://rh7v-10-dhe-2:8080/tiles/model), although the code has improved as ant, there are different inconsistencies in the "property-table.tsx". It seems to work good with shipping but not with others cases, example, if I create a new property in "billing", it expands "shipping" (and others situations), i think it is necessary restructure parts of this page, perhaps in another jira issue.

https://user-images.githubusercontent.com/89084298/149152484-293374d2-21ca-42ff-8bc6-1f6257153833.mp4

2022-01-13 22:09 UTC, briantang approved these changes

2022-01-13 22:53 UTC, aniamy approved these changes

2022-01-14 01:59 UTC, merged