DHFPROD 8269: Use proper endpoints, instead of mock data, for the entity specific data in the side-bar in explore screen
marklogic/marklogic-data-hub pull request #6455
Opened 2022-01-25 20:51 UTC by aniamy

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- N/A Added Release Notes

2022-01-27 05:49 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/pages/Browse.test.tsx
> +  const modelsResponse = [
Looks like we are already storing mock entity model responses and sample hub central config responses in few files under `src/assets/mock-data/modeling/modeling.js`  and `src/assets/mock-data/explore/model-response.js`.
Can we place this mock data as well at one of those appropriate places and refer them here, as needed. ?

2022-01-27 05:53 UTC, xnikhil08 requested changes
Looks good. Just mentioned few suggestions about moving the mock data under src/assets, to follow the UI standards.

2022-01-27 05:53 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/pages/Browse.test.tsx
> +  const hubConfigResponse = {"modeling": {"entities": {"Customer": {"graphX": 16, "graphY": 54, "color": "#e3deeb", "icon": "FaOdnoklassniki"}}}};
This also can be moved under `src/assets`, like mentioned in the previous comment.

2022-01-27 06:38 UTC, briantang commented
Thanks @xnikhil08, I was giving out a hand in that department and somehow left behind some remnants there. Refactored into a common area now.

2022-01-27 20:25 UTC, xnikhil08 approved these changes

2022-01-27 20:32 UTC, Sanjeevani19 reviewed
@aniamy two UI tests are failing on this PR https://jenkins.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-6455/11/tests, Please look into it

2022-01-27 21:50 UTC, Sanjeevani19 approved these changes
Looks good, tests passed on latest build

2022-01-27 23:12 UTC, briantang commented
Pushed an e2e fix for the failing entitiesSideBar.spec test. Should pass now.

2022-01-27 23:12 UTC, briantang approved these changes

2022-01-28 04:38 UTC, xnikhil08 approved these changes

2022-01-28 15:31 UTC, Sanjeevani19 approved these changes

2022-01-28 15:33 UTC, merged