DHFPROD-8381: Card View not toggling from Graph View
marklogic/marklogic-data-hub pull request #6458
Opened 2022-01-26 14:21 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [N/A] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added Release Notes

2022-01-26 18:20 UTC, briantang submitted a review, later dismissed
Looks fixed.

2022-01-26 18:56 UTC, Sanjeevani19 submitted a review, later dismissed

2022-01-26 18:57 UTC, Sanjeevani19 reviewed
@iveyMarklogic Can we add an e2e for this scenario ?

2022-01-28 04:41 UTC, xnikhil08 submitted a review, later dismissed

2022-01-28 15:48 UTC, iveyMarklogic commented
@Sanjeevani19 I added e2es to cover those scenarios

2022-01-28 16:07 UTC, aniamy approved these changes

2022-01-28 16:08 UTC, aniamy commented
Toggling now keeps a memory of the previous choice in Entities for all options. Looks good.

2022-01-28 17:41 UTC, briantang submitted a review, later dismissed
Nice @iveyMarklogic looks good!

2022-01-28 18:01 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreViewSelector.tsx
> +    cy.log(`**Go to Explore section?**`);
Do you mind removing the "?" ?

2022-01-28 18:03 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/explore/exploreViewSelector.tsx
> +    toolbar.getMonitorToolbarIcon().click();
You can add a simple validation here simply to confirm that it actually went to monitor section. For example a title

2022-01-28 18:33 UTC, csilva-ml requested changes
Great work on the e2e, just some minor requests on the validations, thank you!

2022-01-28 20:46 UTC, aniamy approved these changes

2022-01-28 22:39 UTC, xnikhil08 approved these changes

2022-01-31 17:24 UTC, merged