DHFPROD-8300: TABLE - Expanded / nested levels indentation and width issues
marklogic/marklogic-data-hub pull request #6473
Opened 2022-02-01 15:24 UTC by yubiselmarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [N/A] Added Release Notes

2022-02-02 08:24 UTC, AkshayBajajML requested changes
Good work!! 
Just minor observation - Delete icons are slightly misaligned
<img width="1553" alt="Screen Shot 2022-02-02 at 12 09 36 AM" src="https://user-images.githubusercontent.com/66277536/152118080-b450d7a0-f82f-4edf-ae99-13c929a224f2.png">

2022-02-02 13:59 UTC, yubiselmarklogic commented
@AkshayBajajML  Working on it

2022-02-02 17:20 UTC, yubiselmarklogic commented
@AkshayBajajML can you check again

2022-02-02 18:19 UTC, AkshayBajajML approved these changes

2022-02-03 19:13 UTC, AkshayBajajML approved these changes

2022-02-04 13:24 UTC, MSBrignoni approved these changes

2022-02-07 17:37 UTC, merged