DHFPROD-8454: Reset to All Entities Hotfix
marklogic/marklogic-data-hub pull request #6488
Opened 2022-02-07 23:40 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- N/A Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added Release Notes

2022-02-07 23:48 UTC, xnikhil08 approved these changes

2022-02-08 00:38 UTC, Sanjeevani19 approved these changes

2022-02-08 02:25 UTC, Sanjeevani19 reviewed
@briantang Around 15 tests are failing on this PR, Please look into it

2022-02-08 03:44 UTC, xnikhil08 approved these changes

2022-02-08 07:15 UTC, briantang commented
A couple e2e specs validating the explore table with faceting need to be skipped and completely overhauled with https://project.marklogic.com/jira/browse/DHFPROD-8455. This is due to a combination of my work + Ivey's entity specific facets, where all the existing faceting is now contained under the entity-specific panels. Many of these tests are still expecting to use the old options.

2022-02-08 09:35 UTC, AkshayBajajML approved these changes
Looks Good!!

2022-02-08 14:08 UTC, Sanjeevani19 requested changes
@briantang Ideally we shouldn't be skipping out all the test suites, I understand that these tests needs to be updated with the new faceting changes. There are two options here:
1. Updating all those test suites and make sure all the tests are running fine
2. Due to time constraint if we need some time to update the tests, then we have to all test those scenarios manually 
@ngodugu-marklogic  Any thoughts ? Both of you please work together to get this going

2022-02-08 16:59 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
> +  it.skip("Explore other collections", () => {   //THIS FAILS UNTIL ENTITY SPECIFIC FACETS PR IS IN (DHFPROD-7950), needs to use entity specific panel facets instead entity properties panel
7950 is already in develop

2022-02-08 17:28 UTC, briantang commented
> @briantang Ideally we shouldn't be skipping out all the test suites, I understand that these tests needs to be updated with the new faceting changes. There are two options here:
> 
> 1. Updating all those test suites and make sure all the tests are running fine
> 2. Due to time constraint if we need some time to update the tests, then we have to all test those scenarios manually
>    @ngodugu-marklogic  Any thoughts ? Both of you please work together to get this going

I think the best approach would be to use manual testing for now. Basically having to rewrite all of the explore faceting will take 1-2 days. We also need to unblock the pipelines for other PRs

2022-02-08 18:44 UTC, aniamy approved these changes

2022-02-08 22:26 UTC, Sanjeevani19 approved these changes

2022-02-08 22:28 UTC, merged