DHFPROD-8415: TooltipWrongCurate
marklogic/marklogic-data-hub pull request #6510
Opened 2022-02-14 18:22 UTC by MSBrignoni

### Description
Tooltip wrong in curate page´s select

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Run UI tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- n/a Added to Release Wiki

2022-02-15 07:19 UTC, briantang requested changes
Looks fixed, but can we make the placement of the tooltip consistent with the Load view? It should show up on "bottom" instead of "top"

2022-02-15 12:49 UTC, MSBrignoni commented
> Looks fixed, but can we make the placement of the tooltip consistent with the Load view? It should show up on "bottom" instead of "top"

Yes, done!

2022-02-15 17:39 UTC, briantang submitted a review, later dismissed
Looks good!

2022-02-15 18:40 UTC, yubiselmarklogic submitted a review, later dismissed

2022-02-16 17:50 UTC, yubiselmarklogic approved these changes

2022-02-16 19:48 UTC, briantang approved these changes

2022-02-16 20:11 UTC, yubiselmarklogic approved these changes

2022-02-17 18:06 UTC, merged