DHFPROD-8462: Issues with saved queries
marklogic/marklogic-data-hub pull request #6539
Opened 2022-02-22 14:38 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-02-22 23:10 UTC, xnikhil08 requested changes
Looks good, but noticed a bug with selecting a query, right after clearing it. See the screencast.
https://watch.screencastify.com/v/eVlyyNV0VfofOYykNEAq

2022-02-23 15:24 UTC, iveyMarklogic commented
@xnikhil08 Can you check again?

2022-02-23 15:40 UTC, aniamy approved these changes

2022-02-23 20:19 UTC, briantang approved these changes
Looks good

2022-02-23 20:29 UTC, xnikhil08 approved these changes

2022-02-23 21:19 UTC, merged