DHFPROD-8504: Widget— Membership
marklogic/marklogic-data-hub pull request #6576
Opened 2022-03-07 20:38 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-03-07 22:39 UTC, wooldridge requested changes
Great job! I'm suggesting changes to make it more configurable and to tighten the height.

2022-03-07 22:39 UTC, wooldridge commented on examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
> +        "iconSize": 35,
Let's add a date configuration here:
```
"dateFormat": "yyyy-MM-dd",
```
Then we can use it with our DateTime component.

2022-03-07 22:39 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.tsx
> +            {membership ? <Check data-testid="success-icon" color="#97e7d7" size={iconSize} /> : <X data-testid="error-icon" color="#a2a2a2" size={iconSize} />}
If you import our DateTime component, you can use it here for formatting:
```
{membership ? <span className="date"><DateTime config={{"format": props.config.dateFormat}}>{membership.ts}</DateTime></span> : <span className="empty date"></span>}
```

2022-03-07 22:39 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.tsx
> +  const iconSize = config.iconSize ? config.iconSize : 30
Allow configuration of item container style:
```
let membershipStyle: any = props.style ? props.style : props.config?.style ? props.config.style : {};
```
Then apply the style in the item DIV:
```
<div key={index} className={classes} style={membershipStyle}>
```

2022-03-07 22:39 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.scss
> +        flex-basis: 140px;
Let's make the default of 12 lists fit. Let's also constrain the item container size so it doesn't get messy:
```
        flex-basis: 8.3%;
        min-width: 110px; 
        max-width: 160px; 
```

2022-03-07 22:39 UTC, wooldridge commented on examples/entity-viewer-v2/entity-viewer-client/src/main/ml-modules/root/explore-data/ui-config/config.json
> +        "iconSize": 35,
Let's tighten the height:
```
"iconSize": 32,
```

2022-03-07 22:39 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/src/components/Membership/Membership.scss
> +            padding: 10px 0px;
Let's tighten the height:
```
padding: 8px 0px;
```

2022-03-07 22:39 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/src/views/Detail.tsx
> +                <Section title="Membership" config={{
Let's tighten the height:
```
                <Section title="Membership" config={{
                  "headerStyle": {
                    "backgroundColor": "transparent"
                  },
                  "mainStyle": {
                    "padding-top": "8px"
                  }
                }}>
```

2022-03-08 14:33 UTC, iveyMarklogic commented
@wooldridge I did all of the changes, Can you check it again?

2022-03-08 20:53 UTC, wooldridge approved these changes
Looks great, thanks!

2022-03-08 20:57 UTC, merged