DHFPRO- 8541: Re-Add Run Flows Success and Error Messages
marklogic/marklogic-data-hub pull request #6585
Opened 2022-03-09 17:19 UTC by lucianaabc-ml

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-03-11 18:21 UTC, briantang requested changes

2022-03-11 18:21 UTC, briantang commented on marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
> +  it("can create flow and add steps to flow, should load xml merged document and display content", {defaultCommandTimeout: 120000}, () => {
There's a line above this that was commented out due to the skipped test. Can we uncomment it?

2022-03-11 18:21 UTC, briantang commented on marklogic-data-hub-central/ui/e2e/cypress/integration/curation/run/runFlow.spec.tsx
> +  it("can create flow and add steps to flow, should load xml merged document and display content", {defaultCommandTimeout: 120000}, () => {
There's a line above this that was commented out due to the skipped test. Can we uncomment it?

2022-03-11 21:02 UTC, briantang approved these changes
Looks good now!

2022-03-11 21:17 UTC, MSBrignoni submitted a review, later dismissed

2022-03-11 22:26 UTC, briantang requested changes
@lucianaabc-ml  There are several UI and e2e failures that all appear to be related. All of these tests still seem to be expecting the old modals when they should be asserting for the new status modal.

2022-03-19 00:21 UTC, briantang commented
@lucianaabc-ml so close! Just two failures left.
1) In runFlows.spec, looks like it's missing a line to actually start running the flow before the modal appears.
2) In mappingWithCustomHeader.spec, it's trying to click a "back button" that isn't there. Maybe the solution is to remove that.

2022-03-21 20:28 UTC, briantang approved these changes

2022-03-22 12:47 UTC, aniamy approved these changes

2022-03-22 12:49 UTC, merged