DHFPROD-8569: Related entity icons still visible in the new entity icons sidebar, for table/snippet views
marklogic/marklogic-data-hub pull request #6625
Opened 2022-03-21 23:35 UTC by xnikhil08

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-03-22 14:29 UTC, aniamy commented
@xnikhil08 Logic looks good. One small style issue.
When the icons are disabled they move a few pixels away from the "main section". See screenshot, in red I tried to show the extra space.
![image](https://user-images.githubusercontent.com/4117902/159505024-8c859445-df3a-4473-bfca-8ed98d4b7da1.png)

2022-03-22 15:25 UTC, aniamy requested changes
See style issue comment

2022-03-23 19:27 UTC, xnikhil08 commented
> See style issue comment

@aniamy - Fixed it. Another review ?

2022-03-24 17:00 UTC, aniamy approved these changes

2022-03-25 21:29 UTC, merged