DHFPROD-8569: Related entity icons still visible in the new entity icons sidebar, for table/snippet view
marklogic/marklogic-data-hub pull request #6626
Opened 2022-03-21 23:40 UTC by xnikhil08

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [N/A] Added to Release Wiki

2022-03-22 17:09 UTC, aniamy requested changes
See comments from the develop PR.

2022-03-23 19:27 UTC, xnikhil08 commented
> See comments from the develop PR.

@aniamy - Its fixed. Another review ?

2022-03-24 17:00 UTC, aniamy submitted a review, later dismissed

2022-03-24 17:13 UTC, yubiselmarklogic approved these changes

2022-03-28 14:01 UTC, yubiselmarklogic approved these changes

2022-03-28 19:06 UTC, MSBrignoni approved these changes

2022-03-29 08:44 UTC, merged