DHFPROD-8614: FlowSettingsMenuEnhancements
marklogic/marklogic-data-hub pull request #6669
Opened 2022-03-29 14:21 UTC by MSBrignoni

### Description
Flow Settings Menu Enhancements.
Same commit [hash](https://github.com/marklogic/marklogic-data-hub/pull/6668/commits/63ddf2733d669a808d7bda34d62fd2c15c197275) with 5.7.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [x] Added to Release Wiki

2022-03-31 07:27 UTC, briantang requested changes
See the 5.7 PR

2022-03-31 18:29 UTC, MSBrignoni commented
> See the 5.7 PR

Fixed too.

2022-04-04 16:24 UTC, lucianaabc-ml approved these changes

2022-04-04 16:53 UTC, briantang approved these changes

2022-04-04 17:08 UTC, merged