DHFPROD-8684: Failures on develop
marklogic/marklogic-data-hub pull request #6670
Opened 2022-03-29 15:53 UTC by briantang

### Description

- Duplicate PR that already merged, but for develop this time.

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- N/A Added to Release Wiki

2022-03-29 17:14 UTC, yubiselmarklogic approved these changes

2022-03-29 23:02 UTC, xnikhil08 submitted a review, later dismissed

2022-03-30 15:13 UTC, yubiselmarklogic submitted a review, later dismissed

2022-03-30 16:42 UTC, ngodugu-marklogic approved these changes

2022-03-30 16:49 UTC, xnikhil08 approved these changes

2022-03-30 17:18 UTC, csilva-ml requested changes

2022-03-30 17:18 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorCustomDatePicker.spec.tsx
> +      //TODO: investigate cypress dom re-render in DHFPROD-8671
are you sure this is the issue? I think we're trying to do twice the same thing. I suggest removing these lines, if there's a case where we need this please let me know

2022-03-30 17:32 UTC, briantang commented
Rebased and pushed!

2022-03-30 17:50 UTC, xnikhil08 submitted a review, later dismissed

2022-03-30 20:38 UTC, csilva-ml submitted a review, later dismissed

2022-03-31 13:19 UTC, iveyMarklogic approved these changes

2022-03-31 13:29 UTC, merged