DHFPROD-8619: Apply Entity Icons to Modeling Graph View
marklogic/marklogic-data-hub pull request #6677
Opened 2022-03-30 16:02 UTC by yubiselmarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [N/A] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-03-30 20:27 UTC, MSBrignoni reviewed
It's working good. Something I note is when you change the color or icon in the entity is not refreshing until you move to the table view.

2022-04-05 13:05 UTC, lucianaabc-ml submitted a review, later dismissed

2022-04-05 14:01 UTC, MSBrignoni approved these changes

2022-04-06 17:33 UTC, lucianaabc-ml approved these changes

2022-04-07 02:31 UTC, xnikhil08 requested changes
Added few comments in the similar PR for develop branch.

2022-04-07 17:16 UTC, xnikhil08 approved these changes

2022-04-07 18:58 UTC, MSBrignoni approved these changes

2022-04-07 19:40 UTC, merged