DHFPROD-8634: E2E tests for validating landing page of Twizzlers
marklogic/marklogic-data-hub pull request #6700
Opened 2022-04-04 20:46 UTC by ngodugu-marklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-04-07 00:10 UTC, wooldridge requested changes
I'm seeing the following:
```
  Running:  landingPage.spec.tsx                                                            (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="37.0890" tests="4" failures="3">
  <testsuite name="Root Suite" timestamp="2022-04-07T00:06:01" tests="0" file="cypress/integration/landingPage.spec.tsx" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Visit Entity Viewer Landing page" timestamp="2022-04-07T00:06:01" tests="4" time="37.0890" failures="3">
    <testcase name="Visit Entity Viewer Landing page Greets with Entity Viewer title" time="0.6050" classname="Greets with Entity Viewer title">
    </testcase>
    <testcase name="Visit Entity Viewer Landing page Validate the Header Menus" time="12.1600" classname="Validate the Header Menus">
      <failure message="Timed out retrying after 12000ms: Expected to find element: `.Menus_menu__1OerK &gt; a`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 12000ms: Expected to find element: `.Menus_menu__1OerK > a`, but never found it.
    at LandingPage../cypress/support/pages/landing.tsx.LandingPage.menuOptions (http://localhost:8080/__cypress/tests?p=cypress/integration/landingPage.spec.tsx:162:19)
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/landingPage.spec.tsx:109:72)]]></failure>
    </testcase>
    <testcase name="Visit Entity Viewer Landing page Validate the Metrics section" time="12.1710" classname="Validate the Metrics section">
      <failure message="Timed out retrying after 12000ms: Expected to find content: &apos;New entities this week&apos; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 12000ms: Expected to find content: 'New entities this week' but never did.
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/landingPage.spec.tsx:127:12)]]></failure>
    </testcase>
    <testcase name="Visit Entity Viewer Landing page Validate the default sections are displayed" time="12.1530" classname="Validate the default sections are displayed">
      <failure message="Timed out retrying after 12000ms: Expected to find content: &apos;New Search&apos; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 12000ms: Expected to find content: 'New Search' but never did.
    at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/landingPage.spec.tsx:133:12)]]></failure>
    </testcase>
  </testsuite>
</testsuites>

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        4                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      3                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  9                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 50 seconds                                                             │
  │ Spec Ran:     landingPage.spec.tsx                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the Header Menus (failed).png                                                       
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the Header Menus (failed) (attempt 2).png                                           
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the Header Menus (failed) (attempt 3).png                                           
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the Metrics section (failed).png                                                    
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the Metrics section (failed) (attempt 2).png                                        
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the Metrics section (failed) (attempt 3).png                                        
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the default sections are displayed (failed).png                                     
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the default sections are displayed (failed) (attempt 2).png                         
  -  /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui-custom     (1280x720)
     /e2e/cypress/screenshots/landingPage.spec.tsx/Visit Entity Viewer Landing page -               
     - Validate the default sections are displayed (failed) (attempt 3).png                         


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-   (10 seconds)
                          hub-central/ui-custom/e2e/cypress/videos/landingPage.spec.t               
                          sx.mp4                                                                    

    Compression progress:  100%

====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  landingPage.spec.tsx                     01:50        4        1        3        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     01:50        4        1        3        -        -  

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! e2e@1.0.0 cy:run: `npm install && cypress run`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the e2e@1.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! [...]

2022-04-07 16:35 UTC, AkshayBajajML commented
I can see same issue as @wooldridge

2022-04-07 18:36 UTC, AkshayBajajML approved these changes
All tests pass for me now.

<img width="933" alt="Screen Shot 2022-04-07 at 11 35 06 AM" src="https://user-images.githubusercontent.com/66277536/162273227-c90f0710-c9c0-4e65-9484-38d4e9ca753c.png">

2022-04-07 20:26 UTC, iveyMarklogic approved these changes

2022-04-08 16:44 UTC, wooldridge approved these changes

2022-04-08 16:44 UTC, merged