DHFPROD-7889: Customize entity icons and change color
marklogic/marklogic-data-hub pull request #6718
Opened 2022-04-08 17:46 UTC by yubiselmarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

2022-04-08 23:37 UTC, xnikhil08 requested changes
Really good work here. Other than the suggestions mentioned within review comments, i noticed few bugs when i am trying to update the color or icons when the entity-specific side panel is opened for any entity and also when i move from Explore to Modeling screen.
See the following screencast for more details.
https://watch.screencastify.com/v/HN8SWvLDukezMWhBCg1v

2022-04-08 23:37 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
> +      let settingsData = exploreSettingsData.map(entityData => Object.assign({}, entityData));
I would avoid iterating over the entire array every time we are changing Icon, color label or propertiesOnHover. 
Perhaps keeping them separately in either one object with structure similar to "hubCentralConfig.modeling.entities" or in separate objects for each column (like we are doing in few other areas in HC might help. That would really help when the database scales up to include more that 100-1500 entities.

2022-04-08 23:37 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
> +      let settingsData = exploreSettingsData.map(entityData => Object.assign({}, entityData));
**For Example**: If you create a separate state object variable (may be "settingsData") to store all metadata, then your logic here can be reduced to something like below.

`let tempSettingData = settingsData;
    let exploreSettingRow = tempSettingData[row.entityType];
    switch (column) {
          case TableColumns.Color:
          exploreSettingRow.color = e.color.hex;
          break;
        case TableColumns.Icon:
          exploreSettingRow.icon = e;
          break;
        case TableColumns.EntityLabel:
          exploreSettingRow.label = e.value;
          break;
        }
        setSettingsData(tempSettingsData);`

And then we can use this "settingsData" object to be refresh table columns and also avoid iterating over the Array in handleSave by doing something like this 
"updatedPayload.modeling.entities = exploreSettingsData"
This is just a high level layout of the approach and of course there would be some other adjustments in the code.

2022-04-08 23:37 UTC, xnikhil08 commented on marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-display-settings-modal.tsx
> +      for (const key in exploreSettingsData) {
See if we can avoid this iteration as well, like i mentioned in another comment above.

2022-04-12 16:18 UTC, yubiselmarklogic commented on marklogic-data-hub-central/ui/src/components/explore/entity-type-display-settings-modal/entity-type-color-picker/entity-type-color-picker.tsx
> +import React, {useState, useEffect, useRef, useCallback} from "react";
Ok. I created a subtask DHFPROD-8758

2022-04-18 16:54 UTC, AkshayBajajML approved these changes
Looks Good!! Above mentioned issue by @xnikhil08 is also addressed.

2022-04-18 18:24 UTC, briantang approved these changes

2022-04-18 19:14 UTC, xnikhil08 approved these changes

2022-04-18 19:22 UTC, merged