DHFPROD-8635: E2E tests to validate search in Twizzlers
marklogic/marklogic-data-hub pull request #6740
Opened 2022-04-13 15:21 UTC by ngodugu-marklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-04-18 17:01 UTC, csilva-ml commented on marklogic-data-hub-central/ui-custom/e2e/cypress/integration/searchValidations.spec.tsx
> +    cy.waitUntil(() => searchPage.resultsList().should("be.visible",{timeout:5000}));
Can we remove the wait untils or are we using it for some reason? We actually don't need them, the should() commands waits already :)

2022-04-18 17:06 UTC, csilva-ml requested changes
Hey it looks awesome, just a few suggestions and if we could not use the waitUntils (we actually have tickets to remove the existing ones)

2022-04-18 21:26 UTC, ngodugu-marklogic commented
> Hey it looks awesome, just a few suggestions and if we could not use the waitUntils (we actually have tickets to remove the existing ones)

Done Fixed them. @csilva-ml PR is ready for review.

2022-04-19 17:58 UTC, csilva-ml approved these changes

2022-04-20 02:02 UTC, wooldridge approved these changes

2022-04-20 02:02 UTC, merged