DHFPORD-7578: Stop a running step/flow from Hub Central
marklogic/marklogic-data-hub pull request #6779
Opened 2022-04-22 15:05 UTC by lucianaabc-ml

DHFPORD-7578: Stop a running step/flow from Hub Central

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-04-22 20:04 UTC, MSBrignoni requested changes
it is going well @lucianaabc-ml:
- To make it consistent with the other tooltip ("Run Flow"), could we show the tooltip at the top?

![image](https://user-images.githubusercontent.com/89084298/164786029-e17bee6d-4bfd-46fe-80d7-5129dfe56f1f.png)

2022-04-25 15:36 UTC, briantang requested changes
<img width="1276" alt="Screen Shot 2022-04-25 at 8 33 22 AM" src="https://user-images.githubusercontent.com/18374593/165122896-0f2f4ce6-e6bd-4d7e-8708-438667302375.png">

It looks like if I run the flow and close the modal, the flow will finish but the "Stop" button is still on the panel.

I also don't see this part of the AC. Was there an issue there?

"When I click to stop a flow,
Then the remaining steps in the flow appear and show "Canceled" with explore links disabled."

2022-04-25 23:24 UTC, briantang requested changes

2022-04-25 23:24 UTC, briantang commented on marklogic-data-hub-central/ui/src/components/flows/flows.tsx
> -      if (singleIngest) {
Looks good now but appears like one of my bugfixes were undone with some conflict resolution here. This previous code is needed to fix the issue with running a single load step.

2022-04-25 23:25 UTC, briantang commented
@lucianaabc-ml Please also update the Wiki with this new functionality: https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.7.2

2022-04-26 00:11 UTC, briantang commented on marklogic-data-hub-central/ui/src/config/tooltips.config.tsx
> +  moveLeft: 'Move left',
Minor thing here but the tooltips here look to be the outdated ones. Please refer to the right column of that section in Matthew's UI Text wiki here: https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.7.1+UI+Content#DataHub5.7.1UIContent-RunFlows

2022-04-26 15:21 UTC, briantang requested changes
We can get the modal to re-render the remaining steps to also show "Canceled" if you add formatExtraData below the formatter. Check below:

formatter: ...,
 formatExtraData: {jobResponse}

2022-04-26 16:39 UTC, briantang approved these changes

2022-04-26 17:26 UTC, MSBrignoni approved these changes

2022-04-26 18:06 UTC, merged