DHFPROD-8846: Install Entity Viewer modules only on EntityViewer build
marklogic/marklogic-data-hub pull request #6836
Opened 2022-05-03 15:48 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit

2022-05-10 15:40 UTC, wooldridge requested changes
I checked out your custom-search branch and ran the following from root: ./gradlew clean build -x test

I see the following error:
```
> Task :marklogic-data-hub-central:installDependencies

> marklogic-data-hub-central@0.1.0 preinstall /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui
> npx npm-force-resolutions

npx: installed 6 in 2.833s

/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/com/cognitect/transit/impl/reader.js:39
        return this.decoder.decode(JSON.parse(str), cache);
                                        ^
SyntaxError: Unexpected token < in JSON at position 213779
    at JSON.parse (<anonymous>)
    at Transit$JSONUnmarshaller.reader.JSONUnmarshaller.unmarshal (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/com/cognitect/transit/impl/reader.js:39:41)
    at Transit$Reader.r [as read] (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/com/cognitect/transit/impl/reader.js:59:37)
    at cognitect.transit/read (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/cognitect/transit.cljs:137:10)
    at npm_force_resolutions$core$read_json (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:25:6)
    at switch__2144__auto__ (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs$core$async$impl$ioc_helpers$run_state_machine (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! marklogic-data-hub-central@0.1.0 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marklogic-data-hub-central@0.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mwooldri/.npm/_logs/2022-05-10T15_34_07_325Z-debug.log

> Task :marklogic-data-hub-central:installDependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':marklogic-data-hub-central:installDependencies'.
> Process 'command '/Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/build/npm/npm-v6.14.10/bin/npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 56s
29 actionable tasks: 18 executed, 11 up-to-date
macpro-5957:marklogic-data-hub mwooldri$ 
```

2022-05-11 19:34 UTC, rahulvudutala commented
> I checked out your custom-search branch and ran the following from root: ./gradlew clean build -x test
> 
> I see the following error:
> 
> ```
> > Task :marklogic-data-hub-central:installDependencies
> 
> > marklogic-data-hub-central@0.1.0 preinstall /Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/ui
> > npx npm-force-resolutions
> 
> npx: installed 6 in 2.833s
> 
> /Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/com/cognitect/transit/impl/reader.js:39
>         return this.decoder.decode(JSON.parse(str), cache);
>                                         ^
> SyntaxError: Unexpected token < in JSON at position 213779
>     at JSON.parse (<anonymous>)
>     at Transit$JSONUnmarshaller.reader.JSONUnmarshaller.unmarshal (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/com/cognitect/transit/impl/reader.js:39:41)
>     at Transit$Reader.r [as read] (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/com/cognitect/transit/impl/reader.js:59:37)
>     at cognitect.transit/read (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/cognitect/transit.cljs:137:10)
>     at npm_force_resolutions$core$read_json (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:25:6)
>     at switch__2144__auto__ (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
>     at /Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
>     at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
>     at cljs.core.async.impl.ioc-helpers/FN-IDX (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
>     at cljs$core$async$impl$ioc_helpers$run_state_machine (/Users/mwooldri/.npm/_npx/71227/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! marklogic-data-hub-central@0.1.0 preinstall: `npx npm-force-resolutions`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the marklogic-data-hub-central@0.1.0 preinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/mwooldri/.npm/_logs/2022-05-10T15_34_07_325Z-debug.log
> 
> > Task :marklogic-data-hub-central:installDependencies FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':marklogic-data-hub-central:installDependencies'.
> > Process 'command '/Users/mwooldri/projects/marklogic-data-hub/marklogic-data-hub-central/build/npm/npm-v6.14.10/bin/npm'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 5m 56s
> 29 actionable tasks: 18 executed, 11 up-to-date
> macpro-5957:marklogic-data-hub mwooldri$ 
> ```

@wooldridge There is an issue in the ui/package-lock.json file on line 4706. Looks like we are carrying this from a long time. The branch should work once the package-lock.json is fixed. Can you please look into it once?

2022-05-17 18:12 UTC, rahulvudutala commented
@wooldridge Pushed some changes. Both HC and EV are working as expected. You can test it now

2022-05-19 00:01 UTC, wooldridge approved these changes

2022-05-19 00:02 UTC, merged