DHFPROD-8805: Step Status Faceting on Monitoring Table
marklogic/marklogic-data-hub pull request #6848
Opened 2022-05-05 23:41 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-05-06 15:28 UTC, prolonMarkLogic requested changes
Hello @briantang ,  I found one case, when I ran a flow, and as result, I have steps finished and another in error, if I select both on the facets, and apply. it starts in an internal loop.
If you need more information I have a video about it. just ask to me

2022-05-06 23:55 UTC, briantang commented
Thanks @prolonMarkLogic . Need to update the condition to handle multiple values. Should be fixed now.

2022-05-09 16:48 UTC, ryanjdew approved these changes

2022-05-09 17:05 UTC, ryanjdew requested changes

2022-05-09 17:05 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/flow/job-query-lib.sjs
> +    xdmp.log("WHERE: " + whereClause);
This log statement needs to be cleaned up. It may be worth converting to a trace statement.

2022-05-09 17:13 UTC, ryanjdew approved these changes

2022-05-09 17:50 UTC, prolonMarkLogic approved these changes

2022-05-10 19:17 UTC, briantang commented
Tests passed, just needs reviews.

2022-05-10 19:21 UTC, prolonMarkLogic approved these changes

2022-05-10 20:10 UTC, yubiselmarklogic approved these changes

2022-05-11 02:33 UTC, merged