DHFPROD-8808: Retain state: Modeling Table View
marklogic/marklogic-data-hub pull request #6852
Opened 2022-05-06 16:47 UTC by lucianaabc-ml

DHFPROD-8808: Retain state: Modeling Table View

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-05-06 18:40 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
> +  it("should be the same as the array", () => {
Do you mind changing the description to something like "Validate that the table records on shown in the UI are sorted"

2022-05-06 18:41 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
> +  it("should be the same as the array", () => {
same here for the description

2022-05-06 18:43 UTC, csilva-ml requested changes
Great work Luciana!
I have a couple suggestions for the e2e tests, on the first **it** grab all the data (both for the asc and the desc) and on a second it do all the validations (instead of having 4 tests).
I also added minor comments about the **it** descriptions so that they are easier to understand in the future :)

2022-05-09 08:01 UTC, briantang approved these changes

2022-05-09 13:48 UTC, MSBrignoni approved these changes

2022-05-09 14:51 UTC, merged