DHFPROD-8824: Document the Twizzlers API in Swagger
marklogic/marklogic-data-hub pull request #6885
Opened 2022-05-16 15:41 UTC by AkshayBajajML

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-05-20 12:47 UTC, iveyMarklogic approved these changes

2022-06-06 19:35 UTC, wooldridge requested changes
@AkshayBajajML, this looks great. I added comments to generally address the following:

- For summaries, make wording consistent (e.g., "Returns...").
- Fix some of the params and payloads.
- Remove some config info that isn't used/needed.

2022-06-06 19:35 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/openapi/openapi-spec.yaml
> +          description: "Response Ok"
The response for /api/explore/getEntityModels looks like this:
```
{
  "entityTypeNames": [
    "person",
    "organization"
  ]
}
```

2022-06-06 19:35 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/openapi/openapi-spec.yaml
> +      - name: "mertics"
Fix typo: "metrics"

2022-06-06 19:35 UTC, wooldridge commented on marklogic-data-hub-central/ui-custom/openapi/openapi-spec.yaml
> +  title: "Twizzlers API Documentation"
Let's title it: "Entity Viewer API Documentation"

2022-06-08 23:09 UTC, AkshayBajajML commented
@wooldridge Thanks for reviewing it. I have made all of the mentioned changes and PR is ready to be reviewed. 
Let me know if there are any additional changes required.

2022-06-13 21:08 UTC, wooldridge commented
The getEntityModels spec looks like this:
<img width="816" alt="Screen Shot 2022-06-13 at 2 04 19 PM" src="https://user-images.githubusercontent.com/477757/173445575-21ec417c-a00d-4e24-85b7-0fb808c5a9f0.png">
The property name should be "entityTypeNames", here is the response:
```
{
  "entityTypeNames": [
    "person",
    "organization"
  ]
}
```

2022-06-13 23:21 UTC, wooldridge approved these changes
Looks good!!!

2022-06-13 23:21 UTC, merged