DHFPROD-7180: RetainStateMapMatchMergeInCurate
marklogic/marklogic-data-hub pull request #6886
Opened 2022-05-16 17:24 UTC by MSBrignoni

### Description
Retain State Map Match Merge In Curate View

#### Checklist: 
```diff
- Note: do not change the below
```

-  ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-05-17 05:18 UTC, briantang requested changes
I think the entity-tiles component may be missing some kind of state information when we leave and return to the Curate tile. I get an error white screen after I create a step.

1) Expand several different entity panels in the Curate tile
2) Visit a different tile and come back
3) The panel states are correct, but when I try creating a new step in one of the panels, there is an error page.

2022-05-17 15:03 UTC, MSBrignoni commented
> I think the entity-tiles component may be missing some kind of state information when we leave and return to the Curate tile. I get an error white screen after I create a step.
> 
>     1. Expand several different entity panels in the Curate tile
> 
>     2. Visit a different tile and come back
> 
>     3. The panel states are correct, but when I try creating a new step in one of the panels, there is an error page.

Thanks @briantang! fixed.

2022-05-17 16:20 UTC, briantang commented on marklogic-data-hub-central/ui/e2e/cypress/integration/persistence/persistence.spec.tsx
> +    loadPage.getAccordionButton(0).click();
Looks fixed now. One more thing, I'm not sure if "loadPage" is the proper page to put these actions in. I think the one we want to use here may be "curatePage' just to be organized.

2022-05-17 17:43 UTC, briantang approved these changes

2022-05-17 20:06 UTC, briantang approved these changes

2022-05-18 13:14 UTC, yubiselmarklogic approved these changes

2022-05-18 14:26 UTC, merged