DHFPROD-8607: Add Entity Type Display Settings to Model screen
marklogic/marklogic-data-hub pull request #6915
Opened 2022-05-25 20:13 UTC by yubiselmarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-05-26 22:01 UTC, xnikhil08 requested changes
Looks good.
Just one small change. The Display Settings label seems to be bigger than even the Entity type title in the side panel. Let's make its font size similar to tab labels "Properties" and "Entity Type".

![image](https://user-images.githubusercontent.com/19846034/170586962-81709823-111e-4ee1-bde4-de7543d430a4.png)

2022-05-27 13:50 UTC, yubiselmarklogic commented
@xnikhil08 Fixed

2022-05-27 16:59 UTC, xnikhil08 approved these changes

2022-05-27 18:26 UTC, MSBrignoni approved these changes

2022-05-27 18:34 UTC, merged