DHFPROD-8899: Error handling: async calls
marklogic/marklogic-data-hub pull request #6919
Opened 2022-05-30 18:05 UTC by lucianaabc-ml

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-06-03 17:40 UTC, MSBrignoni requested changes
Looks good, but, sometimes is happening in Chrome, and almost always in FF, after logout, the system is redirecting to the error page too.

2022-06-03 19:42 UTC, MSBrignoni approved these changes

2022-06-06 17:04 UTC, MSBrignoni approved these changes

2022-06-06 20:21 UTC, yubiselmarklogic approved these changes

2022-06-06 22:37 UTC, merged