DHFPROD-9035: Export to CSV for All Entities
marklogic/marklogic-data-hub pull request #6992
Opened 2022-06-24 20:49 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-06-24 22:15 UTC, ryanjdew approved these changes

2022-06-24 22:40 UTC, briantang requested changes
Looks good but I see an 500 Internal Server error if they choose to export all rows where the "limit" argument is left empty. This works for single entities though.

2022-06-27 16:56 UTC, ryanjdew approved these changes

2022-06-27 17:11 UTC, briantang approved these changes
This looks great now, thanks @rahulvudutala

2022-06-27 18:21 UTC, merged