DHFPROD-7921: Provide warning for property rowId
marklogic/marklogic-data-hub pull request #7040
Opened 2022-07-13 18:20 UTC by lucianaabc-ml

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

2022-07-14 08:09 UTC, briantang commented
@lucianaabc-ml  This looks great! Will you be added a relevant e2e test for this?

2022-07-14 12:50 UTC, lucianaabc-ml commented
> @lucianaabc-ml This looks great! Will you be added a relevant e2e test for this?

Yes! Currently working on that

2022-07-14 16:46 UTC, briantang approved these changes
Functionality and coverage looks good. Please update the wiki here: https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.8.0

2022-07-14 16:56 UTC, lucianaabc-ml commented
> Functionality and coverage looks good. Please update the wiki here: https://wiki.marklogic.com/display/ENGINEERING/Data+Hub+5.8.0

Just added it to the wiki!

2022-07-15 05:08 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/writerScenario2.spec.tsx
> +  });
Can we delete the property at the end of this scenario?

2022-07-15 05:10 UTC, csilva-ml requested changes
Let's delete the property created to make sure it does not impact the rest of the run. There are more modifications for this spec file in other open PRs. Let me know if you need any help @lucianaabc-ml

2022-07-18 15:31 UTC, merged