DHFPROD-9007: Verify sorting in monitor tile
marklogic/marklogic-data-hub pull request #7094
Opened 2022-07-27 15:40 UTC by ngodugu-marklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

2022-07-27 17:46 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +    cy.get(".reset-expansion-style:eq(" + monitorPage.searchBiggerRowIndex(firstPageTableCellsJobId) + ") .stepStartDate").then(($row) => {
Can we move the cy.get's to a page object class? And just those methods from the test

2022-07-27 17:47 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +      orginalDateTimeArr.forEach(element => cy.log(element));
Do we need these logs?

2022-07-27 17:56 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +  it("Validate column order for Step Name,	Step Type,	StatusEntity, Type Start, Date and Time part 3", () => {
Can you change it to a more descriptive title instead of "part 3"?

2022-07-27 17:57 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +      cy.get(".reset-expansion-style:eq(" + monitorPage.searchBiggerRowIndex(firstPageTableCellsJobId) + ") .stepNameDiv").then(($row) => {
Can we move this cy.get to a page object?

2022-07-27 17:57 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +      cy.get(".reset-expansion-style:eq(" + monitorPage.searchBiggerRowIndex(firstPageTableCellsJobId) + ") .stepType").then(($row) => {
same thing here for the cy.get

2022-07-27 17:59 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +      cy.get(".reset-expansion-style:eq(" + monitorPage.searchBiggerRowIndex(firstPageTableCellsJobId) + ") .stepStatus").then(($row) => {
same thing here for the cy.get

2022-07-27 18:01 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +      cy.get(".reset-expansion-style:eq(" + monitorPage.searchBiggerRowIndex(firstPageTableCellsJobId) + ") .stepEntityType").then(($row) => {
same thing here for the cy.get

2022-07-27 18:01 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +      cy.get(".reset-expansion-style:eq(" + monitorPage.searchBiggerRowIndex(firstPageTableCellsJobId) + ") .stepStartDate").then(($row) => {
same thing here for the cy.get

2022-07-27 18:02 UTC, csilva-ml requested changes
Hey, just a couple changes and questions. 
Not sure if we should test every single column  ASC and DESC

2022-07-27 20:12 UTC, ngodugu-marklogic commented
> Hey, just a couple changes and questions. Not sure if we should test every single column ASC and DESC

@csilva-ml Fixed the PR with requested changes, And yes it's better we validate it for columns, just an extra validations for column shouldn’t hurt, we might catch errors if something breaks for any of the column anytime.

2022-07-27 20:51 UTC, csilva-ml commented
> > Hey, just a couple changes and questions. Not sure if we should test every single column ASC and DESC
> 
> @csilva-ml Fixed the PR with requested changes, And yes it's better we validate it for columns, just an extra validations for column shouldn’t hurt, we might catch errors if something breaks for any of the column anytime.

Ok. My guess was that we're using the same functionalities for all columns, and this test has history of being flaky. So I was just wondering if it was worth it to check all of them. Just sharing a different point of view to keep in mind. If you think this is necessary it's ok for me! 
Changes look good !

2022-07-27 20:51 UTC, csilva-ml approved these changes

2022-07-28 18:52 UTC, csilva-ml requested changes

2022-07-28 18:52 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +    //Commenting this validations due to a bug DHFPROD-9157
I think this is not a bug. Holding back the PR so we can look at it

2022-07-28 19:04 UTC, csilva-ml approved these changes

2022-07-28 19:05 UTC, MSBrignoni approved these changes

2022-07-29 13:41 UTC, merged