DHFPROF-9158: In Model, an Entity's version property box is too small…
marklogic/marklogic-data-hub pull request #7129
Opened 2022-08-08 19:22 UTC by lucianaabc-ml

… to see the whole version.

DHFPROF-9158: In Model, an Entity's version property box is too small to see the whole version.

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-08-08 22:16 UTC, briantang requested changes
Since we are making it larger anyways, can we make the width match the end of the input boxes for the above fields? (i.e. description, namespace uri).

Also, can we make the same change for the table view? It has the same version box that needs updating for the entity-type-modal
<img width="543" alt="Screen Shot 2022-08-08 at 3 15 20 PM" src="https://user-images.githubusercontent.com/18374593/183523831-f8629781-86c7-4dd2-94df-40ead0404af9.png">

2022-08-10 17:18 UTC, lucianaabc-ml commented
> Since we are making it larger anyways, can we make the width match the end of the input boxes for the above fields? (i.e. description, namespace uri).
> 
> Also, can we make the same change for the table view? It has the same version box that needs updating for the entity-type-modal <img alt="Screen Shot 2022-08-08 at 3 15 20 PM" width="543" src="https://user-images.githubusercontent.com/18374593/183523831-f8629781-86c7-4dd2-94df-40ead0404af9.png">

Hey @briantang ! It's already the same width for me, that's weird. Maybe you had the devtools open and that changed the width?
![image](https://user-images.githubusercontent.com/94134837/183975955-b8b72b50-3d40-4d96-a36c-bfab7aa650b5.png)

2022-08-10 19:09 UTC, briantang approved these changes

2022-08-11 13:17 UTC, iveyMarklogic approved these changes

2022-08-11 17:18 UTC, merged