DHFPROD-9128: Success Transition and Merge Documents
marklogic/marklogic-data-hub pull request #7131
Opened 2022-08-09 07:32 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-08-09 14:37 UTC, rahulvudutala requested changes

2022-08-09 14:37 UTC, rahulvudutala commented on marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
> +    public ResponseEntity<JsonNode> mergeDocument(@RequestParam List<String> mergeURIs, @RequestParam String flowName, @RequestParam(required = false)  String stepNumber, @RequestParam(required = fal
@briantang There is already another mergeDocument method with the same signature and implementation. You can remove this.

2022-08-09 14:56 UTC, rahulvudutala commented on marklogic-data-hub-central/src/main/java/com/marklogic/hub/central/controllers/steps/MergingStepController.java
> +    public ResponseEntity<JsonNode> mergeDocument(@RequestParam List<String> mergeURIs, @RequestParam String flowName, @RequestParam(required = false)  String stepNumber, @RequestParam(required = fal
I removed the method and force pushed the changes

2022-08-09 16:51 UTC, ryanjdew submitted a review, later dismissed

2022-08-09 19:09 UTC, briantang commented
Looking into some minor test/BE issue with the team.

2022-08-09 22:57 UTC, ryanjdew approved these changes

2022-08-09 23:51 UTC, AkshayBajajML submitted a review, later dismissed

2022-08-10 00:05 UTC, rahulvudutala approved these changes

2022-08-10 00:32 UTC, briantang commented
Couple remaining failures are unrelated except for one tweak I pushed. This should pass on the next cycle.

2022-08-10 00:34 UTC, rahulvudutala approved these changes

2022-08-10 00:50 UTC, AkshayBajajML approved these changes

2022-08-10 02:11 UTC, merged