DHFPROD-9377: Fix the failing intermittent cypress e2e scripts on PRs
marklogic/marklogic-data-hub pull request #7203
Opened 2022-09-09 15:25 UTC by ngodugu-marklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-09-09 16:55 UTC, csilva-ml requested changes

2022-09-09 16:55 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/modeling/graphValidations.spec.tsx
> +    propertyModal.getDeleteIcon("Test1-relTest1Test2").should("be.visible").scrollIntoView().click();
we should put the scroll into view before checking for its visibility. Please let's make that change for all the following with the same

2022-09-09 16:55 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/monitor/monitorTableValidations.spec.tsx
> +    monitorPage.getOrderColumnMonitorTable("Step Name").should("be.visible").scrollIntoView().click({force: true}).then(() => {
same thing about the scroll for this file please

2022-09-12 18:29 UTC, csilva-ml approved these changes

2022-09-12 18:33 UTC, briantang submitted a review, later dismissed

2022-09-12 19:50 UTC, Sanjeevani19 reviewed
@ngodugu-marklogic  Failures showed in the latest run again, http://jenkins1.marklogic.com/blue/organizations/jenkins/Datahub_CI/detail/PR-7203/9/tests, Please look into it ?

2022-09-13 12:40 UTC, iveyMarklogic approved these changes

2022-09-13 12:42 UTC, csilva-ml approved these changes

2022-09-13 12:58 UTC, merged