DHFPROD-9436: GET notification to work when there is no primary key
marklogic/marklogic-data-hub pull request #7248
Opened 2022-09-22 22:57 UTC by rahulvudutala

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-09-22 23:03 UTC, ryanjdew requested changes

2022-09-22 23:03 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/com.marklogic.smart-mastering/matcher-impl/notification-impl.xqy
> +          let $_ := xdmp:log("$xpath")
A couple log statements to cleanup.

2022-09-22 23:36 UTC, briantang approved these changes
Thanks @rahulvudutala issue looks fixed.

2022-09-23 06:06 UTC, ryanjdew approved these changes

2022-09-23 06:08 UTC, merged