DHFPROD-9477: The product group node should not be displayed
marklogic/marklogic-data-hub pull request #7274
Opened 2022-10-05 19:41 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [n/a] Added to Release Wiki

2022-10-06 19:01 UTC, aniamy approved these changes

2022-10-07 19:47 UTC, prolonMarkLogic requested changes
Hello @iveyMarklogic , one thing is that all the concepts are leaf node, and we can expand it, and see something strange.
[Data Hub Central.webm](https://user-images.githubusercontent.com/92050414/194641921-8712b090-0413-4cc6-a539-0a6bc644ddef.webm)

2022-10-07 20:02 UTC, prolonMarkLogic commented
Hi @iveyMarklogic  another thing is that some nodes has the leaf icon, but we can't expand them.
[Data Hub Central (1).webm](https://user-images.githubusercontent.com/92050414/194644018-b7275897-12f1-43a3-8269-52dbb76a6a51.webm)

2022-10-10 14:07 UTC, iveyMarklogic commented
@prolonMarkLogic  some nodes have the leaf icon because the backend responds as a node with relations 
![image](https://user-images.githubusercontent.com/88790827/194884879-d0c83b37-5cd4-479b-ba6c-e9f6df8d824c.png)

2022-10-11 13:48 UTC, prolonMarkLogic approved these changes

2022-10-11 18:15 UTC, merged