DHFPROD-9489: Fixes Win10 Chrome
marklogic/marklogic-data-hub pull request #7277
Opened 2022-10-07 16:04 UTC by eeduardo-marklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-10-07 17:34 UTC, Sanjeevani19 reviewed
@eeduardo-marklogic I see a lot of e2e failures mentioned in the JIRA ticket, but I only see one test file has been modified, Are they all related to each other ?

2022-10-10 16:53 UTC, csilva-ml requested changes

2022-10-10 16:53 UTC, csilva-ml commented on marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
> +    //Agregar al page object
please remove this  comment

2022-10-11 13:42 UTC, eeduardo-marklogic commented on marklogic-data-hub-central/ui/e2e/cypress/integration/mastering/e2eMasteringflow.spec.tsx
> +    //Agregar al page object
Done.

2022-10-11 17:05 UTC, ngodugu-marklogic approved these changes

2022-10-11 20:14 UTC, Sanjeevani19 approved these changes

2022-10-12 13:02 UTC, merged