DHFPROD-9565: New entity property selector
marklogic/marklogic-data-hub pull request #7288
Opened 2022-10-17 21:27 UTC by iveyMarklogic

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-10-18 16:30 UTC, littlecherro commented on marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
> +        // menuProps.unshift({ value: ".", key:".", label: " - instance - ", type: "string" });
there's a comment here, should be removed but is it there for a reason or something?

2022-10-18 16:51 UTC, iveyMarklogic commented on marklogic-data-hub-central/ui/src/components/modeling/graph-view/relationship-modal/add-edit-relationship.tsx
> +      await setDisplayPropertyList(true);
@littlecherro both comments were fixed on my last updated.

2022-10-18 19:25 UTC, prolonMarkLogic submitted a review, later dismissed

2022-10-19 13:17 UTC, littlecherro approved these changes

2022-10-19 13:47 UTC, MSBrignoni reviewed
@iveyMarklogic when we have a structured property and another nested with the same name, the component is not showing the "/" properly, this can be tackled in this PR or another.

https://user-images.githubusercontent.com/89084298/196709315-5e5f82db-dca3-4b05-848c-a4f3256835be.mp4

2022-10-19 15:38 UTC, rahulvudutala commented
@iveyMarklogic Did we conclude on using dot(.) notation or (/) notation for the context?
Also, the indentation for shipping, zip, fiveDigit doesn't look correct in the attached screenshot. nicknames and shipping should be on the same level. fiveDigit, plusFour and geopoint should be right indented to zip and should be on the same level

<img width="1536" alt="Screen Shot 2022-10-19 at 8 35 42 AM" src="https://user-images.githubusercontent.com/18605155/196738610-c9940a0e-e10e-44b6-b8fc-656e2c752b99.png">

2022-10-19 15:41 UTC, rahulvudutala requested changes
@iveyMarklogic Did we conclude on using dot(.) notation or (/) notation for the context?
Also, the indentation for shipping, zip, fiveDigit doesn't look correct in the attached screenshot. nicknames and shipping should be on the same level. fiveDigit, plusFour and geopoint should be right indented to zip and should be on the same level

<img width="1536" alt="Screen Shot 2022-10-19 at 8 30 02 AM" src="https://user-images.githubusercontent.com/18605155/196739150-5c979f4c-76f2-44d2-a0c8-06424ca5ee49.png">

2022-10-19 16:14 UTC, iveyMarklogic commented
@rahulvudutala and @MSBrignoni the indentation was fixed in my last update
![image](https://user-images.githubusercontent.com/88790827/196746962-14c87be6-cf22-4c3d-b725-de5e5522e7e9.png)
![image](https://user-images.githubusercontent.com/88790827/196747029-d5ea2868-81fc-4343-9607-dd5a645409db.png)

2022-10-19 16:19 UTC, iveyMarklogic commented
@rahulvudutala we conclude on using (/) notation to be consistent with the mapping and also with the expression section
![image](https://user-images.githubusercontent.com/88790827/196747756-7b41cb02-7408-4498-aca1-54373b11c97d.png)

2022-10-19 17:52 UTC, rahulvudutala approved these changes

2022-10-19 18:03 UTC, MSBrignoni approved these changes

2022-10-19 19:40 UTC, merged