DHFPROD-9560: Related Concepts Faceting Rework to Filter
marklogic/marklogic-data-hub pull request #7305
Opened 2022-10-21 19:24 UTC by briantang

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [x] Added to Release Wiki

2022-10-25 03:35 UTC, prolonMarkLogic requested changes
Hi @briantang, the tooltip is showing the related entities message
![image](https://user-images.githubusercontent.com/92050414/197676347-677d6308-4591-4c93-93ac-040a9859d13d.png)

2022-10-26 15:28 UTC, prolonMarkLogic submitted a review, later dismissed
good job! I was testing and works fine!

2022-10-26 18:14 UTC, iveyMarklogic submitted a review, later dismissed

2022-10-27 17:41 UTC, iveyMarklogic submitted a review, later dismissed

2022-10-28 14:08 UTC, iveyMarklogic approved these changes

2022-10-28 14:51 UTC, prolonMarkLogic approved these changes

2022-10-30 21:55 UTC, briantang commented
All tests passing, just needs reviews.

2022-10-31 12:56 UTC, prolonMarkLogic approved these changes

2022-10-31 12:57 UTC, iveyMarklogic approved these changes

2022-10-31 13:08 UTC, merged