DHFPROD-9538: Readme and runFlows automation for realestate example project
marklogic/marklogic-data-hub pull request #7309
Opened 2022-10-26 03:41 UTC by senumulapally

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit

2022-10-27 15:17 UTC, Sanjeevani19 approved these changes

2022-10-27 22:44 UTC, ngodugu-marklogic requested changes
@senumulapally Some of the steps in Data_Ingestion, Data_Mapping and Data_Matching are failing. Please take a look at it. And also the ReadMe says we can Log in using the credentials hub-developer and password but I think we need to update ReadMe with the right password or change the password in mlconfig.

2022-11-09 15:20 UTC, littlecherro approved these changes

2022-11-09 18:33 UTC, prolonMarkLogic approved these changes

2022-11-10 17:54 UTC, ngodugu-marklogic approved these changes

2022-11-10 17:55 UTC, merged