DHFPROD-9611: Clean up Console Warnings - Merging Step Details
marklogic/marklogic-data-hub pull request #7324
Opened 2022-11-01 18:05 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Code passes ESLint tests
- [ n/a] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

2022-11-02 18:51 UTC, MSBrignoni requested changes
Looks good, I noticed this to change @amejiaq, can you double-check the styles?
![image](https://user-images.githubusercontent.com/89084298/199576649-0fc9ff07-a027-42d8-b842-caf4186fdffa.png)

2022-11-03 18:23 UTC, littlecherro approved these changes

2022-11-04 13:57 UTC, MSBrignoni approved these changes

2022-11-07 17:32 UTC, ngodugu-marklogic commented
The E2E test failure should be fixed as part of https://github.com/marklogic/marklogic-data-hub/pull/7345. We can merge this PR manually @Sanjeevani19

2022-11-07 18:07 UTC, merged