DHFPROD-9329: Problem deleting concept class and relationship
marklogic/marklogic-data-hub pull request #7388
Opened 2022-11-15 12:20 UTC by eeduardo-marklogic

DHFPROD-9329 Creating/Deleting relationship

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Code passes ESLint tests
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-12-09 18:05 UTC, MSBrignoni approved these changes

2022-12-12 17:55 UTC, briantang submitted a review, later dismissed

2022-12-13 13:34 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +  it("Create/Delete new relationship and new concept class from Table view", {defaultCommandTimeout: 120000}, () => {
Any reason why we need to change the default timeout?

2022-12-13 13:37 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +  it("Create/Delete new relationship and new concept class from Table view", {defaultCommandTimeout: 120000}, () => {
Why not move this it before we delete the TestConcept? That past is already tested in the previous create and edit tests. And focus only on the relationship. Then the delete test cleans the concept.

2022-12-13 13:46 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +    entityTypeTable.getConceptClass("TestConcept").should("exist").scrollIntoView();
No need to tests all this part. The tests "Create/Edit and verify new concept class from Table view" is already doing all this checks.
Also I do not see the part were we create and edit a relationship related to a concept.

2022-12-13 13:48 UTC, aniamy requested changes
See comments

2022-12-15 18:41 UTC, MSBrignoni submitted a review, later dismissed

2022-12-15 19:05 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +    modelPage.toggleColorSelector("testDeleteStyle");
Again, I suggest we do this test one it above and re-use the Concept class alreadt created to optimize the times.
In this test we don't need to re-test things like picking colors and descriptions. We already covered this above.

2022-12-15 19:07 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +    cy.log("**Create a relationship with the created concept class**");
Suggestion, the it should start here using the concept we already have created in this file.

2022-12-15 19:20 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +    cy.waitUntil(() => toolbar.getModelToolbarIcon()).click();
We are already in the model tile. In this scenario there is no need to click the tile icon

2022-12-15 19:23 UTC, aniamy commented on marklogic-data-hub-central/ui/e2e/cypress/e2e/modeling/verifyConceptClassesInModeling.cy.tsx
> +    graphViewSidePanel.getDeleteIcon("testDeleteStyle").scrollIntoView().click({force: true});
Continuing with the suggestion: This part, deleting the concept, would be handled by the last it so we wouldn't need it.

2022-12-20 17:45 UTC, aniamy submitted a review, later dismissed

2022-12-20 17:50 UTC, ngodugu-marklogic approved these changes

2022-12-20 20:11 UTC, ngodugu-marklogic submitted a review, later dismissed

2022-12-21 14:54 UTC, aniamy approved these changes

2022-12-21 15:06 UTC, MSBrignoni approved these changes

2022-12-21 15:35 UTC, merged