DHFPROD-9661: Relationships with structured props missing from the model
marklogic/marklogic-data-hub pull request #7456
Opened 2022-11-30 20:14 UTC by littlecherro

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2022-12-02 14:16 UTC, iveyMarklogic requested changes
@littlecherro  When the user removes the structured property the relationship still shows on the graph 

https://user-images.githubusercontent.com/88790827/205312865-ed3977b1-0d6f-4bd1-9cec-382a461ad631.mp4

2022-12-07 15:14 UTC, aniamy submitted a review, later dismissed

2022-12-07 16:35 UTC, iveyMarklogic submitted a review, later dismissed

2022-12-12 17:53 UTC, aniamy approved these changes

2022-12-12 18:08 UTC, iveyMarklogic submitted a review, later dismissed

2022-12-14 12:40 UTC, iveyMarklogic approved these changes

2022-12-14 16:15 UTC, closed without merging