DHFPROD-8074: Keyboard accessibility for Sidebar of Explorer
marklogic/marklogic-data-hub pull request #7549
Opened 2023-01-10 16:10 UTC by littlecherro

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- n/a Added to Release Wiki

2023-01-11 20:39 UTC, aniamy requested changes
Already talked with Cherro. Found an issue where "Staging" wasn¡t chaning color when selected.
And "Related Entities" checkbox could not be reached.

2023-01-23 15:17 UTC, iveyMarklogic submitted a review, later dismissed

2023-01-23 19:21 UTC, aniamy submitted a review, later dismissed

2023-01-24 15:33 UTC, iveyMarklogic approved these changes

2023-01-24 15:35 UTC, aniamy approved these changes

2023-01-24 15:44 UTC, merged