DHFPROD-9750: Use real data for Create, Edit and copy lists
marklogic/marklogic-data-hub pull request #7560
Opened 2023-01-17 19:33 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [x] Added to Release Wiki

2023-01-17 19:42 UTC, littlecherro commented on marklogic-data-hub-central/ui/src/api/__mocks__/mocks.data.ts
> +        "data": {"name": "Preset List 1", "values": ["uno", "dos", "uno", "dos", "uno", "dos", "uno", "dos"]},
i get what you meant to do here but i think we should stick to the same language through the app :)

2023-01-17 19:42 UTC, littlecherro commented on marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
> +      listValues={["Uno"]}
same here :)

2023-01-17 19:42 UTC, littlecherro commented on marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
> +      listValues={["Uno"]}
here too

2023-01-17 19:43 UTC, littlecherro commented on marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
> +            "values": ["uno", "dos", "uno", "dos", "uno", "dos", "uno", "dos"]
:)

2023-01-17 19:54 UTC, amejiaq commented on marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
> +      listValues={["Uno"]}
Done!

2023-01-17 19:54 UTC, amejiaq commented on marklogic-data-hub-central/ui/src/components/entities/matching/ruleset-single-modal/ruleset-single-modal.test.tsx
> +            "values": ["uno", "dos", "uno", "dos", "uno", "dos", "uno", "dos"]
Done!

2023-01-18 14:50 UTC, MSBrignoni requested changes
Looks good! there is only this little detail, perhaps is possible to control this in the front:



https://user-images.githubusercontent.com/89084298/213202956-c1a56d69-b359-432f-b1d7-e9dfe7b3a5cd.mp4

2023-01-18 15:00 UTC, amejiaq commented
> Looks good! there is only this little detail, perhaps is possible to control this in the front:
> 
>  Screen_Recording_.1-18-2023_11-44-29_AM.mp4

This behavior will be review it in this ticket https://project.marklogic.com/jira/browse/DHFPROD-9811

2023-01-19 12:48 UTC, MSBrignoni approved these changes

2023-01-20 13:19 UTC, littlecherro approved these changes

2023-01-20 19:55 UTC, merged