DHFPROD-6741: Curate + Run: Add focus state to expand/collapse component
marklogic/marklogic-data-hub pull request #7561
Opened 2023-01-17 20:01 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [n/a] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [n/a] Added to Release Wiki

2023-01-18 18:28 UTC, littlecherro submitted a review, later dismissed

2023-01-18 18:35 UTC, briantang requested changes
When I hit "TAB" from this point in the screenshot, the 'No Entity Type' panel does not have the focus state. That part lies probably somewhere else in the code and needs to be added in.

<img width="1676" alt="Screen Shot 2023-01-18 at 10 34 32 AM" src="https://user-images.githubusercontent.com/18374593/213265477-18470ee7-911d-4722-9e94-e0d73f2be25f.png">

2023-01-18 19:12 UTC, amejiaq commented
> When I hit "TAB" from this point in the screenshot, the 'No Entity Type' panel does not have the focus state. That part lies probably somewhere else in the code and needs to be added in.
> 
> <img alt="Screen Shot 2023-01-18 at 10 34 32 AM" width="1676" src="https://user-images.githubusercontent.com/18374593/213265477-18470ee7-911d-4722-9e94-e0d73f2be25f.png">

Fixed! 🛠

2023-01-19 01:24 UTC, briantang approved these changes

2023-01-19 13:27 UTC, littlecherro approved these changes

2023-01-19 16:46 UTC, merged