DHFPROD-9811: Additional Error Validation For Create New List
marklogic/marklogic-data-hub pull request #7582
Opened 2023-01-26 21:27 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [n/a] Added to Release Wiki

2023-01-27 18:40 UTC, MSBrignoni approved these changes

2023-01-30 18:06 UTC, briantang requested changes
Looks good @amejiaq. One thing with the existing duplicate value error message:

<img width="507" alt="Screenshot 2023-01-30 at 10 06 08 AM" src="https://user-images.githubusercontent.com/18374593/215558284-81ee03c6-4e40-4a0f-843e-474205f4ece3.png">

Can we upgrade the text to as follows?

The value **"duplicate_example"** already exists in this list. Please enter a unique value to ignore.

2023-01-31 07:09 UTC, briantang requested changes
<img width="499" alt="Screenshot 2023-01-30 at 11 05 42 PM" src="https://user-images.githubusercontent.com/18374593/215690278-491731b7-ddea-4840-a37c-e82f07d36dad.png">

Can we add a period to the end of the error message?

Also, sorry for the confusion, but actually I think the referenced value should only be bolded with no surrounding quotes, to be consistent with other parts of the app (duplicate entity name, property name, etc.).

For example,

The value **a** already exists in this list.

2023-01-31 16:32 UTC, amejiaq commented
@briantang  Fixed 🛠

2023-01-31 17:04 UTC, briantang requested changes

2023-01-31 17:04 UTC, briantang commented on marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
> +    expect(screen.queryAllByText(errorText)).toHaveLength(1);
If possible, can we also add a check here to verify the latest duplicate values error?

2023-01-31 18:11 UTC, briantang approved these changes

2023-01-31 18:11 UTC, briantang commented on marklogic-data-hub-central/ui/src/components/entities/matching/list-modal/list-modal.test.tsx
> +import {getSubElements} from "@util/test-utils";
Nice :)

2023-01-31 19:32 UTC, littlecherro approved these changes

2023-01-31 21:58 UTC, merged