DHFPROD-9853: Facet Selection is not retaining selection
marklogic/marklogic-data-hub pull request #7598
Opened 2023-01-31 19:09 UTC by littlecherro

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- N/A Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- N/A Reviewed Tests
- N/A Added to Release Wiki

2023-01-31 20:03 UTC, MSBrignoni requested changes

2023-01-31 20:03 UTC, MSBrignoni commented on marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
> +      {Object.keys(greyedOptions.selectedFacets).length > 0 &&
In this case @littlecherro, could be possible to add an extra control before the ".lenght" to check an undefined?

2023-01-31 20:03 UTC, MSBrignoni commented on marklogic-data-hub-central/ui/src/components/selected-facets/selected-facets.tsx
> +      {Object.keys(greyedOptions.selectedFacets).length > 0 &&
Same here :)

2023-01-31 20:26 UTC, MSBrignoni submitted a review, later dismissed

2023-02-01 17:47 UTC, briantang approved these changes

2023-02-02 17:29 UTC, aniamy approved these changes

2023-02-02 18:23 UTC, MSBrignoni approved these changes

2023-02-03 13:36 UTC, merged