DHFPROD-9840: Disable Merge Icons with Missing Permissions
marklogic/marklogic-data-hub pull request #7604
Opened 2023-02-01 22:29 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [n/a] Added to Release Wiki

2023-02-03 09:34 UTC, briantang requested changes
Icon Disabling needs to be added to notifications modal and also All Data View (record-view.tsx)

<img width="1213" alt="Screenshot 2023-02-03 at 1 32 06 AM" src="https://user-images.githubusercontent.com/18374593/216564401-ffdfc3a4-dbb7-4fdd-8645-426d60415289.png">

Can we update the text as well to tell the user what is disabled?
Depending on the icon, it should either say:

"Unmerge: Contact your security administrator for access "
or
"Merge: Contact your security administrator for access"

2023-02-03 17:33 UTC, amejiaq commented
@briantang  added the missing feature, and their respective unit test and e2e

2023-02-07 17:52 UTC, iveyMarklogic approved these changes

2023-02-07 22:09 UTC, briantang approved these changes

2023-02-08 00:16 UTC, merged