DHFPROD-7309: Match Keyboard Accessibility
marklogic/marklogic-data-hub pull request #7615
Opened 2023-02-07 17:32 UTC by littlecherro

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [ ] JIRA_ID included in all the commit messages
- [ ] PR title is in the format JIRA_ID:Title
- [ ] Rebase the branch with upstream
- [ ] Squashed all commits into a single commit
- [ ] Added Tests
- [ ] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2023-02-09 17:51 UTC, amejiaq approved these changes
Pretty solution for the unit test!

2023-02-09 18:21 UTC, littlecherro commented
Notes: 
The select component on Values to Ignore doesn't behaves as expected. There's going to be a ticket for that.
Also, there's an issue with TreeSelect component where is almost impossible to reach the styles when its focused, so a workaround was implemented for that.

2023-02-09 18:22 UTC, briantang requested changes
<img width="1647" alt="Screenshot 2023-02-09 at 10 21 47 AM" src="https://user-images.githubusercontent.com/18374593/217903238-b476edf4-151b-410c-b036-f8d1b2dd8d8a.png">

I can't seem to select the other radio options "Test URIs with All Data" and "Test All Data"

2023-02-09 18:23 UTC, briantang commented on marklogic-data-hub-central/ui/src/components/entities/matching/matching-step-detail/matching-step-detail.test.tsx
> +  it.only("Keyboard Navigation sequence is correct", async () => {
May have forgotten to remove the "only" here

2023-02-09 18:24 UTC, littlecherro commented
> <img alt="Screenshot 2023-02-09 at 10 21 47 AM" width="1647" src="https://user-images.githubusercontent.com/18374593/217903238-b476edf4-151b-410c-b036-f8d1b2dd8d8a.png">
> 
> I can't seem to select the other radio options "Test URIs with All Data" and "Test All Data"

try with the arrows :) 

![image](https://user-images.githubusercontent.com/108084664/217903735-4098ca96-dab3-4a4a-b069-0de6e5ab05e5.png)

2023-02-09 18:26 UTC, littlecherro commented
> <img alt="Screenshot 2023-02-09 at 10 21 47 AM" width="1647" src="https://user-images.githubusercontent.com/18374593/217903238-b476edf4-151b-410c-b036-f8d1b2dd8d8a.png">
> 
> I can't seem to select the other radio options "Test URIs with All Data" and "Test All Data"

@briantang try the arrows 🤔
![image](https://user-images.githubusercontent.com/108084664/217904032-3d981cb8-fa25-4142-bba9-73355095ad62.png)

2023-02-09 18:26 UTC, briantang commented
> > <img alt="Screenshot 2023-02-09 at 10 21 47 AM" width="1647" src="https://user-images.githubusercontent.com/18374593/217903238-b476edf4-151b-410c-b036-f8d1b2dd8d8a.png">
> > I can't seem to select the other radio options "Test URIs with All Data" and "Test All Data"
> 
> @briantang try the arrows 🤔 ![image](https://user-images.githubusercontent.com/108084664/217904032-3d981cb8-fa25-4142-bba9-73355095ad62.png)

Oops right I see that working now.

2023-02-09 18:27 UTC, briantang approved these changes

2023-02-09 18:30 UTC, amejiaq approved these changes

2023-02-10 13:36 UTC, amejiaq submitted a review, later dismissed

2023-02-13 16:46 UTC, briantang approved these changes

2023-02-13 19:42 UTC, amejiaq approved these changes

2023-02-14 13:21 UTC, merged