DHFPROD-9922: Limit Table Width in Explore
marklogic/marklogic-data-hub pull request #7640
Opened 2023-02-13 17:40 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [n/a] Added to Release Wiki

2023-02-13 17:54 UTC, briantang requested changes
I feel like there is some more space for this to run here. Could we try increasing the lettersToCut limit to maybe 26 chars?

<img width="604" alt="Screenshot 2023-02-13 at 9 49 34 AM" src="https://user-images.githubusercontent.com/18374593/218533935-2dbf0f97-0dae-4a2a-8e40-5813f854b1c8.png">

2023-02-13 18:15 UTC, amejiaq commented
> I feel like there is some more space for this to run here. Could we try increasing the lettersToCut limit to maybe 26 chars?
> 
> <img alt="Screenshot 2023-02-13 at 9 49 34 AM" width="604" src="https://user-images.githubusercontent.com/18374593/218533935-2dbf0f97-0dae-4a2a-8e40-5813f854b1c8.png">



> 

Brian it was set to trim in 40 letters, I increase the value to 65 Please tell me if is enough

2023-02-14 17:36 UTC, briantang approved these changes
Looks great now @amejiaq. Thanks!

2023-02-15 17:16 UTC, briantang submitted a review, later dismissed

2023-02-15 17:28 UTC, littlecherro submitted a review, later dismissed

2023-02-16 04:20 UTC, briantang approved these changes

2023-02-16 15:12 UTC, MSBrignoni approved these changes

2023-02-16 17:06 UTC, merged