DHFPROD-9900: Unmerge Modal Column Order
marklogic/marklogic-data-hub pull request #7642
Opened 2023-02-13 19:12 UTC by MSBrignoni

### Description

Unmerge Modal Column Order

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran cypress tests on firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- n/a Added to Release Wiki

2023-02-17 16:05 UTC, briantang requested changes
I see some different fontstyles here. Is it intended?

<img width="1555" alt="Screenshot 2023-02-17 at 8 04 47 AM" src="https://user-images.githubusercontent.com/18374593/219704533-16135e93-6767-445f-9e1d-425b52b4457b.png">

2023-02-17 19:57 UTC, MSBrignoni commented
> I see some different fontstyles here. Is it intended?
> 
> <img alt="Screenshot 2023-02-17 at 8 04 47 AM" width="1555" src="https://user-images.githubusercontent.com/18374593/219704533-16135e93-6767-445f-9e1d-425b52b4457b.png">

Thanks!, done, I removed some styles there 
![image](https://user-images.githubusercontent.com/89084298/219779137-13e5f1c5-8567-41c4-860b-7b894b2a2a40.png)

2023-02-17 20:43 UTC, briantang approved these changes

2023-02-21 19:18 UTC, amejiaq approved these changes

2023-02-21 21:38 UTC, merged