DHFPROD-9918: Add boolean data to Person and test table boolean values
marklogic/marklogic-data-hub pull request #7710
Opened 2023-03-09 15:02 UTC by vmendez-marklogic

DHFPROD-9918: Add boolean data to Person and test table boolean values

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [X ] JIRA_ID included in all the commit messages
- [X ] PR title is in the format JIRA_ID:Title
- [X] Rebase the branch with upstream
- [X] Squashed all commits into a single commit
- [X] Added Tests
- [X] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2023-03-09 17:48 UTC, aniamy approved these changes

2023-03-13 01:18 UTC, briantang requested changes
Solution and tests look good, just one small thing on terminology. For the new entry we are adding with "CurrentlyClient", it may be a little too similar to potential relationships that can be done with a Client entity. Can I suggest making it something more "Person"-specific, such as **"Verified"** true/false. Hope that makes sense, let me know if any questions or concerns.

2023-03-14 16:48 UTC, briantang submitted a review, later dismissed

2023-03-14 17:58 UTC, aniamy commented
@vmendez-marklogic There is a lint issue in the pipeline. Please take a look at the logs.

2023-03-14 21:53 UTC, aniamy submitted a review, later dismissed

2023-03-15 13:18 UTC, iveyMarklogic submitted a review, later dismissed

2023-03-17 13:45 UTC, aniamy approved these changes

2023-03-17 16:59 UTC, briantang approved these changes

2023-03-20 20:58 UTC, merged