DHFPROD-10026: Extra nodes in Graph View when using latest SLED Project
marklogic/marklogic-data-hub pull request #7778
Opened 2023-03-30 19:07 UTC by littlecherro

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [x] Reviewed Tests
- [x] Added to Release Wiki

2023-03-31 20:35 UTC, aniamy submitted a review, later dismissed

2023-04-05 19:35 UTC, ngodugu-marklogic commented
https://user-images.githubusercontent.com/74939216/230185774-e6bca152-ac24-4fd9-a129-fbe4f66f853a.mov

The message just comes up initially and then disappears when I switch between nodes

2023-04-05 19:58 UTC, ngodugu-marklogic requested changes
The message just comes up initially and then disappears when I switch between nodes

https://user-images.githubusercontent.com/74939216/230193840-568db662-0aff-43c4-9f5a-34d403de63af.mov

2023-04-12 16:05 UTC, ngodugu-marklogic approved these changes

2023-04-12 17:02 UTC, aniamy approved these changes

2023-04-13 18:27 UTC, merged