DHFPROD-9446: Add document permissions to Artifact Events and Instanc…
marklogic/marklogic-data-hub pull request #7792
Opened 2023-04-10 15:19 UTC by prolonMarkLogic

…e Events

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [n/a] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2023-04-10 21:00 UTC, ryanjdew requested changes

2023-04-10 22:35 UTC, prolonMarkLogic commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/features/doc-permissions.mjs
> +    contentObject.context.permissions = contentPermissions.concat("," + permissions);
Good catch! I pushed one change for it, thanks

2023-04-11 12:39 UTC, aniamy approved these changes

2023-04-11 15:44 UTC, ryanjdew approved these changes

2023-04-11 17:02 UTC, rahulvudutala approved these changes

2023-04-11 17:15 UTC, merged