DHFPROD-10289: Incorrect position of the information modal
marklogic/marklogic-data-hub pull request #7880
Opened 2023-06-02 22:26 UTC by amejiaq

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [n/a] Added to Release Wiki

2023-06-05 20:54 UTC, aniamy approved these changes

2023-06-06 14:54 UTC, briantang requested changes
Looks like your solution also removed the keyboard navigation selection (SPACE/ENTER to open/close the info modal). Can that be fixed in this same PR?

2023-06-06 16:24 UTC, amejiaq commented
> Looks like your solution also removed the keyboard navigation selection (SPACE/ENTER to open/close the info modal). Can that be fixed in this same PR?

Fixed 🛠🛠🛠

2023-06-09 16:09 UTC, briantang approved these changes

2023-06-09 16:51 UTC, merged