DHFPROD-10244: BE:Step Test does not use pre-step interceptor, with X…
marklogic/marklogic-data-hub pull request #7912
Opened 2023-06-19 19:49 UTC by prolonMarkLogic

…ML document format

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [n/a] Added Tests
- [n/a] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [ ] Added to Release Wiki

2023-06-20 16:15 UTC, ryanjdew requested changes

2023-06-20 16:15 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
> +    sourceDocument = cts.doc(uri).toObject();
this can be docActual.toObject(); We don't want to call cts.doc more than necessary.

2023-06-20 16:15 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
>        if (sourceDocument) {
This can move into the prior if condition.

2023-06-20 16:15 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
> +      if (updatedDocument && updatedDocument.format === "XML") {
This can become an else if (...) branch.

2023-06-20 16:15 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
> +         { database: xdmp.database(config.STAGINGDATABASE) }
We can't assume that the document will be in the staging database.

2023-06-20 16:15 UTC, ryanjdew commented on marklogic-data-hub/src/main/resources/ml-modules/root/data-hub/5/builtins/steps/mapping/entity-services/lib.mjs
> +            xdmp.nodeReplace(instanceNode, xmlTransform);
We shouldn't be updating content in the database as part of testing/validating data.

2023-06-21 20:40 UTC, ryanjdew submitted a review, later dismissed

2023-06-22 21:00 UTC, briantang submitted a review, later dismissed

2023-06-23 15:32 UTC, ryanjdew commented
@prolonMarkLogic I think to best avoid complications with the XML -> JSON -> XML, we can add an option to mapping/getDocument.mjs Data Service to return the XML as XML and use that option here.

2023-06-23 15:34 UTC, ryanjdew requested changes
See latest comment about adding an option to mapping/getDocument.mjs

2023-06-24 03:43 UTC, ryanjdew approved these changes

2023-06-26 13:24 UTC, aniamy approved these changes

2023-06-26 15:05 UTC, merged