DHFPROD-10424: Matched entities table renders empty before request is…
marklogic/marklogic-data-hub pull request #7946
Opened 2023-07-18 21:15 UTC by amejiaq

… done

### Description

#### Checklist: 
```diff
- Note: do not change the below
```

- ##### Owner:

- [x] JIRA_ID included in all the commit messages
- [x] PR title is in the format JIRA_ID:Title
- [x] Rebase the branch with upstream
- [x] Squashed all commits into a single commit
- [x] Added Tests
- [x] Ran newly added/edited cypress tests on Firefox locally
  

- ##### Reviewer:

- [ ] Reviewed Tests
- [n/a] Added to Release Wiki

2023-07-21 17:04 UTC, briantang requested changes
Rather than create a new it() block, could we just verify this line 
`matchingStepDetail.getEmptyMatchedEntities().should("not.exist");`

by squeezing it into the existing blocks that already click the Test button for each of the URI types?

For example, matching.cy.tsx:431, matching.cy.tsx:501...

2023-07-21 19:23 UTC, aniamy approved these changes

2023-07-21 20:07 UTC, amejiaq commented
> Rather than create a new it() block, could we just verify this line `matchingStepDetail.getEmptyMatchedEntities().should("not.exist");`
> 
> by squeezing it into the existing blocks that already click the Test button for each of the URI types?
> 
> For example, matching.cy.tsx:431, matching.cy.tsx:501...

🛠Fixed🛠

2023-07-24 17:12 UTC, briantang approved these changes

2023-07-24 19:51 UTC, aniamy approved these changes

2023-07-24 19:53 UTC, merged